### ISSUE TITLE
采用xeLatex编译器

### ISSUE THREAD

**Issue by hansomesong** [ElegantLaTeX/ElegantBook#1]
在Overleaf中编辑，默认编译器是 pdfLatex 报了一对错。希望可以在README说明 使用 xeLatex编译器

**Comment by Liam0205** [comment]
@hansomesong 你可以提一个 Pull Request。

**Comment by EthanDeng** [comment]
@hansomesong 你可以在 overleaf 和 本地分别试下下面的代码（都用 PDFLaTeX ）：

```tex
\documentclass{article}

\usepackage[UTF8]{ctex}

\title{Test}
\author{author}

\begin{document}

\maketitle

\section{Introduction}
There is a theory which states that if ever anyone discovers exactly what the Universe.

中文。


\end{document}
```

**Comment by Varuto** [comment]
NB

**Comment by EthanDeng** [comment]
本地（TeX Live 2018）是没问题的，但是 Overleaf 报错。也就是说，其实这个问题不是这个模板本身的问题，而是在 Overleaf 上，ctex 宏包没法使用 PDFLaTeX 编译。

**Comment by Liam0205** [comment]
@EthanDeng CTeX 宏包在没有指定字体的情况下，默认使用 Fandol 字体。而 Fandol 字体没法在 PDFLaTeX 下以 zhmetrics 技术实现中文支持。换其他字体是 okay 的。

**Comment by EthanDeng** [comment]
> @EthanDeng CTeX 宏包在没有指定字体的情况下，默认使用 Fandol 字体。而 Fandol 字体没法在 PDFLaTeX 下以 zhmetrics 技术实现中文支持。换其他字体是 okay 的。

关键不是在于 Overleaf 不能编译，但是本地 TeX Live 能编译吗？这里面的区别是什么？我不太懂 Overleaf 里面是怎么样的（TeX Live 2017？）。
