### ISSUE TITLE
[提问建议]建立一个提问模板

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#100]
仿照 [https://github.com/CTeX-org/forum/blob/master/.github/ISSUE_TEMPLATE/question.md](https://github.com/CTeX-org/forum/blob/master/.github/ISSUE_TEMPLATE/question.md)，建立一个提问用的模板，好处：
- 帮助提问者理清思路
- 帮助提问者一次性提供 MWE

例子：
- [ ]功能请求
- [ ]bug 反馈
- [ ]使用疑问
发行版
- [ ]TeX Live 20xx

**Comment by EthanDeng** [comment]
我觉得可以有一个提问说明，但是不要搞模板，说明里让他们给出

1. 系统
2. TeX 套装
3. 模板版本

如果是报告 bug，给出 MWE，然后以及报错信息，最好附上 log 文件。

如果是修改模板效果或者建议，可以给出图示或者详细说明，同样给出 MWE。

**Comment by EthanDeng** [comment]
@sikouhjw 你要不写一个  ElegantLaTeX 提问说明须知，简化一些，方便操作，方便理解就行。

比如可以给出一个示例：

> 我在 Win10 上用 TeX Live 2020 编译 ElegantBook 3.11 版本出现下面错误....blah blah

**Comment by EthanDeng** [comment]
我其实试着按照他们的提问来写一个 question.md，然后写着写着，我觉得这玩意太麻烦了，我自己都不愿意填写，还要说怎么填写这个 question.md，想想还是算了，问题表达清楚就好了，可以不断提问和回答，如果提问者没有特别明确的话。

**Comment by sikouhjw** [comment]
# 编译报错

我在 win10（mac/linux）上用 TeX Live 2020（Miktex）编译 ElegantBook 3.11（ElegantNote 2.30/ElegantPaper 0.09）版本时，出现报错，编译方式为 XeLaTeX（pdfLaTeX），这是我的注释掉无关代码后的 MWE：
```tex
\documentclass{elegantbook}
\begin{document}
  \latex
\end{document}
```
报错为
```tex
./1.tex:3: Undefined control sequence.
l.3   \latex
```
后缀为 `.log` 的文件附在这（从 `Attach files by dragging & dropping, selecting or pasting them.` 那上传文件）

`<文件.log>`

我还有图片/bib 文件，报错在图片/bib 文件这里，我将
- `.tex`
- `.bib`
- 图片

文件压缩成压缩文件，附在这

`<文件.rar/.zip>`

---------------
# 功能请求/需求实现

我在使用 ElegantBook，我想改其中的一些设置：
- 给 `\cover` 和 `\logo` 设置缺省值

这是我想要的效果图
https://user-images.githubusercontent.com/49770925/72252368-1fef4900-363a-11ea-9267-ee716a1c2c58.png
我的代码实现是这样的：
```tex
……
```
具体参考https://github.com/ElegantLaTeX/ElegantBook/issues/74

------------------
# 使用疑问

我在使用 ElegantBook，我打算用它来写一本书，但我不知道怎么将正文分成多个子文件插入到主文件中，能教教我吗
