### ISSUE TITLE
定义列表未加粗

### ISSUE THREAD

**Issue by annProg** [ElegantLaTeX/ElegantBook#101]
自定义 `mainfont` 之后，定义列表没有加粗效果

```latex
\documentclass[cn]{elegantbook}
\setmainfont[]{Source Sans Pro}

\begin{document}
\begin{description}
\item[Linux]
Linux
\end{description}
\end{document}
```

![image](https://user-images.githubusercontent.com/4145852/83811219-f79cdf80-a6eb-11ea-9419-b1992d2ceea6.png)

去掉 `\setmainfont[]{Source Sans Pro}`之后，正常的效果：
![image](https://user-images.githubusercontent.com/4145852/83811278-1a2ef880-a6ec-11ea-9049-5e0cfcb61176.png)

**Comment by sikouhjw** [comment]
用模板就不要改模板，如果要改，说明你可能需要的不是 ElegantBook
```tex
\documentclass{ctexart}
\usepackage{sourceserifpro}
\begin{document}
\begin{description}
\item[Linux]
Linux
\end{description}
\end{document}
```
还有，请分清什么叫无衬线，什么叫衬线，`\setmainfont[]{Source Sans Pro}` 完全没有起到作用，除非你修改 `description` 的定义

**Comment by sikouhjw** [comment]
注释
https://github.com/ElegantLaTeX/ElegantBook/blob/5d02e85f01096c8e1819c9d18c3bd2df388e3709/elegantbook.cls#L189
然后按你的代码即可，后果自负
