### ISSUE TITLE
希望增加一个“案例”的环境

### ISSUE THREAD

**Issue by muyubaobao** [ElegantLaTeX/ElegantBook#102]
您好，在写书的过程中，我经常会遇到需要引入一些实际案例，希望模板里能提供一个类似definition这样的环境，例如\begin{case}  \end{case}这样，可以将案例放在里面，这样可以与正文内容分开。

一个可能的问题是，商业案例一般较长，可能会超过一页，里面还会插图表，所以这里面的格式问题也许较为复杂。

非常感谢！

**Comment by sikouhjw** [comment]
> 一个可能的问题是，商业案例一般较长，可能会超过一页，里面还会插图表，所以这里面的格式问题也许较为复杂。

尽量就不要放盒子里了，浮动体用不了，表格也难弄，仿照 `example` 环境弄一个好了。
```tex
\documentclass[cn]{elegantbook}
\usepackage{zhlipsum}
\newcounter{casea}[chapter]
\setcounter{casea}{0}
\renewcommand{\thecasea}{\thechapter.\arabic{casea}}
\newenvironment{case}[1][]{
  \refstepcounter{casea}
  \par\noindent\textbf{\color{main}{案例} \thecasea #1 }\rmfamily}{
  \par\ignorespacesafterend}
\begin{document}
\begin{case}
  \zhlipsum[1-5]
  \begin{figure}
    \centering
    \includegraphics[]{example-image.pdf}
  \end{figure}
\end{case}
\end{document}
```
如果要修改「案例」的颜色，修改 `\color{main}` 的选项即可。如果不想让章节为案例的上级计数器，注释
```tex
\newcounter{casea}[chapter]
\renewcommand{\thecasea}{\thechapter.\arabic{casea}}
```
就好了

**Comment by muyubaobao** [comment]
> > 一个可能的问题是，商业案例一般较长，可能会超过一页，里面还会插图表，所以这里面的格式问题也许较为复杂。
> 
> 尽量就不要放盒子里了，浮动体用不了，表格也难弄，仿照 `example` 环境弄一个好了。
> 
> ```
> \documentclass[cn]{elegantbook}
> \usepackage{zhlipsum}
> \newcounter{casea}[chapter]
> \setcounter{casea}{0}
> \renewcommand{\thecasea}{\thechapter.\arabic{casea}}
> \newenvironment{case}[1][]{
>   \refstepcounter{casea}
>   \par\noindent\textbf{\color{main}{案例} \thecasea #1 }\rmfamily}{
>   \par\ignorespacesafterend}
> \begin{document}
> \begin{case}
>   \zhlipsum[1-5]
>   \begin{figure}
>     \centering
>     \includegraphics[]{example-image.pdf}
>   \end{figure}
> \end{case}
> \end{document}
> ```
> 
> 如果要修改「案例」的颜色，修改 `\color{main}` 的选项即可。如果不想让章节为案例的上级计数器，注释
> 
> ```
> \newcounter{casea}[chapter]
> \renewcommand{\thecasea}{\thechapter.\arabic{casea}}
> ```
> 
> 就好了

非常感谢您的帮助，已经实现相应的效果。此外，不知是否能将案例环境中的字体变化一下，或者字号变化一下，这样跟正文有区别，可以设置么？非常感谢！

**Comment by muyubaobao** [comment]
> > > 一个可能的问题是，商业案例一般较长，可能会超过一页，里面还会插图表，所以这里面的格式问题也许较为复杂。
> > 
> > 
> > 尽量就不要放盒子里了，浮动体用不了，表格也难弄，仿照 `example` 环境弄一个好了。
> > ```
> > \documentclass[cn]{elegantbook}
> > \usepackage{zhlipsum}
> > \newcounter{casea}[chapter]
> > \setcounter{casea}{0}
> > \renewcommand{\thecasea}{\thechapter.\arabic{casea}}
> > \newenvironment{case}[1][]{
> >   \refstepcounter{casea}
> >   \par\noindent\textbf{\color{main}{案例} \thecasea #1 }\rmfamily}{
> >   \par\ignorespacesafterend}
> > \begin{document}
> > \begin{case}
> >   \zhlipsum[1-5]
> >   \begin{figure}
> >     \centering
> >     \includegraphics[]{example-image.pdf}
> >   \end{figure}
> > \end{case}
> > \end{document}
> > ```
> > 
> > 
> > 如果要修改「案例」的颜色，修改 `\color{main}` 的选项即可。如果不想让章节为案例的上级计数器，注释
> > ```
> > \newcounter{casea}[chapter]
> > \renewcommand{\thecasea}{\thechapter.\arabic{casea}}
> > ```
> > 
> > 
> > 就好了
> 
> 非常感谢您的帮助，已经实现相应的效果。此外，不知是否能将案例环境中的字体变化一下，或者字号变化一下，这样跟正文有区别，可以设置么？非常感谢！

我把\rmfamily 改成\fangsong  \small了，目前已经解决的我的问题，不知道这么改会不会影响其他的，不过目前已经好了，再次感谢！
