### ISSUE TITLE
去掉version编译报错

### ISSUE THREAD

**Issue by over-shine** [ElegantLaTeX/ElegantBook#104]
```tex
\documentclass{elegantpaper}
\title{test}
\author{test}
\institute{test}
\version{0.09}

\makeatletter
\renewcommand\@maketitle{%
  \newpage
  \null
  \vskip 2em%
  \begin{center}%
  \let \footnote \thanks
    {\LARGE\bfseries \@title \par}%
    \vskip 1.5em%
    {\large
      \lineskip .5em%
      \begin{tabular}[t]{c}%
        \@author\\[1ex]
      \end{tabular}\par}
      \the\institute%
\vskip 0.5ex%
\ifx\@date\empty
\else
\vskip 0.1em%
 {\small\normalfont\citshape\updatetext\@date}%
\fi
  \end{center}%
  \par
}
\makeatother

\begin{document}
\maketitle
\end{document}
```
报错

{
	"resource": "/e:/课件/政治/paper/test.tex",
	"owner": "LaTeX",
	"severity": 8,
	"message": "Undefined control sequence.\n\\@maketitle ...0.1em{\\small \\normalfont \\citshape \n",
	"source": "LaTeX",
	"startLineNumber": 34,
	"startColumn": 1,
	"endLineNumber": 34,
	"endColumn": 65536
}
{
	"resource": "/e:/课件/政治/paper/paper.tex",
	"owner": "LaTeX",
	"severity": 4,
	"message": "Unknown slot number of character\n(microtype)\t`\\`A'\n(microtype)\tin font encoding `TU' in inheritance list\n(microtype)\t`microtype.cfg/376(protrusion)'.\n",
	"source": "LaTeX",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 65536
}
{
	"resource": "/e:/课件/政治/paper/test.tex",
	"owner": "LaTeX",
	"severity": 4,
	"message": "Unknown slot number of character\n(microtype)\t`\\~A'\n(microtype)\tin font encoding `TU' in inheritance list\n(microtype)\t`microtype.cfg/376(protrusion)'.\n",
	"source": "LaTeX",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 65536
}

**Comment by EthanDeng** [comment]
不属于 book 的 issue，请跳转 https://github.com/ElegantLaTeX/ElegantPaper/issues/39，请更新模板版本。
