### ISSUE TITLE
ElegantLaTeX 相关模板提问示例

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#105]
关于 ElegantLaTeX 模板的提问大体上分为三类：

1. 编译出错；
2. 功能实现；
3. 其他问题。

我之前一直犹豫要不要提问模板，最大的考虑就是，太麻烦了。但是无规矩不成方圆，长此以往，不方便交流，在 @sikouhjw 的强烈建议和帮助下，今后在 GitHub 上以及 QQ 群，请大家尽量按照下面的提问模板/示例来提供信息，谢谢！

_Originally posted by @sikouhjw in https://github.com/ElegantLaTeX/ElegantBook/issues/100#issuecomment-638282808_

**Comment by EthanDeng** [comment]
# 编译报错

我在 win10（mac/linux）上用 TeX Live 2020（Miktex）编译 ElegantBook 3.11（ElegantNote 2.30/ElegantPaper 0.09）版本时，出现报错，编译方式为 XeLaTeX（pdfLaTeX），这是我的注释掉无关代码后的 MWE：

```tex
\documentclass{elegantbook}
\begin{document}
  \latex
\end{document}
```
报错为
```tex
./1.tex:3: Undefined control sequence.
l.3   \latex
```
后缀为 `.log` 的文件附在这（从 `Attach files by dragging & dropping, selecting or pasting them.` 那上传文件）

`<文件.log>`

我还有图片/bib 文件，报错在图片/bib 文件这里，我将
- `.tex`
- `.bib`
- 图片

文件压缩成压缩文件，附在这

`<文件.rar/.zip>`

**Comment by EthanDeng** [comment]
# 功能请求/需求实现

我在使用 ElegantBook，我想改其中的一些设置：
- 给 `\cover` 和 `\logo` 设置缺省值

这是我想要的效果图
https://user-images.githubusercontent.com/49770925/72252368-1fef4900-363a-11ea-9267-ee716a1c2c58.png
我的代码实现是这样的：
```tex
……
```
具体参考https://github.com/ElegantLaTeX/ElegantBook/issues/74

**Comment by EthanDeng** [comment]
# 其他问题

我在使用 ElegantBook，我打算用它来写一本书，但我不知道怎么将正文分成多个子文件插入到主文件中，能教教我吗

_Originally posted by @sikouhjw in https://github.com/ElegantLaTeX/ElegantBook/issues/100#issuecomment-638282808_

**Comment by LingfeiYu** [comment]
使用\usepackage{pdflscape}宏包，使得文章某一单独页面横置后，页眉页脚仍显示于侧方（而不是页面正下方），请问该如何解决？

**Comment by BairuChen2019** [comment]
请问怎么让中文参考文献排在前面，英文排在后面呢？

**Comment by sikouhjw** [comment]
> 请问怎么让中文参考文献排在前面，英文排在后面呢？

单独问题去开新的 issue，还有请按照此 issue 的提示给 mwe
