### ISSUE TITLE
如何自定义章节标题样式

### ISSUE THREAD

**Issue by xq114** [ElegantLaTeX/ElegantBook#110]
例如把 section 样式改成 \S1 这种，用 ctex 文档类可以用 `\ctexsetup` 设置，用 elegantbook 类的时候 `\ctexsetup` 会报错（Error: The key 'ctex/chapter/name' is unknown and is being ignored.）。应该怎么处理这个问题呢？

**Comment by sikouhjw** [comment]
ElegantBook 不是用 `ctexheading` 设置章节的，用的是 `titlesec` 宏包，与 `ctexheading` 有冲突，所以
- 要么用 `titlesec` 设置
- 要么修改 `cls` 文件（不推荐）
- 要么自己写一个样式
