### ISSUE TITLE
I found no \citation commands

### ISSUE THREAD

**Issue by zapplelove** [ElegantLaTeX/ElegantBook#114]
```bash
This is BibTeX, Version 0.99d (TeX Live 2020)
The top-level auxiliary file: elegantbook-cn.aux
I found no \citation commands---while reading file elegantbook-cn.aux
I found no \bibdata command---while reading file elegantbook-cn.aux
I found no \bibstyle command---while reading file elegantbook-cn.aux
(There were 3 error messages)
```
根据使用说明，按照xelatex->bibtex->xelatex*2的方式编译，但第二步死活不好使，请作者查找一下问题。
ps. 我直接clone的，使用bash terminal编译

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/106
https://github.com/ElegantLaTeX/ElegantBook/issues/112

**Comment by sikouhjw** [comment]
用 `biber` 而不是 ``bibtex

**Comment by zapplelove** [comment]
https://elegantlatex.org/cn/elegantbook/compilationmethods/
请修正一下。

**Comment by sikouhjw** [comment]
> https://elegantlatex.org/cn/elegantbook/compilationmethods/
> 请修正一下。

没维护很久了，具体编译看 release 中的说明手册和 issue

**Comment by EthanDeng** [comment]
网站可能随着 4.x 发布而彻底关闭，以 GitHub/发行版里的手册为准。

**Comment by gavin-edward** [comment]
> ```shell
> This is BibTeX, Version 0.99d (TeX Live 2020)
> The top-level auxiliary file: elegantbook-cn.aux
> I found no \citation commands---while reading file elegantbook-cn.aux
> I found no \bibdata command---while reading file elegantbook-cn.aux
> I found no \bibstyle command---while reading file elegantbook-cn.aux
> (There were 3 error messages)
> ```
> 
> 根据使用说明，按照xelatex->bibtex->xelatex*2的方式编译，但第二步死活不好使，请作者查找一下问题。 ps. 我直接clone的，使用bash terminal编译

TeXstudio中默认编译器设置为 XeLaTeX, 默认文献工具设置为 Biber, 然后再编译就没问题了

**Comment by laseren** [comment]
The top-level auxiliary file: elegantbook-cn.aux
I found no \citation commands---while reading file elegantbook-cn.aux
I found no \bibdata command---while reading file elegantbook-cn.aux
I found no \bibstyle command---while reading file elegantbook-cn.aux
(There were 3 error messages)
Macos 编译后出现一样的消息
TeXstudio中默认编译器设置为 XeLaTeX, 默认文献工具设置为 bibtex8而不是bibtex， 然后再编译就没问题了

**Comment by Explorer-cc** [comment]
> ```
> The top-level auxiliary file: elegantbook-cn.aux
> I found no \citation commands---while reading file elegantbook-cn.aux 
> I found no \bibdata command---while reading file elegantbook-cn.aux 
> I found no \bibstyle command---while reading file elegantbook-cn.aux
>  (There were 3 error messages) 
> ```
> 
> Macos 编译后出现一样的消息 TeXstudio中默认编译器设置为 XeLaTeX, 默认文献工具设置为 bibtex8而不是bibtex， 然后再编译就没问题了

<img width="1152" height="849" alt="Image" src="https://github.com/user-attachments/assets/361a93bc-4c22-444b-af1c-9bbe8ccba409" />

上述文档指出：默认是`biber`后端，则自己不太应该设置使用`bibtex`来编译`elegantbook`文档类。总而言之，调用方式和实际编译的命令应该_统一_，则不会出现上述报错/警告。

BTW，应正确使用[代码块](https://docs.github.com/zh/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)。
