### ISSUE TITLE
! LaTeX Error: File `pgfornament.sty' not found.

### ISSUE THREAD

**Issue by AustinJia** [ElegantLaTeX/ElegantBook#117]
你好，
1. 我出现了这样的报错。
我在https://github.com/ElegantLaTeX/ElegantBook/issues/92
看到了解决方案，不过我没看懂如何解决。

我直接在overleaf 上编辑，就没有这样的报错，但是假如用MacTex 2020 compiler 的话，就会有这样的报错。

2. 还有，我想问一下如何wrapfig? 
我运用了"\usepackage{wrapfig}" 在elegantbook.cls，然后直接

\begin{wrapfigure}{r}{0.55\textwidth}
    \begin{center}
        \includegraphics[width=0.5\textwidth]{PrincetonU.png}
    \end{center}
\end{wrapfigure}

但是出现了这个问题
<img width="453" alt="Screen Shot 2020-08-19 at 12 00 14 PM" src="https://user-images.githubusercontent.com/13293943/90660616-29661280-e214-11ea-8105-ded7f1c0bcc1.png">

**Comment by sikouhjw** [comment]
> 你好，
> 
> 1. 我出现了这样的报错。
>    我在#92
>    看到了解决方案，不过我没看懂如何解决。
> 
> 我直接在overleaf 上编辑，就没有这样的报错，但是假如用MacTex 2020 compiler 的话，就会有这样的报错。

https://github.com/ElegantLaTeX/ElegantBook/issues/106

> 1. 还有，我想问一下如何wrapfig?
>    我运用了"\usepackage{wrapfig}" 在elegantbook.cls，然后直接
> 
> \begin{wrapfigure}{r}{0.55\textwidth}
> \begin{center}
> \includegraphics[width=0.5\textwidth]{PrincetonU.png}
> \end{center}
> \end{wrapfigure}
> 
> 但是出现了这个问题
> <img alt="Screen Shot 2020-08-19 at 12 00 14 PM" width="453" src="https://user-images.githubusercontent.com/13293943/90660616-29661280-e214-11ea-8105-ded7f1c0bcc1.png">

https://github.com/ElegantLaTeX/ElegantBook/issues/105

**Comment by EthanDeng** [comment]
在 overleaf 上没有问题的原因是 overleaf 用的不是 TeX Live 2020，而 pgfornament 包的作者在 TeX Live 2020 发布时，不小心把自己包标注为过时，所以导致没有打包到 TeX Live 2020。

所以解决办法有：
1. 使用 overleaf，不更改任何东西。
2. 使用 MacTeX 2020，但是把宏包更新到最新的版本；

第二种方法的处理实际上发生了两件事情：
1. ElegantBook 在 TeX Live 2020 发布时使用了 pgfornament 宏包，更新后并不会使用这个包，所以保证即便没有 pgfornament  包的时候仍然没问题。
2. 更新全部宏包时，会安装 pgfornament 宏包，所以宏包缺失问题也不存在了。

**Comment by EthanDeng** [comment]
如果要左文字，右边图片的，可以使用 minipage 环境，另外为了重现你的问题，请提供 MWE。
