### ISSUE TITLE
minipage下example缩进问题，我想让“例题2.22”跟“命题2.3一样不缩进。请问如何解决？谢谢

### ISSUE THREAD

**Issue by nbyfcb** [ElegantLaTeX/ElegantBook#118]
<img width="617" alt="截屏2020-09-01 下午2 36 11" src="https://user-images.githubusercontent.com/48893879/91812215-4ca4af00-ec63-11ea-95a1-5cfeac6ffc1c.png">
<img width="631" alt="截屏2020-09-01 下午2 36 19" src="https://user-images.githubusercontent.com/48893879/91812225-50d0cc80-ec63-11ea-930e-4a4dee5787e5.png">

**Comment by sikouhjw** [comment]
This is not MWE, please refer to https://github.com/ElegantLaTeX/ElegantBook/issues/105 and [https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that](https://tex.meta.stackexchange.com/questions/228/ive-just-been-asked-to-write-a-minimal-working-example-mwe-what-is-that) to provide MWE

**Comment by EthanDeng** [comment]
加上 `\noindent`。
