### ISSUE TITLE
中英文档使用的示例颜色不一致

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#12]
### 问题描述

在文档的第 2.3 节，中英文版本使用的示例颜色不一致

|      | Position A | Position B |
| ---- | ---------- | ---------- |
| cn   | main       | structure  |
| en   | main       | main       |

![image](https://user-images.githubusercontent.com/6376638/56828658-5d395e00-6894-11e9-8c24-eb6145819dc4.png)
![image](https://user-images.githubusercontent.com/6376638/56828685-6d513d80-6894-11e9-96ba-526fc1d3ca0f.png)

![image](https://user-images.githubusercontent.com/6376638/56827872-9244b100-6892-11e9-82a8-233de101d042.png)

### 源码位置

https://github.com/ElegantLaTeX/ElegantBook/blob/92c45095cf09c90af572bd234415cb089b2266e0/elegantbook-cn.tex#L75-L92
https://github.com/ElegantLaTeX/ElegantBook/blob/92c45095cf09c90af572bd234415cb089b2266e0/elegantbook-en.tex#L75-L93

### 讨论与建议

main 颜色
 - 问题：`cyan` 和 `green` 主题 main 的差异小，`blue` 主题的 main 是绿色的

structure 颜色
 - 问题：`gray` 主题的 structure 颜色是纯黑

目前，建议都改用 structure。长期来看，可能需要调整配色。确认如何修改后，我可以提供 pull request。

**Comment by EthanDeng** [comment]
嗯 那个中文表格是我上次改的（[commit](https://github.com/ElegantLaTeX/ElegantBook/commit/0171d1836f1911a51079537945c13893d84be726)），改完传到 github 之后发现文本里面也有，-_-||。我想着下次更新一起改呢。**正确的是 structure color**。因为原来是三色，3.07 版本多了 structure color，分布时文档部分当时没注意。改为 structure color 的话，那个 gray 还需要调整下，因为那个 structure 是黑色，不是灰色，这也是当时我改完之后的感觉，gray 不是 gray，是 black，后来忙 Overleaf 的事情，就先搁置了。

至于后面说到的主题相似（其实 green 、blue 和 cyan 都有点相似，只不过 green 为 3 色，而且看起来更旧，其他颜色更新），问题出在哪呢？现在 blue 和 cyan 颜色主题是有据可循的两套颜色，而那个 green 主题是原先我自己设置的颜色主题（在这次颜色更新之前，一直沿用的主题）。虽然我更喜欢现在的 blue 主题，但是为了保留原先的颜色主题（原先 3 色改为 4 色，structure 的颜色就来自于 main），所以这个主题看起来不是那么搭（与 cyan 和 blue）。

看到你的标题我就知道要说什么，本来想着下个版本 3.08 再重新调整下，比如默认的颜色主题不叫 green，叫个其他名字。cyan 和 blue 也有点相似（可能保留 blue，重新定制 cyan 颜色主题和 green）。我还得再想想，你也可以提供具体建议，比如提供颜色主题。

**Comment by muzimuzhi** [comment]
### 示例颜色

我想到一个新的思路
 - 新增颜色 `demo`，专门用于展示颜色主题，例如 `\textcolor{demo}{<name of color theme>}`。同时规定 `demo` 必须使用主题中既有的颜色。这样就避免了「示例色」和「颜色主题单词词义」不一致的问题，也把示例色的选取和整体配色问题分离了。

### 颜色命名
基于
 - 颜色名中应该统一带或不带 "color" 单词
 - 颜色名不带 "color" 也能通过命令的用法看出来它是颜色，不是普通文本，不易产生歧义

的考虑，我倾向于统一不带 "color"（`beamer` 也使用这种颜色命名方式），也即把 "structurecolor" 改成 "structure"。

具体是不是叫 "structure" 这个名字，要不要换一个，要不要使用 `\colorlet` 为颜色系统增加一层抽象，长期来看都是可讨论的。可能放在新 issue 里讨论。

#### 「增加一层抽象」的意思是
```latex
if (lang == "xx")
  \deinecolor{<base color>}{<color model>}{<spec list>}
fi
\colorlet{<color in use>}{<base color>}
\fancyhead{\color{<color in use>}...}

<base color>   ::= "main" | "second" | ...
<color in use> ::= "header and footer" | "section title" | ...
```
这样能提高代码的可维护性（比起使用 `\fancyhead{\color{second}}`），一定程度上减少错误（例如修改 `\fancyhead/foot` 里使用的颜色时改了三处漏了第四处）。

### 配色设计
具体配色方面，我能力不足。

**Comment by EthanDeng** [comment]
多一层抽象那个想法挺好的，我资瓷。

**Comment by EthanDeng** [comment]
另外对于灰色，我想改为四个颜色都改为 RGB=100,100,100。

**Comment by muzimuzhi** [comment]
对新增颜色 `demo` 的意见呢？

**Comment by muzimuzhi** [comment]
看到已经统一使用 "structure" 了

**Comment by EthanDeng** [comment]
> 对
> 
> 1. 新增颜色 `demo`
> 2. 颜色名统一不带 "color" 单词
> 
> 的意见呢？

我不知道你的 demo 颜色这个要怎么实现。颜色名称的话，就去掉 color 好了，名字维持不变：structure，main，second，third。（或者保留 color，改名为 structurecolor，theoremcolor，definitioncolor，propositioncolor，不过这个名字有点太长了）

**Comment by muzimuzhi** [comment]
> 我不知道你的 demo 颜色这个要怎么实现。

类似下方这样，在定义色彩主题时，let 到其他颜色。

```latex
\ifdefstring{\ELEGANT@color}{green}{
  ...
  \colorlet{demo}{main}
}{}
\ifdefstring{\ELEGANT@color}{cyan}{
  ...
  \colorlet{demo}{structure}
}{}
```

**Comment by muzimuzhi** [comment]
我之前考虑多了。看起来，现在使用 `structure` 作为各颜色主题的示例色即可。

如果仍然考虑增加 `\colorlet{demo}{structure}`，则唯一的好处是，未来「颜色 `structure`」和「颜色主题单词词义」不一致时，可以通过 `demo` 的抽象来保持代码改动最小。

**Comment by EthanDeng** [comment]
对的，我把灰色主题改完之后，全部都应该是 structure 颜色作为示例颜色。之前 gray 应该使用 main，其他是 structure。

**Comment by muzimuzhi** [comment]
目前已经增加了 `demo` 色（见 https://github.com/ElegantLaTeX/ElegantBook/commit/bd32b964bd37fef4ac6a9b0f42c7758a0842cb79 ），等 #15 完成，就可以把它作为新增颜色抽象层的一部分。
