### ISSUE TITLE
How to remove the dot in the cross-reference to an item from enumerate?

### ISSUE THREAD

**Issue by sierxue** [ElegantLaTeX/ElegantBook#121]
When I refer to an item in a enumerate list, there is an annoying dot in the sentence. Please see more details in my MWE.

I find some discussions about this but still couldn't solve it. See, for example, [https://tex.stackexchange.com/q/288407/104838](https://tex.stackexchange.com/q/288407/104838) and [https://tex.stackexchange.com/q/234499/104838](https://tex.stackexchange.com/q/234499/104838)

MWE with Version 2020/08/04 v4.0.5 ElegantBook document class:

```
\documentclass[en]{elegantbook}
\begin{document}
\begin{problemset}\label{set:1}
    \item\label{itm:1_1}
        Problem 1
    \item Problem 2
\end{problemset}
Problem~\ref{itm:1_1} is quite easy!
\end{document}
```
![image](https://user-images.githubusercontent.com/19348230/93020012-60f68d80-f60d-11ea-83f9-9bc950b30c7e.png)

**Comment by sikouhjw** [comment]
You need to redefine the problemSet environment, which the source code section references to
https://github.com/ElegantLaTeX/ElegantBook/blob/78fe2c7dafcede6641e3ef06e45803afc0110eeb/elegantbook.cls#L715-L721
You need to use the ability to set `label` and `ref` separately in the `enumitem` package
```tex
\documentclass[en]{elegantbook}
\renewenvironment{problemset}[1][\chaptername~\problemsetname]{
  \begin{center}
    \phantomsection\addcontentsline{toc}{section}{\texorpdfstring{\chaptername\;\problemsetname}{\problemsetname}}
    \textcolor{structurecolor}{\Large\bfseries\adftripleflourishleft~#1~\adftripleflourishright}
  \end{center}
  \begin{enumerate}[label=\color{structurecolor}\arabic*., ref=\arabic*]}{
  \end{enumerate}}
\begin{document}
\begin{problemset}\label{set:1}
    \item\label{itm:1_1}
        Problem 1
    \item Problem 2
\end{problemset}
Problem~\ref{itm:1_1} is quite easy!
\end{document}
```

**Comment by sierxue** [comment]
Thanks for your help!

It works in the pdf output! But I receive the following error message:
```
mwe-cross-reference-item.tex|12 error| Undefined control sequence. \problemsetname 
mwe-cross-reference-item.tex|12 error| Undefined control sequence. \chaptername \;\problemsetname 
mwe-cross-reference-item.tex|12 error| Undefined control sequence. ...left ~\chaptername ~\problemsetname
```

**Comment by sikouhjw** [comment]
I made a mistake. Your version is `v4.x`, and the code I gave is `v3.11`, and the code corresponding to `v4.x` is referred to
https://github.com/ElegantLaTeX/ElegantBook/blob/f123c6a83bef9bfb4c9f1c4f0af5a2c557eb7a9c/elegantbook.cls#L829-L837
modified into
```tex
\documentclass[en]{elegantbook}
 \renewenvironment{problemset}[1][\chaptername~\chapterextra\exercisename]{ 
   \begin{center} 
     \phantomsection\addcontentsline{toc}{section}{\texorpdfstring{\chaptername\;\exercisename}{\exercisename}} 
     % \markboth{#1}{\rightmark} 
     \markright{#1} 
     \textcolor{structurecolor}{\Large\bfseries\adftripleflourishleft~#1~\adftripleflourishright} 
   \end{center} 
   \begin{enumerate}[label=\color{structurecolor}\arabic*., ref=\arabic*]}{ 
   \end{enumerate}}
\begin{document}
\begin{problemset}\label{set:1}
    \item\label{itm:1_1}
        Problem 1
    \item Problem 2
\end{problemset}
Problem~\ref{itm:1_1} is quite easy!
\end{document}
```
PS: It is not recommended to use the `v4.x` version because it is still in development

**Comment by sierxue** [comment]
This works like a charm! Your solution is greatly appreciated!
