### ISSUE TITLE
强烈建议删除vectorian88.pgf设置，避免编译错误 Argument of \c has an extra }.

### ISSUE THREAD

**Issue by zhenjieliang** [ElegantLaTeX/ElegantBook#127]
虽然在elegantbook.cls中加上vectorian88.pgf可以让页脚和目录有一个很好看的标记，但是这是以编译速度、编译出来的pdf以及经常可能发生的编译错误为代价的。

具体而言，该cls中有两处和vectorian88.pgf有关，设置的代码如下

```tex
\titleformat{\chapter}[\style]{\bfseries}
{\filcenter\LARGE\enspace\bfseries{\color{structurecolor}\IfAppendix{\appendixname}{\chaptername}\enspace}}{1pt}{\bfseries\color{structurecolor}\LARGE\filcenter}[\ifdefstring{\ELEGANT@base}{hide}{}{\filcenter\base{structurecolor}{88}}]

\fancyfoot[c]{\base{structurecolor}{88}} 
```

去除vectorian88.pgf之后该两处的代码分别是

```tex
\titleformat{\chapter}[\style]{\bfseries}
{\filcenter\LARGE\enspace\bfseries{\color{structurecolor}\IfAppendix{\appendixname}{\chaptername}\enspace}}{1pt}{\bfseries\color{structurecolor}\LARGE\filcenter}%[\ifdefstring{\ELEGANT@base}{hide}{}{\filcenter\base{structurecolor}{88}}]

%\fancyfoot[c]{\base{structurecolor}{88}} 
```

按照这样修改之后，编译速度大大提高，编译出的pdf的大小也下降了。另外，还可以避免莫名
其妙的错误，例如：

```tex
Argument of \c has an extra }.
```

如果你曾经被这个编译报错折磨过，你就明白这个vectorian88.pgf是多么的可恶。

**Comment by sikouhjw** [comment]
你用的不是最新版，不与时俱进，报错是必然的

**Comment by zhenjieliang** [comment]
> 你用的不是最新版，不与时俱进，报错是必然的

最新版的cls确实没有这些设置了。。。
我之所以不用最新版，是因为我魔改加了很多设置。你说的有道理，应该看看最新版本。

不过我相信有些同学也和我一样对这个模板进行了很多修改，他们应该也和我一样遇到过同样的问题。所以这个issue还是放着吧

**Comment by EthanDeng** [comment]
> 虽然在elegantbook.cls中加上vectorian88.pgf可以让页脚和目录有一个很好看的标记，但是这是以编译速度、编译出来的pdf以及经常可能发生的编译错误为代价的。

我也是基于这个考虑，决定 remove 掉的。
