### ISSUE TITLE
可否加入“问题”和“猜想”两项？

### ISSUE THREAD

**Issue by zahlkorper** [ElegantLaTeX/ElegantBook#128]
可否加入“问题”和“猜想”两项？

**Comment by sikouhjw** [comment]
你可以自己仿照着 `cls` 文件，在导言区添加

**Comment by zahlkorper** [comment]
> 你可以自己仿照着 `cls` 文件，在导言区添加

谢谢，我在cls中添加了，不过更新到新版本还要重新添加一遍，原来导言区也可以添加，才知道。

**Comment by EthanDeng** [comment]
后续考虑 #93
