### ISSUE TITLE
LaTeX Error: Command `\Bbbk' already defined.

### ISSUE THREAD

**Issue by liupeiID** [ElegantLaTeX/ElegantBook#131]
Tex version: texlive2020,
OS: macos 10.11
elegant version: 3.07
text editor: vim /texworks

mwe
```tex
\documentclass[cn,11pt,fancy]{elegantbook} 
\usepackage{subfiles}
\usepackage{ulem}
\usepackage{float}
\begin{document}           
\input{chapters/title}   		% 封皮信息 %%%%%%%%  
\maketitle               		% 制作封面 %%%%%%%%  
% ---------------------------------------------------------
\mainmatter
\hypersetup{pageanchor=true}
\tableofcontents           		% 生成目录 
\subfile{chapters/00preface}            % 00 序言(记录内容)
% ---------------------------------------------------------
% ---------------------------------------------------------
\subfile{chapters/01read}%             	% 01 文献阅读  
\subfile{chapters/02exp}%	        % 02 实验记录 
\subfile{chapters/03code}%	        % 03 编程(matlab,python,cpp)       
\subfile{chapters/04linux}%            	% 04 linux 相关  
\subfile{chapters/05cv}%            	% 05 cv_professional    
\subfile{chapters/06stu}%              	% 06 教学(学生)记录 
\subfile{chapters/07grant}%           	% 07 科研项目   
\subfile{chapters/2020}      		% 08 note
% ---------------------------------------------------------
\bibliography{reference}                % 参考文献
% ---------------------------------------------------------
\end{document}
```
文档在windows和ubuntu下编译运行正常，在MACOS下出现如上问题。

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/106

**Comment by liupeiID** [comment]
> #106
非常感谢，按照步骤，原始模版编译成功！

**Comment by liupeiID** [comment]
(/usr/local/texlive/2020/texmf-dist/tex/generic/gettitlestring/gettitlestring.s
ty)) (./elegantbook.out) (./elegantbook.out)

Package hyperref Warning: Rerun to get /PageLabels entry.

*geometry* driver: auto-detecting
*geometry* detected driver: xetex
ABD: EverySelectfont initializing macros
(/usr/local/texlive/2020/texmf-dist/tex/latex/footmisc/footmisc.sty)
(./chapters/title.tex)
(/usr/local/texlive/2020/texmf-dist/tex/latex/jknapltx/ursfs.fd)
(/usr/local/texlive/2020/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2020/texmf-dist/tex/latex/amsfonts/umsb.fd)

Package fontspec Warning: Font "Kaiti SC" does not contain requested Script
(fontspec)                "CJK".

[1]

Package hyperref Warning: old toc file detected, not used; run LaTeX again.

(./chapters/00preface.tex
! Improper alphabetic constant.
<to be read again> 
                   \__xeCJK_ambiguous_char:n 
l.2 \begin{document}
                    
?

**Comment by liupeiID** [comment]
目前单独编译每个subfile都能成功，编译如上主文件出现问题
[1] (./chapters/01read.tex
! Improper alphabetic constant.
<to be read again> 
                   \__xeCJK_ambiguous_char:n 
l.3 \begin{document}
                    
?

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/forum/blob/master/.github/ISSUE_TEMPLATE/question.md

**Comment by OsbertWang** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/72 解决方案参考它

**Comment by EthanDeng** [comment]
#132
