### ISSUE TITLE
Improper alphabetic constant.

### ISSUE THREAD

**Issue by liupeiID** [ElegantLaTeX/ElegantBook#132]
OS:  macos 10.11
Tex: texlive2020

MWE:
elegantbook.tex 
```tex
\documentclass[cn,11pt,fancy]{elegantbook} 
\usepackage{subfiles}
\begin{document}           
\maketitle               		
\mainmatter
\hypersetup{pageanchor=true}
\tableofcontents           		       
\subfile{chapters/01read}%             	
\bibliography{reference}                
\end{document}
```

mac:MWE u$ cat chapters/01read.tex 
```tex
\documentclass[../elegantbook]{subfiles}

\begin{document}
\chapter{文献阅读}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{前言}
\href{http://www.fenqubiao.com/}{JCR分区查询}，JCR分区（账号,密码 ）

\end{document}
```
我还尝试了：在chapter文件夹下单独编译01read没有错误提示，但是在主文件夹下编译 elegantbook是会出现这个错误。

**Comment by EthanDeng** [comment]
你把 elegantbook 换成其他文类向确认下，是模板问题还是你的用法问题。

另外，`\hypersetup{pageanchor=true}` 应该删除。

**Comment by liupeiID** [comment]
> 你把 elegantbook 换成其他文类确认下，是模板问题还是你的用法问题。
> 
> 另外，`\hypersetup{pageanchor=true}` 应该删除。

谢谢尝试了删除hypersetup语句和该用其他类，结果正常。mwe如下：
mac:MWE u$ cat elegantbook.tex 
\documentclass[cn,11pt,fancy]{article} 
\usepackage{subfiles}
\usepackage{hyperref}
\begin{document}                          		
\tableofcontents           		       
\subfile{chapters/01read}%             	
\bibliography{reference}                
\end{document}
mac:MWE u$ cat chapters/01read.tex 
\documentclass[../elegantbook]{subfiles}

\begin{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\section{前言}
\href{http://www.fenqubiao.com/}{JCR分区查询}，JCR分区（账号,密码  ）

\end{document}

**Comment by EthanDeng** [comment]
为觉得很奇怪啊，为啥正常阿？cn fancy 都不是 article 选项，而且，后面文件有中文，你没有任何报错信息？

**Comment by liupeiID** [comment]
> 我觉得很奇怪啊，为啥正常阿？cn fancy 都不是 article 选项，而且，后面文件有中文，你没有任何报错信息？

mac:MWE u$ xelatex elegantbook.tex 
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./elegantbook.tex
LaTeX2e <2020-10-01> patch level 2
L3 programming layer <2020-10-27> xparse <2020-03-03>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size11.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/subfiles/subfiles.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/import/import.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/pdfescape/pdfescape.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hycolor/hycolor.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/auxhook/auxhook.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/kvoptions/kvoptions.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/intcalc/intcalc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/etexcmds/etexcmds.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/url/url.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/bitset/bitset.sty
(/usr/local/texlive/2020/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/atbegshi-ltx.sty))
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/hxetex.def
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/puenc.def)
(/usr/local/texlive/2020/texmf-dist/tex/generic/stringenc/stringenc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/rerunfilecheck/rerunfilecheck.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/atveryend-ltx.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/uniquecounter/uniquecounter.sty
))) (/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
)

LaTeX Warning: Unused global option(s):
    [cn,fancy].

(./elegantbook.aux)
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd)
(/usr/local/texlive/2020/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/refcount/refcount.sty)
(/usr/local/texlive/2020/texmf-dist/tex/generic/gettitlestring/gettitlestring.s
ty)) (./elegantbook.out) (./elegantbook.out) (./elegantbook.toc)
(./chapters/01read.tex
(/usr/local/texlive/2020/texmf-dist/tex/generic/stringenc/se-ascii-print.def))
No file elegantbook.bbl.
[1] (./elegantbook.aux) )
(see the transcript file for additional information)
Output written on elegantbook.pdf (1 page).
Transcript written on elegantbook.log.
mac:MWE u$ 

有一个小小的提示说没有使用 cn fancy，然后正常生成文档

**Comment by EthanDeng** [comment]
经过验证，我发现这个并不是模板的问题，用 ctexbook 文类仍然有问题。

**文件**：`elegantbook.tex`

```tex
\documentclass[11pt]{ctexbook}

\usepackage{subfiles}
\usepackage{hyperref}

\begin{document}      

\tableofcontents
\subfile{chapters/01read}
\bibliography{reference}

\end{document}
```

**文件**：`01read.tex`
```tex
\documentclass[../elegantbook]{subfiles}

\begin{document}
\chapter{This is the first chapter}
\section{Test}
\href{http://www.fenqubiao.com/}{JCR分区查询}

\end{document}
```

**Comment by EthanDeng** [comment]
报错信息链接到 xeCJK 相关信息，初步推测，在 subfiles 里面需要设置字体。

**Comment by EthanDeng** [comment]
等后续我用原来的电脑测试，确认一下。

**Comment by sikouhjw** [comment]
升级全部宏包后，问题解决

**Comment by EthanDeng** [comment]
经过测试，全部宏包升级之后确实没有问题了。

**文件**：`elegantbook.tex`

```tex
\documentclass[cn]{elegantbook}

\usepackage{subfiles}
\usepackage{hyperref}

\begin{document}      

\tableofcontents

\subfile{chapters/01read}
\bibliography{reference}

\end{document}
```

**文件**：`01read.tex`
```tex
\documentclass[../elegantbook]{subfiles}

\begin{document}

\chapter{This is the first chapter}
\section{Test}

\href{http://www.fenqubiao.com/}{JCR 分区查询} 


\end{document}
```

[elegantbook.pdf](https://github.com/ElegantLaTeX/ElegantBook/files/5525071/elegantbook.pdf)

**Comment by EthanDeng** [comment]
如何更新宏包？使用 windows 的 cmd 或者 Ubuntu/Mac 的 terminal 运行 `tlmgr update --all`，管理员权限自己加 `sudo`。

**Comment by liupeiID** [comment]
> 如何更新宏包？使用 windows 的 cmd 或者 Ubuntu/Mac 的 terminal 运行 `tlmgr update --all`，管理员权限自己加 `sudo`。

好的，谢谢！确实解决问题！
