### ISSUE TITLE
关于章节标题格式

### ISSUE THREAD

**Issue by HenryJi529** [ElegantLaTeX/ElegantBook#135]
<img width="264" alt="Screenshot 2020-11-25 at 14 41 10" src="https://user-images.githubusercontent.com/41288155/100192101-46556480-2f2c-11eb-8d30-d304523f2eab.png">

<img width="321" alt="Screenshot 2020-11-25 at 14 41 52" src="https://user-images.githubusercontent.com/41288155/100192158-5cfbbb80-2f2c-11eb-898b-bafe31a3daaf.png">

不知道有没有办法实现这种格式： 
      第一章
   【大标题】
   【小标题】

或者：
   第一章
  【标题】

**Comment by sikouhjw** [comment]
看需求是否足够普遍，普遍就定制

详细描述需求，你描述的不够详细
