### ISSUE TITLE
小白入门，发现编译报错，无法生成书籍

### ISSUE THREAD

**Issue by HarrisonLiang123** [ElegantLaTeX/ElegantBook#139]
## 检查

 [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装
  - [x] Tex Studio

## 描述问题

正在学习计量经济学，想把自己的notes编成一本书，我使用elegantbook 3.11,发现之前几次编译都很正常，但是当我想输入theorm后，编译发现错误，随后删除了theorm，恢复到之前的情况，但是还是发生了如图所示的编译错误。

## 最小工作示例（MWE）
###因为我也不知道错误在哪里，所以就先把\begin{document}到\end{document}都截过来了，sorry.

```latex
\begin{theorem}{多元回归模型的假定}{mul_sum}
(1)一般多元回归模型的关键假定，可以用条件期望表示
\begin{equation}
	E(u|x_1,x_2,...,x_k)=0
\end{equation}
\end{theorem}
```

（用 pdfLaTeX 编译后）输出

```latex
开始 : pdflatex.exe -synctex=1 -interaction=nonstopmode "Ecometric Note".tex

name = unisong, rootname = unisong, pointsize = mktexmf: empty or non-existent rootfile!

kpathsea: Running mktexmf unisong.mf The command name is F:\texlive\2020\bin\win32\mktexmf Cannot find unisong.mf.

kpathsea: Running mktextfm unisong The command name is F:\texlive\2020\bin\win32\mktextfm kpathsea: Appending font creation commands to missfont.log.

出现错误
```
![QQ截图20210108170440](https://user-images.githubusercontent.com/63527319/103999798-54a7c900-51d8-11eb-8379-2433d3b468cf.png)

##现在问题已经得到解决，换用了XeLatex编辑器之后就正常了，但是我还是有点疑惑，为什么之前几次没换编辑器也能正常编译呢？

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/105
学会提问才能解决问题

**Comment by HarrisonLiang123** [comment]
> #105
> 学会提问才能解决问题

已经修改问题了，问题也得到了解决。

**Comment by EthanDeng** [comment]
文件名不要空格，尽量用英文，中文文件用 XeLaTeX 编译。

**Comment by HarrisonLiang123** [comment]
> 文件名不要空格，尽量用英文，中文文件用 XeLaTeX 编译。

谢谢您的回复
