### ISSUE TITLE
颜色主题讨论与征集

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#14]
欢迎大家提供颜色主题，基本原则：色调和谐，风格一致，适合屏幕阅读！

本 issue 长期有效。

**Comment by bai-yi-qing-xiang** [comment]
配色一：
\definecolor{structurecolor}{RGB}{41,183,203}  %蔚蓝
\definecolor{main}{RGB}{85,187,138}  %麦苗绿
\definecolor{second}{RGB}{251,182,18}  %鸡蛋黄
\definecolor{third}{RGB}{236,138,164}  %报春红

配色二：
\definecolor{structurecolor}{RGB}{240,124,130}  %香叶红
\definecolor{main}{RGB}{87,195,194}  %石绿
\definecolor{second}{RGB}{240,148,93} %海螺橙
\definecolor{third}{RGB}{251,218,65} %油菜花黄
