### ISSUE TITLE
图片有时会单独占据一页，以及图片在某一节末尾时，图片与下一节标题之间的间隔过大。

### ISSUE THREAD

**Issue by cxf208** [ElegantLaTeX/ElegantBook#140]
在使用模版时发现，当图片在某一章节的末尾时，如果图片后方再无文字描述，则生成的pdf文件中，图片与下一节标题之间的间隔会很大，不协调。
同时，有时图片会单独占据某一页，这个问题主要出现在图片较大时，请问有无解决的方法，谢谢！

**Comment by sikouhjw** [comment]
https://liam.page/2017/03/11/floats-in-LaTeX-basic/

**Comment by cxf208** [comment]
谢谢，很有帮助！
