### ISSUE TITLE
类型三：其它问题（字体bug？）

### ISSUE THREAD

**Issue by Edogawa-Konan** [ElegantLaTeX/ElegantBook#141]
当在introduction环境下编写仓库时，会出现“仑库”。测试环境是overleaf，textlive2019 [2020均有这个问题。xelatex编译中文。
![bug](https://user-images.githubusercontent.com/22148800/105701023-9ab39b00-5f01-11eb-84bb-ffa800939979.png)
如图

**Comment by sikouhjw** [comment]
MWE
```tex
\documentclass[fontset=fandol]{ctexart}
\begin{document}
  \kaishu 仓库
\end{document}
```
跟 ElegantBook 没什么关系，是字体问题。

Overleaf 调用的字体是 `fontset=fandol`，在 Overleaf 上只需要调用 `fontset=ubuntu` 即可。
