### ISSUE TITLE
ElegantBook字体替换为Baskerville之后，英文字体无法加粗

### ISSUE THREAD

**Issue by pingxi** [ElegantLaTeX/ElegantBook#143]
我在现有模板中加了下面的命令，但用{\bf China}没法把英文单词加粗。大佬们有啥解决方案吗？谢谢！
```tex
\usepackage{fontspec}
\setmainfont[Mapping=tex-text]{Baskerville}
\usepackage[defaultmathsizes,italic]{mathastext}
\usepackage{unicode-math}
```

**Comment by sikouhjw** [comment]
我没有这个字体，无法复现。

尝试手动指定粗体？

**Comment by pingxi** [comment]
我把Baskerville换成了Times，也会遇到同样的问题。会不会是其他地方强制英文字体使用某种样式了？比如{\bf Newton}显示出来不是加粗的。


PS：如果手动指定粗体，怎么实现啊？
谢谢！

\usepackage{fontspec}
\setmainfont[Mapping=tex-text]{Times}
\usepackage[defaultmathsizes,italic]{mathastext}
\usepackage{unicode-math}

**Comment by sikouhjw** [comment]
MWE：
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{times.ttf}
\begin{document}
  test \textbf{test}
\end{document}
```
有 warning：
```tex
LaTeX Font Warning: Font shape `TU/times.ttf(0)/b/n' undefined
(Font)              using `TU/times.ttf(0)/m/n' instead on input line 234.
```
warning 的意思自己去看 https://wenda.latexstudio.net/q-1380.html

解决方案：用一个自带粗体的西文字体。字体设置参考 https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/

**Comment by pingxi** [comment]
谢谢
