### ISSUE TITLE
请问一下在mac系统下使用应该如何修改设置

### ISSUE THREAD

**Issue by lizhu1126** [ElegantLaTeX/ElegantBook#144]
正在使用elegantBook，在windows下可以正常使用，但是在mac下就会报错，应该是字体的问题。想请问一下mac下如何设置？

**Comment by lizhu1126** [comment]
非常感谢

**Comment by sikouhjw** [comment]
报错是什么？

**Comment by lizhu1126** [comment]
> 报错是什么？

Undefined control sequence.
...�荐使用方正字体。方正的{\songti

报错一大堆，和字体相关的类似这样的。
不好意思，以前只是在英文环境下写过文章，对一些中文的设置什么的，有点无从入手，望指教，非常感谢

**Comment by sikouhjw** [comment]
> 
> 
> > 报错是什么？
> 
> Undefined control sequence.
> ...�荐使用方正字体。方正的{\songti
> 
> 报错一大堆，和字体相关的类似这样的。
> 不好意思，以前只是在英文环境下写过文章，对一些中文的设置什么的，有点无从入手，望指教，非常感谢

```tex
\documentclass[cn,fontset=macnew]{elegantbook}
\begin{document}
  测试
\end{document}
```
编译报什么？

**Comment by lizhu1126** [comment]
> > > 报错是什么？
> > 
> > 
> > Undefined control sequence.
> > ...�荐使用方正字体。方正的{\songti
> > 报错一大堆，和字体相关的类似这样的。
> > 不好意思，以前只是在英文环境下写过文章，对一些中文的设置什么的，有点无从入手，望指教，非常感谢
> 
> ```
> \documentclass[cn,fontset=macnew]{elegantbook}
> \begin{document}
>   测试
> \end{document}
> ```
> 
> 编译报什么？

编译报

Critical Package ctex: CTeX fontset `mac' is unavailable in current
(ctex)	mode.

**Comment by sikouhjw** [comment]
> 
> 
> > > > 报错是什么？
> > > 
> > > 
> > > Undefined control sequence.
> > > ...�荐使用方正字体。方正的{\songti
> > > 报错一大堆，和字体相关的类似这样的。
> > > 不好意思，以前只是在英文环境下写过文章，对一些中文的设置什么的，有点无从入手，望指教，非常感谢
> > 
> > 
> > ```
> > \documentclass[cn,fontset=macnew]{elegantbook}
> > \begin{document}
> >   测试
> > \end{document}
> > ```
> > 
> > 
> > 编译报什么？
> 
> 编译报
> 
> Critical Package ctex: CTeX fontset `mac' is unavailable in current
> (ctex) mode.

提供 log 文件

**Comment by lizhu1126** [comment]
> > > > > 报错是什么？
> > > > 
> > > > 
> > > > Undefined control sequence.
> > > > ...�荐使用方正字体。方正的{\songti
> > > > 报错一大堆，和字体相关的类似这样的。
> > > > 不好意思，以前只是在英文环境下写过文章，对一些中文的设置什么的，有点无从入手，望指教，非常感谢
> > > 
> > > 
> > > ```
> > > \documentclass[cn,fontset=macnew]{elegantbook}
> > > \begin{document}
> > >   测试
> > > \end{document}
> > > ```
> > > 
> > > 
> > > 编译报什么？
> > 
> > 
> > 编译报
> > Critical Package ctex: CTeX fontset `mac' is unavailable in current
> > (ctex) mode.
> 
> 提供 log 文件

好的

[main.log](https://github.com/ElegantLaTeX/ElegantBook/files/5980617/main.log)

**Comment by sikouhjw** [comment]
升级全部宏包，用 `xelatex`，应该就没问题了

**Comment by lizhu1126** [comment]
> 升级全部宏包，用 `xelatex`，应该就没问题了

好的，非常感谢，我试一下
