### ISSUE TITLE
使用menukeys包时用\keys不会自动换行

### ISSUE THREAD

**Issue by redleafnew** [ElegantLaTeX/ElegantBook#145]
使用menukeys包时用menu不会自动换行，而用ctex则没有问题。（题目写错了，不好意思）
请问是什么问题，谢谢。
MWE：
```
%\documentclass[cn,11pt,chinese]{elegantbook}
\documentclass {ctexart}
 \usepackage[os=win]{menukeys} %使用目录、菜单、按键
    \renewmenumacro{\menu}[-]{menus} %将默认的>改为-
\begin{document}
选中需要删除的条目当然可以（可以选择多条），点击
 \menu{Tools-Manage Attachments-Convert Linked Files to Stored Files...}
\end{document}
```

**Comment by sikouhjw** [comment]
页边距不同，在 `ctexart` 中依旧会溢出。

**Comment by redleafnew** [comment]
谢谢。那有什么解决办法吗？

**Comment by sikouhjw** [comment]
`texdoc menukeys`, 4.2.1 Predefined styles
```tex
\documentclass[cn]{elegantbook}
\usepackage[os=win]{menukeys}
\renewmenumacro{\menu}[-]{hyphenatepaths}
\begin{document}
选中需要删除的条目当然可以（可以选择多条），点击
 \menu{Tools-Manage Attachments-Convert Linked Files to Stored Files...}
\end{document}
```

**Comment by redleafnew** [comment]
谢谢。我注意到这个了。但两个不一样。重新定义后变成了路径(\path)了，而不是菜单(\menu）了。

**Comment by sikouhjw** [comment]
> 
> 
> 谢谢。我注意到这个了。但两个不一样。重新定义后变成了路径(\path)了，而不是菜单(\menu）了。

为什么不能是菜单？

**Comment by redleafnew** [comment]
/path的效果
<img width="560" alt="path" src="https://user-images.githubusercontent.com/22135631/108501647-91dd9b80-72ec-11eb-9dbe-20a38b9bc4d8.png">
/menu需要的效果：
<img width="589" alt="menu" src="https://user-images.githubusercontent.com/22135631/108501695-a5890200-72ec-11eb-91a0-f2cf4eda5908.png">

**Comment by sikouhjw** [comment]
所以第一种只能是 `\path`？

**Comment by redleafnew** [comment]
是的，第一种实际上是针对path换行的，我想改为{hyphenatemens}，结果没有这个命令。
