### ISSUE TITLE
twoside 模式下页眉方向问题

### ISSUE THREAD

**Issue by Harry-Chen** [ElegantLaTeX/ElegantBook#147]
目前在双面模式下的实现为：

https://github.com/ElegantLaTeX/ElegantBook/blob/78fe2c7dafcede6641e3ef06e45803afc0110eeb/elegantbook.cls#L741-L743

如果用于印刷，页面应该在外侧（即奇数页的右边，偶数页的左边），目前的输出是不正确的。对于一个将封面从右侧开始显示的 PDF 阅读器（如 macOS 的 `Preview.app`），同样会看到不正确的效果。

**Comment by EthanDeng** [comment]
已经改为：
```tex
\if@twoside
  \fancyhead[RE]{\color{structurecolor}\cnormal\rightmark}
  \fancyhead[LO]{\color{structurecolor}\cnormal\leftmark}
```

**Comment by EthanDeng** [comment]
https://github.com/ElegantLaTeX/ElegantBook/blob/71c0f9e1a59688a30133dcc9246d3f3e1a9204eb/elegantbook.cls#L891-L893
