### ISSUE TITLE
我的手册地址更新了

### ISSUE THREAD

**Issue by OsbertWang** [ElegantLaTeX/ElegantBook#151]
https://github.com/ElegantLaTeX/ElegantBook/blob/bf40203c9f38ade2f6bf93e039a436255a8bc043/elegantbook-cn.tex#L127

现在我手册地址是 [这里](https://github.com/OsbertWang/install-latex-guide-zh-cn/releases/)

**Comment by syvshc** [comment]
> https://github.com/ElegantLaTeX/ElegantBook/blob/bf40203c9f38ade2f6bf93e039a436255a8bc043/elegantbook-cn.tex#L127
> 
> 现在我手册地址是 [这里](https://github.com/OsbertWang/install-latex-guide-zh-cn/releases/)

话说原地址也能定向到新的 repo……，
