### ISSUE TITLE
定义环境中的脚注问题

### ISSUE THREAD

**Issue by sukanka** [ElegantLaTeX/ElegantBook#154]
# ElegantBook 版本
4.1
# 问题
## 图片
![image](https://user-images.githubusercontent.com/31362108/120932197-6b226400-c727-11eb-80f5-45ac5e8d631f.png)
## 描述
定义环境中的脚注会出现在定义里面,另外,如果分页的话,定义里面的脚注还会到达下一页.而我希望它成为普通脚注,编号也像外面的脚注那样编号.

# MWE
```latex
\documentclass{elegantbook}

\begin{document}
    \begin{definition}
        This is an example definition.
        \footnote{An example footnote inside.}
    \end{definition}
    \footnote{An example footnote outside put closely to a definition.}
    A normal paragraph with a normal footnote.
    \footnote{A normal footnote.}
\end{document}
```
因为脚注在最底部,截图不是很好看,我直接把MWE 的 pdf 放上来.
[对应的 pdf](https://github.com/ElegantLaTeX/ElegantBook/files/6604502/main.pdf)
# 尝试过的方案
尝试过把脚注紧挨在定义的后面,但是这也会导致非常奇怪的效果.

如果有不清楚的地方,请说明,我会及时补充.

**Comment by sikouhjw** [comment]
```tex
\documentclass{elegantbook}
\begin{document}
    \begin{definition}
        This is an example definition.\footnotemark
    \end{definition}
    \footnotetext{An example footnote inside.}
\end{document}
```
