### ISSUE TITLE
统一缩进符号

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#16]
目前的 `cls` 中，空格和 tab 混用，建议统一。

个人推荐使用 2 个空格表示一层缩进，这也有利于与 latex3 代码风格统一（见 `texdoc l3styleguide`）。

PS：个人计划，待源码梳理结束后，用 latex3 重构文档类选项等部分。

**Comment by EthanDeng** [comment]
嗯，好的，之前没看过 LaTeX 里面的代码规范。LaTeX3 重构文档选项的话，我到时候能看懂吧？-_-|| 

我不懂 LaTeX3.

**Comment by muzimuzhi** [comment]
latex3 可以边看（我之后的 pr）边学，我也能参与维护这个项目一段时间，不至于改完就溜。难点不在 latex3 本身，而在 (la)tex 这门宏语言。

另，https://stone-zeng.github.io 里有两篇介绍 latex3 的文章可供参考。

**Comment by EthanDeng** [comment]
嗯 好的，我可以偷学点东西，不过，我时间并不多，今年毕业，以后有空再学吧...

另外，我把 ElegantLaTeX 当做设计，而不是编程开发/LaTeX，所以我定位是设计者，而不是开发者。

**Comment by muzimuzhi** [comment]
> 另外，我把 ElegantLaTeX 当做设计，而不是编程开发/LaTeX，所以我定位是设计者，而不是开发者。

如果确实是这么定位，我们应该分工合作。现在更像是，开发者之间的合作。即，长期来看，只要维护者稳定，设计者就不需要能看懂源码。

**Comment by EthanDeng** [comment]
怎么说呢，我并太想把这个用 LaTeX3 重写，只要错误减少，方便实用，能实现我要的效果的 LaTeX2e 的语法就行了.....

**Comment by muzimuzhi** [comment]
> 怎么说呢，我并太想把这个用 LaTeX3 重写，只要错误减少，方便实用，能实现我要的效果的 LaTeX2e 的语法就行了.....

如果定位是设计者，那么就减少对源码的关注，逐渐忽略具体实现方式，更多关注 PDF 的整体效果。源码的部分，我来做。

既「定位是设计者，而不是开发者」，又关注源码，似乎和定位不符。

**Comment by Liam0205** [comment]
我就吐槽一句：你俩理解的「设计者」不是一个概念。

**Comment by muzimuzhi** [comment]
@EthanDeng 
请问你理解的「设计者」是什么概念呢？

**Comment by EthanDeng** [comment]
你是真的闲啊...

**Comment by stone-zeng** [comment]
首先应该是有人（开发者）写一套 meta-template，然后设计者再在他提供的 api 基础之上进行设计。beamer 就是这个套路，我那边也正按照这个思路重构。

**Comment by EthanDeng** [comment]
@muzimuzhi 我这里直接给个结论吧：**我想干嘛干嘛，你在要求什么？**

我并不是要做一个完美的东西，就像 @stone-zeng 原来说过，模板用的 times 字体怎么可以称得上 elegant。但是我关心的是更重要的东西，对我来说这就是最好的选择。

我真的很不明白，你为什么执着于我们的模板，你这么*厉害*，自己去设计一个满足你的所有想法的不就好了吗？**你是真的闲**，矿里有家可能吧。

5 个月之后翻出原来的一个帖子来问我我理解的设计者，你想要什么答案？答案就是你可以在这个月内 revert 你过去提交的所有代码，我从今天开始正式通知你，今后不会接受任何你的提交（包括之前拜托你去修改的封面，已经 3 个月了）。

什么是重要的？什么是我关心的，我才是决定这一切的（还有偶尔诈尸的小学生 @Liam0205 ），而不是你！说到底这不就是一个工具吗？

**Comment by Liam0205** [comment]
被召唤了，路过一下。

btw, 可以把我标记为 inactive 了。我就是初版开发过一些东西，后来因为自己不用，就没动力开发了。
