### ISSUE TITLE
缩进问题提问

### ISSUE THREAD

**Issue by ElodieBright** [ElegantLaTeX/ElegantBook#161]
我不想要每个章节里面的段落自动缩进
请问如何修改
我打算自己手动改一下

**Comment by ElodieBright** [comment]
请问proof模块里面是不能加align模块吗
一直给我报错，且align里面的内容显示不出来
![image](https://user-images.githubusercontent.com/79014562/136523121-d5b5b335-cd67-4261-93d6-f5053f7b7521.png)

**Comment by darylz** [comment]
这个改动不生效啊

**Comment by darylz** [comment]
补充：如果使用在bookdown中，这个配制应该放在 before_body.tex，如果放在preamble.tex是不生效的。
