### ISSUE TITLE
Change default fonts

### ISSUE THREAD

**Issue by jospic** [ElegantLaTeX/ElegantBook#162]
Hi,
is there a way to choose custom fonts instead of the default ones?
If yes howto?
Thanks in advance.
-j

**Comment by sikouhjw** [comment]
You can suppress the default English font in this way.
```tex
\makeatletter
\@namedef{ver@newtxtext.sty}{9999/99/99}
\makeatother
\documentclass{elegantbook}
\begin{document}
  test
\end{document}
```
