### ISSUE TITLE
文献生成问题

### ISSUE THREAD

**Issue by TiantianUpup** [ElegantLaTeX/ElegantBook#164]
使用的环境为**vscode+Miktex**
**vscode的编译配置为**
```
{
        "name": "pdflatex -> biber -> pdflatex*2",
        "tools": [
            "xelatex",
            "biber",
            "xelatex",
            "xelatex"
        ]
 }
```
已配置使用biber编译
**引用文献方式为：**
```
\documentclass[cn,10pt,math=newtx,citestyle=gb7714-2015,bibstyle=gb7714-2015,black,simple,onecol]{elegantbook}
%引用的宏包
\usepackage{biblatex}
\usepackage{cite}

% 引用bib文件
\addbibresource{reference.bib}

\begin{document}
Learning to Navigate in Cities Without a Map \cite{liu2012tensor}.
% 打印文献
\printbibliography
\end{document}
```
其中reference.bib文件和生成pdf的latex文件为同级目录
**问题**：未能正常生成文献部分和引用

**Comment by sikouhjw** [comment]
> ```
> \documentclass[cn,10pt,math=newtx,citestyle=gb7714-2015,bibstyle=gb7714-2015,black,simple,onecol]{elegantbook}
> %引用的宏包
> \usepackage{biblatex}
> \usepackage{cite}
> 
> % 引用bib文件
> \addbibresource{reference.bib}
> 
> \begin{document}
> Learning to Navigate in Cities Without a Map \cite{liu2012tensor}.
> % 打印文献
> \printbibliography
> \end{document}
> ```

为什么要加载 `biblatex` 和 `cite`？

**Comment by TiantianUpup** [comment]
![image](https://user-images.githubusercontent.com/20486517/139639276-c1408823-f80d-45fb-82ab-ee7f891d8853.png)
看了文档说修改成biblatex编译，然后我看了网上biblatex的使用方式，然后加上了

**Comment by sikouhjw** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/20486517/139639276-c1408823-f80d-45fb-82ab-ee7f891d8853.png) 看了文档说修改成biblatex编译，然后我看了网上biblatex的使用方式，然后加上了

打开 `\texlive\2021\texmf-dist\doc\latex\elegantbook`，复制全部文件到另一个文件夹，用命令行编译 `elegantbook-en.tex`/`elegantbook-cn.tex` 能成功吗？

**Comment by TiantianUpup** [comment]
可以了，现在还有个问题就是**\printbibliography**这种生成文献的方式在目录中不会生成参考文献的章节，这是latex的风格吗
