### ISSUE TITLE
xetex 中使用非 otf 字体时，是否需要 fontenc 宏包？

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#17]
示例用法

https://github.com/ElegantLaTeX/ElegantBook/blob/789317cd48b680922afe8bdaaa2dd98ac7fa86ae/elegantbook.cls#L67-L78

根据 tex.se 上的[问答](https://tex.stackexchange.com/a/413046/79060) ，可以加载，但在 xelatex 里要保证 TU 编码是最后加载的。似乎目前的加载顺序（在 `fontspec` 之后）有些问题。

**Comment by EthanDeng** [comment]
这个上面没有写最后加载啊....我自己的理解，我之前看到的代码 fontenc 都是在字体宏包前啊，microtype 有点特殊。

**Comment by muzimuzhi** [comment]
是我贴错问题链接了
https://tex.stackexchange.com/q/470976/79060

**Comment by EthanDeng** [comment]
> fontenc is loaded by fontspec
> so it is simplest to tell people not to use `fontenc`.

已经 `fontenc` 的调用删除，感谢反馈！

**Comment by muzimuzhi** [comment]
从提交和源码看，与 `fontenc` 宏包相关的代码，没有经过修改。（可能是已提交，而尚未同步到 remote）
https://github.com/ElegantLaTeX/ElegantBook/blob/ed204e06ed3c7c0dcaf935ec38413f936d133810/elegantbook.cls#L89-L106

这个 issue 我当时写得过于模糊。经过资料查询与阅读，目前有以下几处建议：
 - xetex + en，目前未加载 `fontspec`，可以考虑加载。
 - xetex，在加载 `fontspec` 后（xetex + cn 时，`fontspec` 由 `ctex` 加载），不再加载无宏包选项（即未指定字体编码）的 `fontenc`。
 - xetex，在加载 `fontspec` 之后，如果又加载了其他字体包（内部可能使用了非 TU 编码的字体），则在导言区末尾手动添加 `\usepackage[TU]{fontenc}` 把字体编码恢复到 TU，从而保证西文重音字符的输入和断词位置判断的正确性。

**Comment by EthanDeng** [comment]
我自己本地注释了提交但还没推送到 github，就这两个包你写个 pr 吧。

**Comment by muzimuzhi** [comment]
为了避免冲突，等你推送后我再提交？

**Comment by EthanDeng** [comment]
推送了
