### ISSUE TITLE
4.1 版本中参考文献引用时如何兼容 \citep 和 \citet 引用格式?

### ISSUE THREAD

**Issue by yoczhang** [ElegantLaTeX/ElegantBook#174]
再次打扰了, 如题, 最新版本中参考文献引用时如何兼容 \citep 和 \citet 引用格式?

**Comment by sikouhjw** [comment]
![图片](https://user-images.githubusercontent.com/49770925/147576796-22b4ba86-e48e-41e1-9bbf-d167496b75b7.png)
`texdoc biblatex-gb7714-2015`

**Comment by yoczhang** [comment]
没看明白😂, 我直接在下载的模板中用 `\citep[Sec1]{ref1}` 这种形式就是会报错...

**Comment by sikouhjw** [comment]
用纯粹的 `biblatex-gb7714-2015` 没有任何问题，`elegantbook` 还没测试
```tex
\documentclass{ctexart}
\usepackage[style=gb7714-2015]{biblatex}
\addbibresource{xampl-zh.bib}
\begin{document}
  test\citep[Sec1]{chendengyuan2000guoshi}
  \printbibliography
\end{document}
```
![图片](https://user-images.githubusercontent.com/49770925/147579209-87303f3e-2f4c-4710-a143-a2d70b10543e.png)

**Comment by sikouhjw** [comment]
没有任何问题，请提供压缩过的编译失败的 `tex`、`log`、`pdf` 文件
```tex
\begin{filecontents}{reference.bib}
  
\end{filecontents}
\documentclass[cn,10pt,citestyle=gb7714-2015,bibstyle=gb7714-2015]{elegantbook}
\addbibresource{xampl-zh.bib}
\begin{document}
  test\citep[Sec1]{chendengyuan2000guoshi}
  \printbibliography
\end{document}
```
![图片](https://user-images.githubusercontent.com/49770925/147621339-63254ab5-5289-4479-ab99-93c4754ab493.png)

**Comment by yoczhang** [comment]
[test-en.zip](https://github.com/ElegantLaTeX/ElegantBook/files/7787185/test-en.zip)
简单用了直接下载的 ElegantBook 的模板

**Comment by sikouhjw** [comment]
你的发行版太老了，请换 texlive 2021
```tex
! Undefined control sequence.
l.15 \citep
           [Sec1]{en1} use data from a major peer-to-peer lending \cite{en3}..
```

**Comment by yoczhang** [comment]
好的~ 麻烦了, 感谢
