### ISSUE TITLE
 4.1在最新版本的texlive上出错。

### ISSUE THREAD

**Issue by kilasuelika** [ElegantLaTeX/ElegantBook#175]
最近用`tlmgr update -all`更新到texlive最新版本后使用elegantbook出错，即使是最简单的代码：
```
\documentclass[cn]{elegantbook}

\begin{document}
\section{测试}
\end{document}
```
错误如图所示：
![image](https://user-images.githubusercontent.com/8265798/147873755-51998404-711c-49aa-8ded-000a1068093a.png)

**Comment by kilasuelika** [comment]
另外虽然提示错误，但还是有正常的pdf输出的。

**Comment by sikouhjw** [comment]
https://bbs.pku.edu.cn/v2/post-read.php?bid=346&threadid=18179665&page=a&postid=25034627

**Comment by kilasuelika** [comment]
> https://bbs.pku.edu.cn/v2/post-read.php?bid=346&threadid=18179665&page=a&postid=25034627

感谢。

试了一下，在
elegantbook.cls里面
```
\RequirePackage{newtxtext}
```
改成
```
\RequirePackage[nofontspec]{newtxtext}
```
然后在newextext.sty里面搜索`\ifntxorigotf'改成`\ifntx@origotf'。这样可以得到正常的输出。

**Comment by sikouhjw** [comment]
临时解决方案，在 `\documentclass` 前面加上这段代码
```tex
\makeatletter
\newif\ifntx@origotf
\makeatother
\PassOptionsToPackage{nofontspec}{newtxtext}
\documentclass[cn]{elegantbook}
\begin{document}
  test \textit{楷体}
\end{document}
```

**Comment by syvshc** [comment]
> \makeatletter
> \newif\ifntx@origotf
> \makeatother

在 `newtx` 的 1.703 版本中已经不需要这三行了

**Comment by lkp520** [comment]
> newextext.sty

请问newextext.sty在哪里？

**Comment by sikouhjw** [comment]
> > newextext.sty
> 
> 请问newextext.sty在哪里？

不是给了不需要修改文件的方法吗？

**Comment by syvshc** [comment]
> > newextext.sty
> 
> 请问newextext.sty在哪里？

直接Code处下载或者clone最新的模板文件就可以

**Comment by ouening** [comment]
> > https://bbs.pku.edu.cn/v2/post-read.php?bid=346&threadid=18179665&page=a&postid=25034627
> 
> 感谢。
> 
> 试了一下，在 elegantbook.cls里面
> 
> ```
> \RequirePackage{newtxtext}
> ```
> 
> 改成
> 
> ```
> \RequirePackage[nofontspec]{newtxtext}
> ```
> 
> 然后在newextext.sty里面搜索`\ifntxorigotf'改成`\ifntx@origotf'。这样可以得到正常的输出。

我在`MacOS12.2.1 M1`环境下只添加`[nofontspec]`选项也可以解决`Kaiti SC`找不到的错误

**Comment by syvshc** [comment]
> 我在`MacOS12.2.1 M1`环境下只添加`[nofontspec]`选项也可以解决`Kaiti SC`找不到的错误

是的，因为在 v1.701 之间版本的 `newtx.sty` 修复了 `\ifntxorigotf` 的问题，可以在终端里运行 `tlmgr info newtx` 来查看您当前的 `newtx.sty` 的版本。

**如果版本号在 v1.701 -- v1.705 之间，请不要更新 `newtx` 宏包，如果一定要更新宏包，请使用 `tlmgr update -self -all -exclude "newtx"`**

这是因为在 v1.71 版本的 `newtx.sty` 出现了 bug.
