### ISSUE TITLE
windows10下楷体找不到？

### ISSUE THREAD

**Issue by ZhuangMaMS** [ElegantLaTeX/ElegantBook#176]
测试legantbook.cn，字体找不到？
`Package fontspec Error: The font "KaiTi" cannot be found. \maketitle`
更换字体选项为 `chinesefont=founder`也会报错（字体已下载，并为所有人安装），
`Package fontspec Error: The font "FZKai-Z03" cannot be found. \maketitle`。
环境是windows10+TeXlive2021，已经把宏包更新最新版。
此外按照书的字体网盘链接，测试方正字体是有正确输出的

```tex
\documentclass[fontset=none]{ctexart}
\setCJKmainfont[BoldFont={FZHei-B01},ItalicFont={FZKai-Z03}]{FZShuSong-Z01}
\setCJKsansfont{FZHei-B01}
\setCJKfamilyfont{zhsong}{FZShuSong-Z01}
\setCJKfamilyfont{zhhei}{FZHei-B01}
\setCJKfamilyfont{zhkai}{FZKai-Z03}
\setCJKfamilyfont{zhfs}{FZFangSong-Z02}
\setCJKfamilyfont{zhli}{FZLiShu-S01}

\newcommand*{\songti}{\CJKfamily{zhsong}} % 宋体
\newcommand*{\heiti}{\CJKfamily{zhhei}} % 黑体
\newcommand*{\kaiti}{\CJKfamily{zhkai}} % 楷体
\newcommand*{\fangsong}{\CJKfamily{zhfs}} % 仿宋
\newcommand*{\lishu}{\CJKfamily{zhli}}    % 隶书

\begin{document}

\Large

\centering

\begin{quote}
本站购买了北大方正的字库授权，大家可以按照如上代码设置中文显示即可。
\end{quote}

\begin{tabular}{ll}
 \verb|\songti|&\songti
书宋体，CJK 等价命令 \verb|\CJKfamily{zhsong}|。\\
 \verb|\heiti|&\heiti
方正黑体，CJK 等价命令  \verb|\CJKfamily{zhhei}|。\\
 \verb|\fangsong|&\fangsong
方正仿宋，CJK 等价命令  \verb|\CJKfamily{zhfs}|。\\
 \verb|\kaiti|&\kaiti
方正楷体，CJK 等价命令  \verb|\CJKfamily{zhkai}|。\\
\multicolumn{2}{l}{在 founder 字库中，额外定义了隶书}\\
 \verb|\lishu|& \lishu
方正隶书，CJK 等价命令  \verb|\CJKfamily{zhli}|。\\
\end{tabular}
\end{document} 
```

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/175

**Comment by feiyunw** [comment]
newtxtext有点问题，临时处理的话可以先这么改：
`
--- D:/texlive/2021/texmf-dist/tex/latex/elegantbook/elegantbook.cls	Sat Jan  8 17:27:16 2022
+++ D:/texlive/2021/texmf-dist/tex/latex/elegantbook/elegantbook_new.cls	Sat Jan  8 17:29:01 2022
@@ -199,7 +199,7 @@
   \newcommand{\cfs}{\normalfont}
 \fi
 
-\RequirePackage{newtxtext}
+\RequirePackage[nofontspec]{newtxtext}
 \RequirePackage{anyfontsize}
 \ifdefstring{\ELEGANT@math}{newtx}{
   \RequirePackage{newtxmath}
`

**Comment by sikouhjw** [comment]
> newtxtext有点问题，临时处理的话可以先这么改： ` --- D:/texlive/2021/texmf-dist/tex/latex/elegantbook/elegantbook.cls Sat Jan 8 17:27:16 2022 +++ D:/texlive/2021/texmf-dist/tex/latex/elegantbook/elegantbook_new.cls Sat Jan 8 17:29:01 2022 @@ -199,7 +199,7 @@ \newcommand{\cfs}{\normalfont} \fi
> 
> -\RequirePackage{newtxtext} +\RequirePackage[nofontspec]{newtxtext} \RequirePackage{anyfontsize} \ifdefstring{\ELEGANT@math}{newtx}{ \RequirePackage{newtxmath} `

https://github.com/ElegantLaTeX/ElegantBook/issues/175#issuecomment-1006375133

**Comment by syvshc** [comment]
https://github.com/ElegantLaTeX/ElegantBook/pull/177

**Comment by ouening** [comment]
> 如 pr #177 更新模板版本或者按照 pr 进行修改即可

谢谢！希望可以更新至下游库

**Comment by syvshc** [comment]
> 谢谢！希望可以更新至下游库

由于作者还有一些小功能没有完善，所以还没有推送，同时如 https://github.com/ElegantLaTeX/ElegantBook/issues/175#issuecomment-1059917803 所说，在 `newtx` 宏包出问题的情况下，可以等等再推到 ctan.

**Comment by EthanDeng** [comment]
修改之后，新版 newtx 与模板还是有些问题，暂时不更新到 CTAN，请参照 #175 暂时手动修改。
