### ISSUE TITLE
ElegantBook-4.1版本编译报错

### ISSUE THREAD

**Issue by knightdby** [ElegantLaTeX/ElegantBook#180]
win11，Vscode+texlive2021，编译ElegantBook-4.1，编译方式"xe->bibtex->xe->xe" 。
代码未修改，直接download，然后编译，报错：

![image](https://user-images.githubusercontent.com/75298418/154666811-7c2a987c-2395-46d0-bfff-77223c18c275.png)

**Comment by sikouhjw** [comment]
用 `biber`

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/blob/909fb2c99761a1b4f40815d0f3ba39f73315c3c9/elegantbook.cls#L347-L350
写死了，改不了

**Comment by knightdby** [comment]
已修改cls文件，相应的代码，可以实现。
但存在后续问题，如无编号问题。
感觉这种方式，可以在参考文献中只保留所引用的文献。
![image](https://user-images.githubusercontent.com/75298418/154670398-38b1bd14-8650-4ec9-b9c8-9df1d594729d.png)

**Comment by sikouhjw** [comment]
> 已修改cls文件，相应的代码，可以实现。 但存在后续问题，如无编号问题。 感觉这种方式，可以在参考文献中只保留所引用的文献。 ![image](https://user-images.githubusercontent.com/75298418/154670398-38b1bd14-8650-4ec9-b9c8-9df1d594729d.png)

1. 给代码，谁知道你是不是用了『著者-出版年制』制
2. 什么叫『这种方式』？

**Comment by knightdby** [comment]
抱歉，没有严谨表述。
现有的方式会把.bib文件中所有参考文献列出，而“\bibliography{References/Chapter,References/Literature}”这种方式，仅会将.tex文件中\cite引用的参考文献列出。总的而言，更倾向于后者。
至于Code，只是粗略简单的修改部分，当然也是小白，研究并不深入。乱动您的代码，见谅。

**Comment by knightdby** [comment]
哦哦，原来是这样，get。
还是能够自动选择输出参考文献比较好呢。

**Comment by knightdby** [comment]
您好，打扰您了，想请教一下您一个问题：
main.tex
\def\allfiles{}
subfile.tex
\ifx\allfiles\undefined
  全局文件
\else
  局部文件
\fi

上述代码无论在main文件运行，还是subfile文件运行，生成结果都是局部文件，这个原因是什么？不应该是一个输出“全局文件”，一个输出“局部文件”。main和subfile文件通过\subfile{subfile}和\documentclass[main]{subfiles}两个命令相连接。

**Comment by EthanDeng** [comment]
`backend=biber` 这个后面应该会加上一个可选项，叫 `backend`，可选 `bibtex` 或者 `biber`。
