### ISSUE TITLE
升级宏包后，找不到字体

### ISSUE THREAD

**Issue by HidekiHokuto** [ElegantLaTeX/ElegantBook#183]
升级前founder字体一直可以正常使用，

昨日升级tlmgr后，提示找不到founder的一系列字体，可是font book中可以看到这些字体...

! Package fontspec Error: The font "FZKai-Z03" cannot be found.

**Comment by stone-zeng** [comment]
- #175
- #176

**Comment by HidekiHokuto** [comment]
感谢回复，报错已解决。
