### ISSUE TITLE
elegantbook代码框

### ISSUE THREAD

**Issue by Allinaent** [ElegantLaTeX/ElegantBook#184]
您好，大佬。
![image](https://user-images.githubusercontent.com/11778493/158295664-4f70d103-fd99-4e92-87cc-92df8e38d92a.png)
我用您的elegantbook写文档，其它地方都很好，就是代码框分页的地方不太美观，希望您能帮忙解决一下，万分感谢！

**Comment by StableAgOH** [comment]
建议拆分成两个 `lstlisting` 或者换用 `minted`

**Comment by StableAgOH** [comment]
我目前的解决方法是拆分成两个 `lstlisting` 或者直接不要边框 `\begin{lstlisting}[frame=none]`

**Comment by Allinaent** [comment]
如果您能提供一个minted的elegantbook风格的模板就太棒了。 @StableAgOH

**Comment by StableAgOH** [comment]
@Allinaent 有点没看懂你说的啥意思……直接在 `elegantbook` 中使用 `minted` 宏包就行了啊

**Comment by Allinaent** [comment]
> @Allinaent 有点没看懂你说的啥意思……直接在 `elegantbook` 中使用 `minted` 宏包就行了啊

我的意思是搞个.sty之类的，封装一下，用起来像Typora，更好的样式。 @EthanDeng

**Comment by Allinaent** [comment]
看了其它的一些issue 例如：https://github.com/ElegantLaTeX/ElegantBook/issues/163，latex算是宏语言；minted自动换行有些不好解的地方。
