### ISSUE TITLE
cls L1203 参考文献文件命令可否去掉

### ISSUE THREAD

**Issue by hy-zhao** [ElegantLaTeX/ElegantBook#185]
cls 第1203行的参考文献定义让文件名和使用方式都被限制了，如果overleaf使用似乎也没法每次都自己上传文件。这一句去掉对文件整体不会产生印象，同时用户可以自定义文件名或者使用远程文件。

**Comment by hushidong** [comment]
你既然知道可以用远程的，就没有试试导言区直接加么？不像传统方式只能有一个bib库，biblatex可以使用n个库，只是若entrykey相同，后面的会覆盖前面。

**Comment by hy-zhao** [comment]
好的，谢谢回复，我不清楚biblatex可以用多个库，只是它一直会报reference.bib丢失的错。
