### ISSUE TITLE
关于 `package fontspec: xxx cannot be found` 的问题

### ISSUE THREAD

**Issue by syvshc** [ElegantLaTeX/ElegantBook#188]
首先这个问题大概率是由于 `newtx` 宏包更新到 `1.7` 之后出现的. 

命令行运行 `tlmgr info newtx` 可以看到当前 `newtx` 系列宏包的版本. 

1. 如果 `cat-version` 显示为 `1.7` 及以上, 但不是 `1.71`, 如下

```bash
❯ tlmgr info newtx
package:     newtx
category:    Package
shortdesc:   Alternative uses of the TX fonts, with improved metrics
longdesc:    The bundle splits txfonts.sty (from the TX fonts distribution) into two independent packages, newtxtext.sty and newtxmath.sty, each with fixes and enhancements. newtxmath's metrics have been re-evaluated to provide a less tight appearance, and to provide a libertine option that substitutes Libertine italic and Greek letter for the existing math italic and Greek glyphs, making a mathematics package that matches Libertine text quite well. newtxmath can also use the maths italic font provided with the garamondx package, thus offering a garamond-alike text-with-maths combination.
installed:   Yes
revision:    61581
sizes:       doc: 901k, run: 17977k
relocatable: No
cat-version: 1.705
cat-license: lppl1.3
cat-topics:  font font-body font-maths font-serif font-proportional font-type1 font-otf font-supp font-t1enc
cat-related: minion2newtx
collection:  collection-fontsextra
```

那么在 `Code` 处[下载](https://github.com/ElegantLaTeX/ElegantBook/archive/refs/heads/dev.zip)最新版模板即可解决, 并且在后续更新宏包的时候使用

```bash
tlmgr update -self -all -exclude newtx
```

来忽略 `newtx` 的更新, 

2. 如果 `cat-version` 为 `1.71`. 首先命令行运行 

```bash
tlmgr restore newtx
```

来查看本地是否有备份文件, 

* 如果有如下返回

```bash
❯ tlmgr restore newtx
Available backups for newtx: 61581 (2022-03-05 19:35)
```

那么命令行运行 

```bash
tlmgr restore newtx 61581
```

来将 `newtx` 回滚到 `1.705` 版本. 再使用最新的模板就可以了. 

* 如果没有返回, 说明本地没有备份文件, Windows 可以下载 [newtx.r61581.tar.zip](https://github.com/ElegantLaTeX/ElegantBook/files/8422763/newtx.r61581.tar.zip), 解压后可以得到 `newtx.r61581.tar.lz4` 压缩包; Linux 可以下载 [newtx.r57192.tar.zip](https://github.com/ElegantLaTeX/ElegantBook/files/8439163/newtx.r57192.tar.zip), 解压后可以得到 `newtx.r571792.tar.lz4`, 把它放到 `texlive/20xx/tlpkg/backups/` 文件夹下, 再运行

```bash
tlmgr restore newtx
```

可以看到有可回滚的版本, 按上面的操作回滚版本并使用新的模板文件即可. 

我会关注该宏包的动向, 并且看看有没有替代的方法, 会在这个 issue 中继续更新, 可以在旁边点一个 "Subscribe" 来订阅这个 issue. 有问题也可以留言

**Comment by wpzhangz** [comment]
Add \defaultfontfeatures{} after loading newtx.

**Comment by syvshc** [comment]
> Add \defaultfontfeatures{} after loading newtx.

Thanks for the advice, we have removed `newtxtext` package in https://github.com/ElegantLaTeX/ElegantBook/commit/eb233e43098ee13d72830bb12dddf877b0baec5b
