### ISSUE TITLE
Old syntax for theorem, definitions, etc.

### ISSUE THREAD

**Issue by jaikrishnanj** [ElegantLaTeX/ElegantBook#189]
I have composed a set of notes using elegantbook. But with the latest update to TexLive, it looks like the custom syntax for theorems has changed. The code below no longer gives the right output. 

\begin{theorem}{theorem name}{label text}
The content of theorem.
\end{theorem}

Should I manually shift to the correct syntax in this 300 page document?

**Comment by EthanDeng** [comment]
I am sorry for that, I thought the old syntax still works, I didn't receive much feedbacks. I will look into these codes, and fix it if possible, you can hold on for a while. 

If I cannot fix it recently, I will offer a regular expressions for you to convert the old syntax to new syntax. I don't think manually correct this is a good idea.

Thank you for your feedback!

**Comment by jaikrishnanj** [comment]
Thanks a lot EthanDeng!

**Comment by syvshc** [comment]
This bug was fixed in https://github.com/ElegantLaTeX/ElegantBook/pull/190 .
