### ISSUE TITLE
texlive 2022 升级后编译通不过

### ISSUE THREAD

**Issue by silentmissile** [ElegantLaTeX/ElegantBook#193]
texlive 2022，在2022.4.29日升级后编译自带的elegantbook-cn.tex通不过，提示错误信息如下

LaTeX3 Error: Mismatched LaTeX support files detected. \ExplLoaderFileDate{expl3.sty}}
Undefined control sequence. \sys_if_output_pdf:TF
LaTeX3 Error: Control sequence \ifctexpdf already defined. { \cs_new_eq:NN \ifctexpdf
Unable to load picture or PDF file 'cover.jpg'. ^^I\maketitle
Package graphics Error: Division by 0. ^^I\maketitle
Unable to load picture or PDF file 'logo-blue.png'. ^^I\maketitle
Package graphics Error: Division by 0. ^^I\maketitle
No file document.aux.
Rerun to get /PageLabels entry.

**Comment by EthanDeng** [comment]
缺少文件，自带的文件需要依赖于当前 repo 里面的几个图片以及 bib 文件，你从 github 下载整个项目吧。

**Comment by sikouhjw** [comment]
看起来是升级失败的问题，参考 `texdoc install-latex`，命令行输入
```
fmtutil-sys --all
```

**Comment by silentmissile** [comment]
> 看起来是升级失败的问题，参考 `texdoc install-latex`，命令行输入
> 
> ```
> fmtutil-sys --all
> ```

看来你是对的，我把整个texlive全部重装之后好了
