### ISSUE TITLE
功能建议: 我觉得环境和段落之间的间距应该是两倍会比较好

### ISSUE THREAD

**Issue by wowow005** [ElegantLaTeX/ElegantBook#195]
比如下面这张图是笔记演示中的

![image](https://user-images.githubusercontent.com/61683315/166150133-5f419575-731e-48f0-883f-df3454271f0c.png)

不会觉得定理类环境、note 环境 和自然段落之间的间距太小吗? 显得文本都挤在一起, 反而看不出重点.

我在环境和普通段落之间加了一点空行(通过加入  `\vspace*{1\baselineskip}` )
, 一下子就清晰了, 下图是我的笔记

![image](https://user-images.githubusercontent.com/61683315/166150186-3c9431fb-fcf4-4e76-8a19-3539f5a56d6c.png)

但是这种实现方式不优雅, 我想应该可以调整默认的环境和段落之间的间距, 把这个间距(我画双红线的部分)做的更大一点, 是不是会更好看呢? 如下所示

![Snipaste_2022-05-01_22-29-14](https://user-images.githubusercontent.com/61683315/166150469-ec4538f9-08a9-4e40-968e-ce5791ab9476.png)

不知道我的建议合不合理? 期待你的回复.

**Comment by EthanDeng** [comment]
建议很好，不过一直觉得 tcolorbox 的框太大了，如果行距设置太大，会有稀疏的那种感觉，我自己可能偏向于比较紧凑的格式吧，大部分情况下，我都是偏向于 compact 的格式，除了设计作品之类的。

**Comment by wowow005** [comment]
好的, 我会去尝试一下自己去手动修改的.
