### ISSUE TITLE
`\uwave` 支持欠佳

### ISSUE THREAD

**Issue by tripleInt** [ElegantLaTeX/ElegantBook#197]
如果使用”下波浪线“ `\uwave` 命令，有时会偏移文本本身所在的位置。望修复！

![image](https://user-images.githubusercontent.com/73740872/167110134-3286e3c9-5b93-4377-8cad-4f413c8392df.png)

**Comment by syvshc** [comment]
这个问题已经在 https://github.com/CTeX-org/ctex-kit/commit/ad44c6674bb377653544349f23b7c629bc9e4677 中解决, 如果有需要可以自行生成新的 `xeCJKfntef.sty` 或者等待 CTAN 上的更新.
