### ISSUE TITLE
关于**旁注**的一点想法和建议

### ISSUE THREAD

**Issue by jcx70100** [ElegantLaTeX/ElegantBook#199]
# 背景

在接触`ElegantBook`之前，尝试过使用 [kaobook](https://github.com/fmarotta/kaobook) 

进行知识整理和排版，但`kaobook`对中文的支持有限，虽然有爱好者基于中文环境对其进行了优化，但编译日志并不清爽，存在很多非关键警告，对强迫症患者不友好。

`kaobook`最大的设计亮点是在书籍侧边留了部分留白，用于笔记记录和必要补充材料的展示，也是早期一直硬着头皮使用该模版的核心原因（会有报错和警告，不过勉强能编译成功，并不完美，对中文支持有限）。

在使用`ElegantBook`后，其极大的便利性和灵活性，以及对中文的天生兼容让人使用起来如丝般顺滑，爱不释手！不过至今对**旁注**这个功能念念不忘。

# 对旁注新的理解

通过查询`ElegantBook`的日志，发现其本身带有旁注功能，在展现形式上，是在页面局部区域进行旁注标识，与`kaobook`中全局的页面侧边留白存在差异，但功效是一致的。

由于日志中开发者提到目前尚没有完美的旁注解决方案，仅保留旁注的语法，并未作为特征功能进行推广，不过像**旁注这种笔记结构是笔记整理和书籍排版过程中切实需要的**。

旁注因其结构区域的特殊，导致其存在一定局限性，其中**最大的局限便是内容长度的限制**，过长的旁注会影响排版美观。对此，出于**需求迫切**，经常思考有没有替代方案，在偶然间突然有个想法，便是”**旁注为什么非要在旁边？** “ 比起横向结构的引入可能会受到更多条条框框的影响，上下结构的引入便是顺应文本内容天然的上下文走向，面临的局限可能会更小。

基于上述观念的转变，我想旁注的展现形式是否可以以上下的方式进行呈现。这里我用word画了一个草图：

* 原始旁注如下：

    <img width="713" alt="zlM76" src="https://user-images.githubusercontent.com/8111364/168007009-b1837d66-1eba-45c3-85b8-515df3b196ac.png">

* 新的笔记结构如下：

<img width="671" alt="zfwOF" src="https://user-images.githubusercontent.com/8111364/168007023-11de5762-7d1d-400b-b536-561b101fc796.png">

区别于`ElegantBook`中现有的`定理`、`习题`等结构，该笔记结构需要做到：

1. 在原文段落中标记出原文区段
2. 该段落下方创建笔记块
3. 如果能给笔记块添加小标题并在目录中单独展现笔记目录就很完美了

这种结构可有效解决笔记内容过多带来的横向排版（旁注）问题，不知道设计上会不会更方便一些。

以上仅是一点点新的想法，由于不是Latex资深用户，关键词的表述可能不准确，还请见谅。

**Comment by EthanDeng** [comment]
原来有一个旁注命令的 `\elegantpar`，由 tikz 做的，[ElegantPar](https://www.latexstudio.net/index/details/index/mid/437.html)，但是中间有点小问题吧，忘了啥问题了，后面用的人也不多就去掉了。

你说的这个感觉应该不难做。

**Comment by sikouhjw** [comment]
可以考虑用 `thmtools` 宏包，『在原文标记』可以将 `\autoref` 封装一下。不过项目准备永久不更新了。
