### ISSUE TITLE
修改字体参数导致封面出现异常空白

### ISSUE THREAD

**Issue by eeyrw** [ElegantLaTeX/ElegantBook#2]
想把英文字体改成沿用自带的Computer Modern，所以注释掉了如下语句：
```
% fontsetting
\RequirePackage{ifxetex}
\ifxetex
	\RequirePackage{fontenc}
	\RequirePackage[no-math]{fontspec}
	%\setmainfont{Times New Roman}[NFSSFamily=ntxtlf]
	%\setsansfont{Arial}
...
```
但是发现这样会导致封面变成这样：
![image](https://user-images.githubusercontent.com/2088817/53309214-992a6400-38e1-11e9-9924-e277a27baa36.png)

**Comment by EthanDeng** [comment]
其实不用完全注释掉那部分，xelatex 下的设置不用改动，如果你要使用 CM 字体，你可以就用 pdflatex，然后把 newtxtext 宏包注释掉，然后把 461 行 \hfill 注释掉，这样就行了。我不太懂为什么 newtxtext 宏包和这个距离有关系，可能字体大小？字距之类的。下次更新我会把这个 \hfill 删除。谢谢反馈！

Kind Regards,
________________________________
Dongsheng Deng
Fudan University, Shanghai, China
Email: ddswhu@outlook.com<mailto:%C2%A0ddswhu@outlook.com>
Website: https://ddswhu.me/

发件人： Yuan<mailto:notifications@github.com>
发送时间： 2019-02-25 09:42
收件人： ElegantLaTeX/ElegantBook<mailto:ElegantBook@noreply.github.com>
抄送： Subscribed<mailto:subscribed@noreply.github.com>
主题： [ElegantLaTeX/ElegantBook] 修改字体参数导致封面出现异常空白 (#2)

想把英文字体改成沿用自带的Computer Morden，所以注释掉了如下语句：

% fontsetting
\RequirePackage{ifxetex}
\ifxetex
        \RequirePackage{fontenc}
        \RequirePackage[no-math]{fontspec}
        %\setmainfont{Times New Roman}[NFSSFamily=ntxtlf]
        %\setsansfont{Arial}
...


但是发现这样会导致封面变成这样：
[image]<https://user-images.githubusercontent.com/2088817/53309214-992a6400-38e1-11e9-9924-e277a27baa36.png>

**Comment by EthanDeng** [comment]
你把这两行注释掉之后，用里面的那个最小示例选择 PDFLaTeX 运行下，应该是没问题的。


[ElegantBook-Test.zip](https://github.com/ElegantLaTeX/ElegantBook/files/2898988/ElegantBook-Test.zip)

**Comment by eeyrw** [comment]
你好，我测试了下，可以了。但是一定要用pdflatex么，我用的是xelatex。我用xelatex测试了ElegantBook-Test.zip，按照之前说的的注释掉newtxtext 宏包，461 行 \hfill，以及注释掉	%\setmainfont{Times New Roman}[NFSSFamily=ntxtlf]和%\setsansfont{Arial}也不会出现多余的空白了。

**Comment by EthanDeng** [comment]
XeLaTeX 也是可以，但是我觉得既然使用 XeLaTeX，自定义字体不是更好么？因为宋体和 CM 字体不怎么搭配，仅供参考！

**Comment by eeyrw** [comment]
沉溺于CM字体不能自拔 ：）
