### ISSUE TITLE
中文显示问题

### ISSUE THREAD

**Issue by TXC-ALON** [ElegantLaTeX/ElegantBook#208]
![image](https://user-images.githubusercontent.com/49758976/176145223-396843a4-e54e-4d77-b74e-f7821121b2bc.png)
问题：我是直接打开elegantbook-cn.tex。使用xelatex编译的。没有做过修改，英文部分正常，中文显示不出来，
配置：win10 + Miktex 安装elegantbook。
请问这是什么原因？

**Comment by TXC-ALON** [comment]
设置
\documentclass[lang=cn,10pt，chinesefont=ctexfont]{elegantbook}
\documentclass[lang=cn,10pt，chinesefont=founder]{elegantbook}
编译都没有报错，但都没有中文。

**Comment by syvshc** [comment]
`\documentclass[lang=cn,10pt，chinesefont=ctexfont]{elegantbook}`
10pt 后面的逗号应为英文逗号

**Comment by TXC-ALON** [comment]
我的疏忽，不过FZHei-B01这些字体没有安装好的也不会有中文，不过我一个个下好了，最终结果出来了，非常感谢
字体链接：https://pan.baidu.com/s/1mfN1nFCogRPFXGpwl8rovg?pwd=46tn 
建议希望对后面的人有帮助

**Comment by syvshc** [comment]
如果方正系的字体没装好理论上不会对 `chinesefont=ctexfont` 产生影响
