### ISSUE TITLE
How to modify the header? (\chapter*{}, title or just hide the chapter)

### ISSUE THREAD

**Issue by moshpirit** [ElegantLaTeX/ElegantBook#209]
I'd like to show the title of the chapter, which is fine, but sometimes I use `\chapter*{}`, so it appears "General index" or the name of a previous section, which is very awkward sometimes. I'd like to be able to modify it so it shows the chapters when they are hidden with `*` or at least hide this part of the header or show the title of the document instead.

**Comment by syvshc** [comment]
Could you please upload some pictures to clarify your problem? I didn't understand it.

**Comment by moshpirit** [comment]
Sure, I mean this: 
![imagen](https://user-images.githubusercontent.com/7888062/176474427-9bc33c4a-f022-473b-be2d-ccdca3d2c289.png)

When I use `\chapter*{}` and `\section*{}`, things get messy, and I'd like to be able to modify it so I can show another stuff like the title of the document, the name of the `\chapter*{}` or `\section*{}`. 

If you want me to share any other kind of information or screenshots, feel free to ask :)

**Comment by syvshc** [comment]
I think that this question has nothing to do with elegantbook. In book class things work the same.

```latex
% \documentclass{elegantbook}
\documentclass{book}
\usepackage{fancyhdr}
\usepackage{lipsum}
\begin{document}
  % \maketitle
  \chapter{test chap}
  \section{test sec}
  \lipsum[1-20]
  \chapter*{}
  \section*{}
  \lipsum[1-20]
\end{document}
```
In `\chapter*{}`:
![image](https://user-images.githubusercontent.com/38098591/176626597-98a9ce8e-4048-4322-b56f-10a5a8a57a0a.png)

**Comment by moshpirit** [comment]
I see, then I'll ask somewhere else, sorry for bothering! Is it ok if I share the solution here if I find it, or do you prefer that I don't?
