### ISSUE TITLE
目录里第几章的「章」和本章名称重叠

### ISSUE THREAD

**Issue by XiangyunHuang** [ElegantLaTeX/ElegantBook#218]
最初接到用户在统计之都论坛[反馈](https://d.cosx.org/d/420628-latex-elegantbook/27)

## 问题描述

当章节数量超过 10 就会出现目录里第几章的「章」和本章名称重叠。

## 问题复现

只需将模版里的

```tex
\documentclass[lang=cn,10pt,newtx]{elegantbook}
```

替换为

```tex
\documentclass[lang=cn,10pt,newtx,scheme=chinese]{elegantbook}
```

然后在后文内容上，添加一些空白章节

```tex
\chapter{ElegantBook 写作示例}
\chapter{ElegantBook 写作示例}
\chapter{ElegantBook 写作示例}
\chapter{ElegantBook 写作示例}
\chapter{ElegantBook 写作示例}
\chapter{ElegantBook 写作示例}
```

编译出来后，在目录里，就可以看到问题了，见下图。

<img width="989" alt="截屏2022-09-02 20 38 20" src="https://user-images.githubusercontent.com/12031874/188146133-876499ef-1220-486c-8e54-1f7d1735e6c7.png">

**Comment by EthanDeng** [comment]
这个是因为目录里面宽度设定为固定宽度导致的，确定是模板的问题，我周末看下。

**Comment by EthanDeng** [comment]
根据[这个帖子](https://tex.stackexchange.com/questions/64115/table-of-contents-chapter-number-width)改动，模板在仓库的最新版更新了目录的设定。

**Comment by XiangyunHuang** [comment]
谢谢！
