### ISSUE TITLE
如果latex分章去写，从第7章开始就都以附录方式进行计数了

### ISSUE THREAD

**Issue by YellowPuppy** [ElegantLaTeX/ElegantBook#219]
latex分章去写，从第7章开始就都以附录计数了，请问是什么问题呢？但是不分章的话，就不会有这个问题，但是写作起来会显得很笨重。求教各位大佬该怎么改cls文件呢？具体见下图：
![1](https://user-images.githubusercontent.com/94440332/188265501-9b072958-4c12-4314-889a-c99f9d0dffa8.png)
![2](https://user-images.githubusercontent.com/94440332/188265503-25a79194-7f73-4ddd-99ef-a8f1ac196863.png)

**Comment by syvshc** [comment]
检查一下这些文件中有没有 `\appendix` 命令

**Comment by YellowPuppy** [comment]
> 检查一下这些文件中有没有 `\appendix` 命令

好的多谢！已经找到\appendix命令了，问题已解决。
