### ISSUE TITLE
关于编译时参考文献的显示问题

### ISSUE THREAD

**Issue by ningpang** [ElegantLaTeX/ElegantBook#225]
编译时遇到两个问题：

1. 在打印参考文献时，会显示我bib文件中的全部文献，其中大部分是在文档中没有交叉引用的，如何仅显示我已引用的文献呢？
2. 我希望每一章的后面显示该章节的参考文献，是否能支持？

**Comment by ningpang** [comment]
感谢您的解答

**Comment by sikouhjw** [comment]
第一个问题，注释 `\nocite{*}`。

第二个问题，https://github.com/ElegantLaTeX/ElegantBook/issues/187 。
