### ISSUE TITLE
使用无编号定理类环境报错：`Undefined control sequence. \tcbtitletext ...emname\endcsname ~\thetcbcounter`

### ISSUE THREAD

**Issue by ShivangSong** [ElegantLaTeX/ElegantBook#227]
我在 MacBook 上用 TeX Live 2022 编译 ElegantBook 4.4 版本时，出现报错，编译方式为 XeLaTeX，这是我的注释掉无关代码后的 MWE：
```
\documentclass{elegantbook}
\begin{document}
\begin{theorem*}
  Theorem.
\end{theorem*}
\end{document}
```
报错为
```
Undefined control sequence.
\tcbtitletext ...emname\endcsname ~\thetcbcounter 
```

**Comment by syvshc** [comment]
旧版本的 `tcolorbox` 宏包中如果未定义 `\thetcbcounter` 的话是直接不显示, 在新版本的 [`tcolorbox` 宏包](https://www.ctan.org/pkg/tcolorbox) 中未定义 `\thetcbcounter 的时候会报 `Undefined control sequence`, 在 dev 分支已经修复. 见 https://github.com/ElegantLaTeX/ElegantBook/commit/9b8b09df54901c0f0be2169d81521850b47841ed
