### ISSUE TITLE
参考文献引用能够显示成数字形式吗？[1,5-6]

### ISSUE THREAD

**Issue by cslyc** [ElegantLaTeX/ElegantBook#228]
模板中的参考文献显示的是检索号形式，[en1, en2, en3]，是否可以像IEEE格式那样显示为数字编号？如[1, 5-6]

**Comment by sikouhjw** [comment]
> 模板中的参考文献显示的是检索号形式，[en1, en2, en3]

说明你没有编译成功，请使用 `biber` 编译参考文献。关于编译请去阅读 `texdoc LSHORT-ZH`。

**Comment by cslyc** [comment]
非常感谢！确实是忘记把编译器从bibtex修改为biber了
