### ISSUE TITLE
功能請求，增加GitHub Action自動編譯

### ISSUE THREAD

**Issue by henryclw** [ElegantLaTeX/ElegantBook#230]
最近發現了一個GitHub Action可以自動編譯，並且在創建Release的時候自動把pdf亦編譯好上傳到Release附件當中，這個亦可以作爲CI/CD，讓後面提交pull request的代碼先過一次自動編譯確保能成功。如果覺得這個功能不錯，我可以提交一個 pull request

**Comment by EthanDeng** [comment]
之前试过 但是容易出错，后来就没试过了。

**Comment by henryclw** [comment]
> 之前试过 但是容易出错，后来就没试过了。

請問容易出錯是指編譯不了嗎？

**Comment by sikouhjw** [comment]
项目准备永久不更新了

**Comment by henryclw** [comment]
> 项目准备永久不更新了

是沒有活躍的maintainer了嗎？如果不維護了就大家自己fork了？不想看到這麼好的一個項目凋零。

**Comment by sikouhjw** [comment]
> 是沒有活躍的maintainer了嗎？如果不維護了就大家自己fork了？不想看到這麼好的一個項目凋零。

公告：
2022 年 12 月 31 日后 ElegantLaTeX 系列模板不会再有任何改动，请用户选择性的慢慢迁移到 ctexart/ctexbook 文类。
后续会出具体处置公告，包括可能会把部分特性抽出来，单独做特性一个实现代码的 repo，方便迁移现在的效果到你们自己的文档。

主要有几个原因，一是当时的中文处理并不好，为了兼容 pdflatex 和 xelatex，ElegantLaTeX 做了很多处理，但是现在已经没这个问题了。二是模板的用户都很喜欢改模板，但模板很多内容写的很死，不好改，所以现在的处境很尴尬。三是 maintainer 都比较忙，偶尔处理小 bug 还行，集中改进模板是没精力了，因此就准备彻底不更新了。

**Comment by henryclw** [comment]
好的，那就自己維護自己的模板吧。

謝謝，祝好。
