### ISSUE TITLE
一个因未知原因而产生的奇怪报错, 未在用户群得到答案

### ISSUE THREAD

**Issue by SakuraiMeteroa** [ElegantLaTeX/ElegantBook#231]
准备在VSCode上使用ElegantBook模板写一个新的笔记时, 根据个人以往习惯, 于导言区使用了如下命令 :
\usepackage{xeCJK,amssymb,amsmath,extarrows,mathrsfs,tikz,latexsym,inputenc,yhmath,graphicx}
\usetikzlibrary{graphs}
\usetikzlibrary{cd}
\makeatletter
\newcommand{\rmnum}[1]{\romannumeral #1}
\newcommand{\Rmnum}[1]{\expandafter\@slowromancap\romannumeral #1@}
编译后出现了如下报错 (以往在VSCode上使用ElegantBook模板写笔记时, 并未出现该报错):
![image](https://user-images.githubusercontent.com/119157508/204126873-c898388a-a4c0-4621-b03e-fce4042be9b2.png)
点记报错提示后显示内容为
![image](https://user-images.githubusercontent.com/119157508/204126943-15357381-9668-4690-ac57-a999b9d5da22.png)
想知道报错产生的原因及解决办法, 谢谢!

**Comment by syvshc** [comment]
首先不要有个人习惯, 宏包按需加载, 然后涉及的 `yhmath` 的问题, 请阅读手册以下部分
https://github.com/ElegantLaTeX/ElegantBook/blob/99eb12f4c44e11261dc1b69e62f2c182ef0898c8/elegantbook-cn.tex#L792-L810
