### ISSUE TITLE
Enhancement: lualatex compatibility

### ISSUE THREAD

**Issue by Firestar-Reimu** [ElegantLaTeX/ElegantBook#232]
99% of ElegantLaTeX can be moved from xelatex to lualatex, but:

### Elegantbook:

```latex
  \ifdefstring{\ELEGANT@chinesefont}{nofont}{
    \RequirePackage[UTF8,scheme=plain,fontset=none]{ctex}
    \xeCJKsetup{AutoFakeBold=true}
    }{\relax}

  \ifdefstring{\ELEGANT@chinesefont}{ctexfont}{
    \RequirePackage[UTF8,scheme=plain]{ctex}
    \xeCJKsetup{AutoFakeBold=true}
    }{\relax}
```
one solution is to **remove the autofakebold function**

another solution is:
```latex
  \ifdefstring{\ELEGANT@chinesefont}{nofont}{
    \RequirePackage[UTF8,scheme=plain,fontset=none]{ctex}
    \RequirePackage{iftex}
    \ifxetex
      \xeCJKsetup{AutoFakeBold=true}
    \else
    \fi
    \ifluatex
      \defaultfontfeatures{AutoFakeBold=4}
    \else
    \fi
    }{\relax}
```
but this will use fake bold if or not there is a default bold fontface or `BoldFont` is given

### ElegantPaper & ElegantNote

when using `chinesefont=founder` this error will happen on lualatex:

```
Font \\LTJY3/FZShuSong-Z01(0)/m/n/10=[FZShuSong-Z01.otf]:mode=node;language=dflt;jfm=zh_CN/quanjiao;+tlig;-ss05; at 10pt not loadable: metric data not found or bad.
```

and I don't know why (and why no such error on ElegantBook).

**Comment by syvshc** [comment]
ElegantLaTeX doesn't have a plan to support lualatex. This issue will be closed as "not planned".
