### ISSUE TITLE
用户手册参考文献排序说明写的不好

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#233]
https://github.com/ElegantLaTeX/ElegantBook/blob/99eb12f4c44e11261dc1b69e62f2c182ef0898c8/elegantbook-cn.tex#L625-L630
这段容易理解为：如果设置了 `citestyle=gb7714-2015, bibstyle=gb7714-2015`，就**必须**要设置 `\ExecuteBibliographyOptions{sorting=gb7714-2015}` 才能正常排序。

实际上设置 `citestyle=gb7714-2015, bibstyle=gb7714-2015` 后，排序是按引用顺序列出的，如果添加了 `\ExecuteBibliographyOptions{sorting=gb7714-2015}` 反而排序会出问题，这里应该改成：
- 使用 `citestyle=gb7714-2015, bibstyle=gb7714-2015` 就不需要设置排序，默认就是按引用顺序排序
- 不使用 `citestyle=gb7714-2015, bibstyle=gb7714-2015` 的时候，想要对排序进行操作，可以用 `\ExecuteBibliographyOptions{sorting=name}`，其中 `name` 去 `texdoc biblatex`, sec 3.1.2.1 General 找

**Comment by EthanDeng** [comment]
你直接改到文档里面吧。
