### ISSUE TITLE
封面名人名言过长无法分行显示

### ISSUE THREAD

**Issue by jin-li** [ElegantLaTeX/ElegantBook#24]
如题。
另外，如果可能的话，最好可以将名人名言的作者换到下一行显示，类似这种效果：
![xGuq6](https://user-images.githubusercontent.com/26253144/57498586-5a823400-72aa-11e9-9955-91de0c8334a9.png)

**Comment by EthanDeng** [comment]
好的。虽然为了更加准确表达这个位置信息的含义，我们想把 `\equote` 改名为 `\extrainfo`，但是你提的建议也适用于新命令。

**Comment by EthanDeng** [comment]
> 如题。
> 另外，如果可能的话，最好可以将名人名言的作者换到下一行显示，类似这种效果：
> ![xGuq6](https://user-images.githubusercontent.com/26253144/57498586-5a823400-72aa-11e9-9955-91de0c8334a9.png)

新版本 3.08 已经更新，`\equote` 改为 `\extrainfo`，并且可以多行显示（居中）。
