### ISSUE TITLE
建议增加参考文献格式的选择

### ISSUE THREAD

**Issue by wangcs-1985** [ElegantLaTeX/ElegantBook#26]
首先非常感谢您们的付出，最近我在整理一些研究笔记，采用的是这个模板，但在使用过程中若用\bibliographystyle{plain}无法设置，导致系统出错。我查看了您们的代码，里面没有这个设置。若能加入这个格式选择，我们作为用户使用起来会有更多的选择。目前正文和参考文献中的显示也不符合国人习惯，最好加上序号，正文中引用也用序号。再次感谢！

**Comment by EthanDeng** [comment]
首先，`目前正文和参考文献中的显示也不符合国人习惯`，这个说法我觉得太武断了。经济学领域 author-year 是绝对统治级别的参考文献格式，不管是国内还是国外的期刊，甚至说基本上全是。这种文献格式的好处是，方便读者在阅读时非常清楚知道是哪个作者哪一年的文章。对于熟悉文献的读者来说非常好的。这也是我为什么把 author-year 格式作为默认的参考文献格式。对于中文模式下，文献标准用的是 GB/T 7714-2015，与 plain 是有冲突的。我自己觉得 author-year 更适合文献阅读，虽然这么说，但下个版本我们会加入数字编号这个选项。

**Comment by wangcs-1985** [comment]
谢谢！期待着更新！ 王常盛 邮箱wangcs.lamp@gmail.com 签名由 网易邮箱大师 定制 在2019年05月11日 08:39，Dongsheng Deng 写道： 首先，目前正文和参考文献中的显示也不符合国人习惯，这个说法我觉得太武断了。经济学领域 author-year 是绝对统治级别的参考文献格式，不管是国内还是国外的期刊，甚至说基本上全是。这种文献格式的好处是，方便读者在阅读时非常清楚知道是哪个作者哪一年的文章。对于熟悉文献的读者来说非常好的。这也是我为什么把 author-year 格式作为默认的参考文献格式。对于中文模式下，文献标准用的是 GB/T 7714-2015，与 plain 是有冲突的。我自己觉得 author-year 更适合文献阅读，虽然这么说，但下个版本我们会加入数字编号这个选项。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by EthanDeng** [comment]
> 谢谢！期待着更新！ 王常盛 邮箱wangcs.lamp@gmail.com 签名由 网易邮箱大师 定制 在2019年05月11日 08:39，Dongsheng Deng 写道： 首先，目前正文和参考文献中的显示也不符合国人习惯，这个说法我觉得太武断了。经济学领域 author-year 是绝对统治级别的参考文献格式，不管是国内还是国外的期刊，甚至说基本上全是。这种文献格式的好处是，方便读者在阅读时非常清楚知道是哪个作者哪一年的文章。对于熟悉文献的读者来说非常好的。这也是我为什么把 author-year 格式作为默认的参考文献格式。对于中文模式下，文献标准用的是 GB/T 7714-2015，与 plain 是有冲突的。我自己觉得 author-year 更适合文献阅读，虽然这么说，但下个版本我们会加入数字编号这个选项。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

3.08 版本已经增加 numbers 选项！

**Comment by wangcs-1985** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    谢谢您，已经更新，感觉非常好，我用它来做科研文献笔记，更容易将一些关键文献记录并查找。感谢您们的付出，我会一直关注！
        
    
        
            
        
    
    
        
        

        
    

    在2019年5月29日 17:30，Dongsheng Deng<notifications@github.com> 写道： 


Closed #26.
