### ISSUE TITLE
ElegantBookdown: 用 bookdown 包装 ElegantBook

### ISSUE THREAD

**Issue by XiangyunHuang** [ElegantLaTeX/ElegantBook#28]
我创建了一个 bookdown 项目 --- [ElegantBookdown](https://github.com/XiangyunHuang/ElegantBookdown) 实现在 R Markdown 环境下写书，LaTeX 主体模版 ElegantBook 不动，基于 Pandoc 定制了一些 block 实现 LaTeX 模版中的功能，后续会继续补充 LaTeX 书籍模版中的各种定理类、注释类。目前，项目的效果见网址 <https://bookdown.org/xiangyun/ElegantBookdown/> PDF 格式可通过左上角下载按钮下载

**Comment by EthanDeng** [comment]
很不错啊！还原度很高！赞！原来有一个网友提过这个事情，但是我对 bookdown、pandoc 不太熟悉....感觉觉得有点麻烦，没去尝试过。

**Comment by EthanDeng** [comment]
你做好之后，你这个项目怎么定位呢？你自己有什么想法？你会长期维护这个项目吗？你有想法加入我们？我们还没遇到过这种情况....

**Comment by XiangyunHuang** [comment]
1. 我想对 ElegantBookdown 项目使用协议 CC-BY-4.0，但是对 LaTeX 项目的 LaTeX Project Public License v1.3c 协议不熟悉，我想知道这会不会违反你们项目的协议？就我的这个项目来说，LaTeX 部分已经隐藏的比较深了，事实上就我的水平和时间精力，无力去修改和再维护ElegantBook 的文类，所以当前和今后不会在我的项目中修改 ElegantBook。

1. ElegantBookdown 项目的目标是使用者写书的时候，不需要去学习 LaTeX，但是使用者应当学习 Markdown 的基本语法。目前 ElegantBookdown 项目算是完成一个轮廓，未完成的部分在 [TODO](https://github.com/XiangyunHuang/ElegantBookdown#to-do)  我注意到 ElegantBook 项目还在快速迭代中，我想等比较稳定之后再完善我的 ElegantBookdown 项目。

1. ElegantBookdown 项目基于 bookdown 来写书，使用指南与ElegantBook基本上不一样，ElegantBook 基于 LaTeX，ElegantBookdown 基于 [R Markdown](https://rmarkdown.rstudio.com/)，所以后续完成 LaTeX 模版 ElegantBook 的全面复现后，会将书籍模版的使用指南替换为 [Pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown) 和 [bookdown](https://bookdown.org/yihui/bookdown/)，但会在致谢部分说明使用到 ElegantBook 文类生成 PDF 格式书籍

1. 作为 ElegantBookdown 项目使用者，不需要关心 ElegantBookdown 项目下的 CSS 和 latex 两个目录，只需用自己的内容替换 R Markdown 文件的内容，如果使用者不需要动态生成图、表等统计计算和统计图形的内容，可以不使用 R Markdown 中的各种编程语言的代码块，此时把 R Markdown 文件当作普通的 Markdown 文件就好。

1. 作为 ElegantBookdown 项目开发者，主要便是定制目录 CSS 和 latex 下的内容。这其中会有一半的内容是在修改 [Pandoc's LaTeX](https://github.com/jgm/pandoc-templates/blob/master/default.latex) 、写自定义的 Pandoc filters 和 [bookdown's block](https://bookdown.org/yihui/bookdown/custom-blocks.html) 来适应 ElegantBook 文类，另一半的内容是自定义 CSS 样式。

1. 我看到 ElegantBook 项目后，觉得书籍模版做的特别漂亮，早些时候，特意拿到统计之都论坛上[讨论](https://d.cosx.org/d/420628)，希望有更多的人参与进来，发挥各自的特长，利用开源的力量回馈开源社区。

1. 我会继续维护 ElegantBookdown 项目，在维护过程中希望能请教 ElegantBook 文类的细节，我愿意加入 ElegantLaTeX，我也可以把项目转移到  ElegantLaTeX 下开发。

**Comment by EthanDeng** [comment]
你好，谢谢你这么详细的说明！

1. 你说的协议应该是更加通用的开源协议，LaTeX 这边的通用协议需要注意三个事项就行了

![QQ截图20190529133409](https://user-images.githubusercontent.com/8111364/58532159-35cd0c80-8217-11e9-98ee-62ffd812a7da.png)

基于你这个项目其实不是 ElegantBook 的演化模板，只是在其他领域还原 ElegantBook 的效果，我个人觉得你做到下面几个就行了

+ **说明你项目创意**来源于 ElegantBook；
+ **说明与我们模板中的差异**，LaTeX 的部分效果可能不太好做，建议进行修改；
+ 说明你项目的目标（这个你肯定会说，方便 Markdown/bookdown 用户）；
+ **提供我们模板的信息**，包括使用的协议，获取方式（Github，CTAN）。

2. ElegantBookdown 这个想法非常好，我自己平时也用 Markdown，但是我们应该无暇去参与这部分内容。ElegantBook 目前来说，会根据用户的反馈，将会处于更新状态，至于你说的等我们模板稳定之后，我觉得可以我没法给你准确的时间。我的建议是以最新版 3.08 版为准。之前其实就两次大改动，第一次是 2.x 到 3.x 的大版本更新，然后第二次是 3.06 的封面更新。目前来说，3.08 版本除去新增的 elegantpar（旁注）属于测试，其他都是正式版内容。

3. 嗯，你们的说明文档肯定是怎么用 Markdown，毕竟你的语言不是 LaTeX。

4. 这个是 ElegantBookdown 的内容。

5. 你为了匹配与我们模板的效果，我们可以提供 LaTeX 方面的解释。

6. 我看了下帖子，Yihui Xie 也参与了讨论，看完之后还是感觉挺荣幸的，我自己也是 R 用户，虽然平时不怎么上统计之都！谢谢你们对模板的喜爱，看到一个回复是”确实漂亮，不过距离惊艳还差那么一丢丢，我觉得。不知道为什么。“，如果他有具体建议，请务必让他联系我们，谢谢！！！

7. 你维护 ElegantBookdown 项目的时候，有 LaTeX 的问题可以联系我们，我们非常支持你的这个项目！做好之后，如果你们希望，我们可以帮忙在 LaTeX 圈子里宣传下！

至于邀请你加入 ElegantLaTeX，看到你的回复之后，我们觉得还是慎重点处理。我认真想了之后，你们项目独立于 ElegantLaTeX 更好一些，方便你开发，维护。而且如果你是选定版本之后进行定制，其实也不太涉及与我们模板的互动。所以总结下来就是，其实没太大必要，独立开发会更加自由！你需要了解 LaTeX 细节，我们可以告知。当然，最重要的还是尊重你的意愿！

**Comment by pzhaonet** [comment]
@EthanDeng 你好！我就是那个说“确实漂亮，距离惊艳还差一点”的。 @XiangyunHuang 让我来说说具体建议。客观来讲，这个模板已经比我见过的中文模板强太多了，非常感谢你们的开发和分享。作为一个 LaTeX 中文用户，能遇见这样的模板是十分幸运的。

我说上面那句话的时候，后面还有一句，就是“不知道为什么”，因为这实在是一种不太稳定的主观感受。细想起来，这可能并非模板哪里有不足，而是我的个人感受上觉得 LaTeX 的英文模板普遍比中文模板更好看一些——可能是对后者爱之太深吧。具体建议我提不出来，只盼这个模板得以长久的维护和发展，并早日移植到 bookdown 上面，让更多的人受惠。

此外，前些日子，有位 bookdown 的用户向我推荐了你们开发的 ElegantPaper 模板，并针对 macOS 做了字体优化，通过邮件把修改稿发给了我，建议我加到 [bookdownplus ](https://github.com/pzhaonet/bookdownplus) 包里——这个包是我开发和维护的一个 bookdown 的模板库。经过一番努力， ElegantPaper 的 bookdown 版已经可以通过 bookdownplus 安装使用了：

```
require(bookdownplus)
bookdownplus('elegantpaper_zh', to = 'ele')
```

由于是测试和自己使用，我没有考虑软件许可的问题——主要是我外行，对这些协议的具体使用不太懂。刚好 @XiangyunHuang 提到了这一点，所以我想请教一下，我应该如何在 bookdownplus 包里说明你们的贡献。

bookdownplus 这个包目前收录了 35 个 LaTeX 模板，ElegantPaper 是其中一个。目前的 .cls 文件里保留了原作者的说明文字。除此之外，我早先写了一本 bookdownplus 的模板说明书，打算在[相应章节]((https://bookdown.org/baydap/bookdownplus/#giants__shoulders)说明各个模板的来源，不知这样是否妥当？

**Comment by EthanDeng** [comment]
好的，谢谢你的建议！这个模板也有些年头了，也在不断完善的过程中，未来应该会一直维护下去，并且根据用户需求会有不断的更新。

如果我没理解错的话，你们用的实际是 cls，而不是用其他诸如 css 或者网页 block 去还原我们模板的效果是吧。如果是这样，你们这种是属于“用户”（非 LaTeX 用户），不涉及再次开发，也不是仿制效果。我认为声明模板的来源（github 地址）和原模板的协议规范就行了，如果对 cls 有改动，最好说明改动，其他的我觉得没啥。

**Comment by XiangyunHuang** [comment]
ElegantBookdown 项目在完成 LaTeX 输出后，会用 CSS 制作一套样式主题，这也是我最期待的部分，由于直接搬迁 ElegantBook 模版中的样式到网页中来可能不太适合，我考虑参考其它网页书籍的样式定制。

对，我们都是 ElegantBook 模版的用户，不修改不对它二次开发，只因为它长得漂亮我们想把它迁移到基于 Markdown 编辑和排版的平台上来
