### ISSUE TITLE
Mac编译运行报错

### ISSUE THREAD

**Issue by createwindow** [ElegantLaTeX/ElegantBook#3]
kpathsea: Running mktextfm SimSun/OT

/usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT. /usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/special.map?

mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT

This is METAFONT, Version 2.7182818 (TeX Live 2017) (preloaded base=mf)

kpathsea: Running mktexmf OT

! I can't find file `OT'. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Please type another input file name ! Emergency stop. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Transcript written on mfput.log.

grep: OT.log: No such file or directory

mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT' failed to make OT.tfm. kpathsea: Appending font creation commands to missfont.log. kpathsea: Running mktextfm SimSun/OT

/usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT. /usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/special.map?

mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT

This is METAFONT, Version 2.7182818 (TeX Live 2017) (preloaded base=mf)

kpathsea: Running mktexmf OT

! I can't find file `OT'. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Please type another input file name ! Emergency stop. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Transcript written on mfput.log.

grep: OT.log: No such file or directory

mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT' failed to make OT.tfm.

kpathsea: Running mktextfm KaiTi/OT

/usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT. /usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/special.map?

mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT

This is METAFONT, Version 2.7182818 (TeX Live 2017) (preloaded base=mf)

kpathsea: Running mktexmf OT

! I can't find file `OT'. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Please type another input file name ! Emergency stop. <*> \mode:=ljfour; mag:=1; nonstopmode; input OT Transcript written on mfput.log.

grep: OT.log: No such file or directory

mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input OT' failed to make OT.tfm. kpathsea: Running mktextfm KaiTi/B/OT

/usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Could not map source abbreviation O for OT. /usr/local/texlive/2017/texmf-dist/web2c/mktexnam: Need to update /usr/local/texlive/2017/texmf-dist/fonts/map/fontname/special.map?

Error: Command crashed: xelatex -synctex=1 -interaction=nonstopmode "elegantbook-en".tex

Process exited with error(s)

**Comment by EthanDeng** [comment]
对 Mac 系统，你需要修改 cls 里面的字体设置。包括 Times New Roman，SimSun, KaiTi, SimHei, Microsoft YaHei 等字体。字体设置部分在 48 行-80 行，你需要根据自己系统的字体替换掉。
