### ISSUE TITLE
目录页眉的一个小Bug

### ISSUE THREAD

**Issue by On1gub** [ElegantLaTeX/ElegantBook#32]
目录页的页眉有个小Bug，页码不能对齐边沿，见下图

![Snipaste_2019-06-09_16-24-33](https://user-images.githubusercontent.com/43373866/59156820-229e2480-8ad4-11e9-96bc-42f7d895d125.png)

可以在页眉设置处添加以下代码解决

```LaTeX
\fancyheadoffset[LO,LE]{0cm}
```

**Comment by muzimuzhi** [comment]
使用目前最新提交 https://github.com/ElegantLaTeX/ElegantBook/commit/ed204e06ed3c7c0dcaf935ec38413f936d133810 
 版本下的模板和示例文档，为 `elegantbook-cn.tex` 文件增加章节以获得跨页目录，编译后得到的 PDF 无法复现你的问题。

建议提供一个完整的、可复现问题的例子。

**Comment by EthanDeng** [comment]
> 目录页的页眉有个小Bug，页码不能对齐边沿，见下图
> 
> ![Snipaste_2019-06-09_16-24-33](https://user-images.githubusercontent.com/43373866/59156820-229e2480-8ad4-11e9-96bc-42f7d895d125.png)
> 
> 可以在页眉设置处添加以下代码解决
> 
> ```
> \fancyheadoffset[LO,LE]{0cm}
> ```

这是 Book 还是 Note？看这颜色感觉是 Note，但 Note 是没设置目录的，Book 我无法重现你的问题。

**Comment by On1gub** [comment]
我找到问题所在了。

我为了显示更多内容，将目录页的页边距减小了，在document中将添加目录的代码改为了

‘’‘LaTeX
\newgeometry{left=2cm,right=2cm}
\tableofcontents
\restoregeometry
```

**Comment by lisayang2019** [comment]
我建议能在目录部分和对应章节之间建立超链接。

这个问题可能和这个issue无关，而且我看到之前的closed issue里有相同的建议（https://github.com/ElegantLaTeX/ElegantBook/issues/29），但是我尝试了里面的方法，没有成功实现，加上那个issue已经关闭，所以不想新增issue，就在这里留言了。希望这样okay。

**Comment by EthanDeng** [comment]
> 我建议能在目录部分和对应章节之间建立超链接。
> 
> 这个问题可能和这个issue无关，而且我看到之前的closed issues里有相同的建议#29，但是我尝试了里面的方法，没有成功实现，加上那个issue已经关闭，所以不想新增issue，就在这里留言了。希望这样okay。

如果是单向链接，你可以在 cls 里面修改 hyperref 的选项设置，将 `linktoc=all` 加进去。如果是双向链接，之前的[问题](https://github.com/ElegantLaTeX/ElegantBook/issues/29) 已经提供了一种方法，但是我们不会把这个作为默认，也不提倡。
