### ISSUE TITLE
若注释掉subtitle，在编译时则会出现“there is no line to end”的错误

### ISSUE THREAD

**Issue by xyh-cosmo** [ElegantLaTeX/ElegantBook#33]
其实忽略这个错误并不影响pdf的生成，只是每次都出现，比较烦人。。。
是否可以在cls文件里增加一个条件判断？

**Comment by EthanDeng** [comment]
好的，谢谢建议！

**Comment by muzimuzhi** [comment]
相对简单的修改方式，是在行 721 的 `\the\subtitle` 之前，加一个 `\mbox{}`。
https://github.com/ElegantLaTeX/ElegantBook/blob/ae0d420e4954f2cc35cba577384496ab86573758/elegantbook.cls#L720-L730

**Comment by EthanDeng** [comment]
#46
