### ISSUE TITLE
verbatim 跨页报错

### ISSUE THREAD

**Issue by annProg** [ElegantLaTeX/ElegantBook#34]
报错信息
```
! Package tikz Error: Sorry, some package has redefined the meaning of the math
-mode dollar sign. This is incompatible with tikz and its calc library and migh
t cause unrecoverable errors.

See the tikz package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.58 \end{Highlighting}
```

## MWE
```latex
\documentclass[cn]{elegantbook}
\usepackage{fancyvrb}
\begin{document}
\vspace*{21cm}
\begin{verbatim}
a
b
c
d
e
f
g
h
i
\end{verbatim}
\end{document}
```

Ref: https://github.com/annProg/PanBook/issues/27

**Comment by annProg** [comment]
参考 [stackexchange](https://tex.stackexchange.com/questions/352297/tikz-error-some-package-has-redefined-the-meaning-of-the-math-mode-dollar-sign)，使用`\savebox`，可以编译通过了，`\nointerlineskip`会报错，不知道为什么
```diff
@@ -196,7 +196,7 @@

 \newcommand{\base}[2]{%
-       \nointerlineskip \vspace{0.1\baselineskip}\hspace{\fill}
+       \vspace{0.1\baselineskip}\hspace{\fill}
        {\color{#1}
                \resizebox{0.3\linewidth}{1.5ex}
                {{%
@@ -206,9 +206,10 @@
                                        \path (C) to [ornament=#2] (D);
                                        \end{tikzpicture}}}}}%
        \hspace{\fill}
-       \par\nointerlineskip \vspace{0.1\baselineskip}
+       \par \vspace{0.1\baselineskip}
 }

+
 % ----- Title Style -----
 \ifdefstring{\ELEGANT@titlestyle}{hang}{\def\style{hang}}{\relax}
 \ifdefstring{\ELEGANT@titlestyle}{display}{\def\style{display}}{\relax}
@@ -627,6 +628,8 @@
        }
 }{\relax}

+\newsavebox\elegantfoot
+\savebox\elegantfoot{\base{structurecolor}{88}}

 %页眉页脚
 \RequirePackage{fancyhdr}
@@ -642,7 +645,7 @@
 \fancyhead[L]{\color{structurecolor}\ifdefstring{\ELEGANT@lang}{en}{\itshape}{\kaishu}\rightmark}
 \fi

-\fancyfoot[c]{\base{structurecolor}{88}}
+\fancyfoot[c]{\usebox{\elegantfoot}}
 \renewcommand{\headrule}{\color{structurecolor}\hrule width\textwidth}
 \pagestyle{fancy}
 \renewcommand{\headrulewidth}{1pt}
```

**Comment by EthanDeng** [comment]
ElegantLaTeX 这几个模板都不用 verbatim 这个自带的环境，用的都是 [listings](http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf) 包带的 lstlisting 环境

**Comment by annProg** [comment]
> ElegantLaTeX 这几个模板都不用 verbatim 这个自带的环境，用的都是 [listings](http://texdoc.net/texmf-dist/doc/latex/listings/listings.pdf) 包带的 lstlisting 环境。

感觉代码高亮应该交给用户来决定。这个问题用`minted`也存在。可以考虑修复一下

**Comment by EthanDeng** [comment]
你说的这几个环境都是并列的关系，你说的让用户选择是让他们选择用 `verbatim` 或者 `lstlisting` 或者 `minted` 么？

这个建议我觉得并不好，原因在于，模板通用的自定义并不是我们提倡用户去做的，就像字体自定义一样，凡是涉及自定义就会招来很多系统，编译选择，编译选项的问题。我们模板目前来说最重要的是保证易用性，其次是美观。

就目前所涉及的高亮方式：
+ 自带的 `verbatim` 高亮并不好，很多人不喜欢；
+ `lstlisting` 环境，可定制化程度高，兼容性高
+ `minted` 环境，定制化门槛高，编译麻烦，需要开启 `-shell-escape` 选项。

实际上就只有两个比较好的选项，一个是 `lstlisting`，一个是 `minted`，但是用过 minted 的人就知道其实加入 `-shell-escape` 挺麻烦的。对于不同的编辑器，这又会增加一个复杂的说明过程。对于老手来说，这或许不是很难，但是对于新手就是灾难。所以我们暂且不会考虑加入这个。

至于 `lstlisting`，我们后面会完善各个语言的设置，4 月份有好几个群友有意向去完善不同语言的关键字和其他设置。而我在目前的设置下，并没有出现你所说的跨页报错问题。

![QQ截图20190622194748](https://user-images.githubusercontent.com/8111364/59963810-f7cbbb80-952a-11e9-9ed9-4065d124db9c.jpg)

**Comment by annProg** [comment]
`listings`没有此问题。
我的意思是，模板应该支持用户选择不同的代码高亮方式。模板定制`listings`作为默认的选择，但是如果需要用`verbatim`或者`minted`，也应该能编译通过。

比如，`listings`支持的语言比较少，比如`Markdown`就不支持。这种情况下，既想用`minted`高亮`Markdown`，又想用`elegantbook`，就会陷入两难的选择。

**Comment by dekoza** [comment]
I have problems with `elegantbook` and `minted` clashing. I can somewhat understand what you say using Google Translator but the question is - will `elegantbook` support `minted` anytime soon?

**Comment by annProg** [comment]
> I have problems with `elegantbook` and `minted` clashing. I can somewhat understand what you say using Google Translator but the question is - will `elegantbook` support `minted` anytime soon?

My solution now is to patch it myself. see https://github.com/ElegantLaTeX/ElegantBook/issues/34#issuecomment-504651999

This is full `cls` file with my patch [elegantbook.cls v3.08](https://github.com/annProg/PanBook/blob/master/styles/book/elegantbook/elegantbook.cls)

**Comment by dekoza** [comment]
Thank you @annProg but this still does not work for me. I tried to make a minimal example but faild. Nevertheless I figured that it helps to insert `\,` between some environments.

**Comment by EthanDeng** [comment]
I will try to accommodate the support for minted.

**Comment by muzimuzhi** [comment]
你们把事情搞复杂了。

 - 问题核心，是目前的实现，与 `verbatim` 和 `minted` 宏包不兼容。
 - 不兼容的源头，是 `\base` 命令的定义。
 - 不兼容的解决，是去掉 `\base` 定义里的多余分组。
```diff
diff --git a/elegantbook.cls b/elegantbook.cls
index 6868ca5..50335c8 100644
--- a/elegantbook.cls
+++ b/elegantbook.cls
@@ -203,12 +203,11 @@
        \nointerlineskip \vspace{0.1\baselineskip}\hspace{\fill}
        {\color{#1}
                \resizebox{0.3\linewidth}{1.5ex}
-               {{%
                                {\begin{tikzpicture}
                                        \node  (C) at (0,0) {};
                                        \node (D) at (4,0) {};
                                        \path (C) to [ornament=#2] (D);
-                                       \end{tikzpicture}}}}}%
+                                       \end{tikzpicture}}}%
        \hspace{\fill}
        \par\nointerlineskip \vspace{0.1\baselineskip}
 }
```

附带一提，`\base` 的定义还可以更简化。

**Comment by muzimuzhi** [comment]
> @annProg 感觉代码高亮应该交给用户来决定。https://github.com/ElegantLaTeX/ElegantBook/issues/34#issuecomment-504658575

> @EthanDeng 这个建议我觉得并不好，原因在于，模板通用的自定义并不是我们提倡用户去做的，就像字体自定义一样，凡是涉及自定义就会招来很多系统，编译选择，编译选项的问题。我们模板目前来说最重要的是保证易用性，其次是美观。https://github.com/ElegantLaTeX/ElegantBook/issues/34#issuecomment-504661190

一些个人意见
 - 模板确实应该提供「开箱即用」的整套配置，而不是完全交给用户来选择。
 - 在提供整套配置的同时，模板也应保持一定的扩展性和定制性。
 - 第一类，如果是天生冲突的宏包，模板用了其中一个，用户想换用与之冲突的，用户有责任自行找到解决方案。
 - 第二类，如果是天生不冲突的包，而因为模板实现有问题，新增了冲突关系，模板维护者有责任提供修复或绕过的办法。
 - 现在这个问题，属于第二类，所以模板有责任修复。

**Comment by muzimuzhi** [comment]
花了一些时间，做了一些调查。

### 短结论：

 - 这不完全是模板的问题，与 latex2e kernel 的处理也有关。
 - 修复的方式，我更推荐在页脚里手动恢复 $ 的 catcode，把
https://github.com/ElegantLaTeX/ElegantBook/blob/64757b063e922516e44f9d7fc9e1190dec40027b/elegantbook.cls#L662
    修改为
    ```latex
    \fancyfoot[c]{\catcode`\$=3\relax\base{structurecolor}{88}}
    ```
    即可。使用 `\savebox`，也能解决本模板里的问题。

### 长解释：
大致原因是，
1. latex2e kernel 目前的实现是，如果在页面中修改了符号的 catcode，且修改没有在当前页面结束前恢复，则这些修改也会影响当前页面页眉页脚里的 catcode（与 output routine 有关，见 `texdoc source2e`, sec. 65，623 行开始）
2. `verbatim` 环境、`verbatim` 和 `fancyvrb`（`minted` 依赖它） 宏包提供的代码抄录环境，都会修改 ``\catcode`\$=12`` （other）。这样，抄录环境一旦跨页，就会影响页眉页脚的 catcode。因为实现方式不同，模板中使用的 `listings` 宏包恰巧是个例外。这是与模板的第一处联系。
3. 因为符号的 catcode 在 tex 的 input processor 阶段就确定了，所以一般情况下，这种 catcode 的修改范围溢出不会带来什么问题，哪怕是在页眉页脚里写数学公式（参考 TeX-SX 的[这则问答](https://tex.stackexchange.com/a/498891)）。
4. 但是，tikz 是个例外。
    * 首先，tikz 会在解析坐标时判断 $ 的 catcode，如果不为 3（math shift），就报错。这就是 issue 里提到的报错。这个报错其实只是提醒，并不影响 tikz 的功能，把引起报错的命令 `\tikz@ensure@dollar@catcode` 设为空就能避免。
    * 其次，如果使用了 tikz library calc 提供的坐标运算功能，则如果 $ 的 catcode 不为 3，tikz 就无法正确绘制图形。
5. 到这一步，才出现与模板的第二处联系。模板在页脚中插了 tikzpicture，在其内部又使用了 `pgfornament-han` 宏包预定义的（同样由 tikz 绘制的）纹样图形，这才会（在合适条件下）引起报错。

**Comment by muzimuzhi** [comment]
``\catcode`\$=3\relax`` 已由提交 https://github.com/ElegantLaTeX/ElegantBook/commit/b3d038fc3e0c1b12f7b833bda4d2434e113abeec 加入，当前 issue 可关闭。
