### ISSUE TITLE
heading does not match contents at the end of the chapter (页眉）

### ISSUE THREAD

**Issue by zhz200408** [ElegantLaTeX/ElegantBook#35]
The chapter heading seems to follow the section.  When I got to the end 
of the chapter, say, 第1章 习题，the heading remained to be the last 
section, which didn't match the content of the page.  (see the 
attached.)  I'd appreciate it greatly if there would be a command to 
switch off the heading or simply to the chapter title.
[heading.pdf](https://github.com/ElegantLaTeX/ElegantBook/files/3318474/heading.pdf)

**Comment by muzimuzhi** [comment]
The commit https://github.com/muzimuzhi/ElegantBook/commit/2d73515ddf54de5e1229f445d8d3e779cb0876c9 provides a possible solution that let `problemset` environment update the header. With this modification, left header of the only page of your file `heading.pdf` would be "1 习题". 

You can change the header to any desired text by changing both arguments of `\markboth`.

**Comment by muzimuzhi** [comment]
> I'd appreciate it greatly if there would be a command to switch off the heading or simply to the chapter title.

 - In `oneside` mode (default), every left header is the latest section title in the corresponding page.
 - If you add `twoside` to the class option (i.e. `\documentclass[..., twoside]{elegantbook}`), then right header of odd pages will show chapter title, and left header of even pages will show section title.

Maybe `twoside` is what you want.
