### ISSUE TITLE
定义环境没有标题和标签时结果有问题

### ISSUE THREAD

**Issue by views63** [ElegantLaTeX/ElegantBook#36]
最小例子
``` latex
\documentclass[cn,11pt,cyan]{elegantbook}
\begin{document}
\begin{definition}
测试
\end{definition}
\end{document}
```
结果
<img width="216" alt="20190625022156" src="https://user-images.githubusercontent.com/175116/60042373-28a91d80-96f0-11e9-940e-470f7c6a6aca.png">
期待结果
<img width="257" alt="20190625022349" src="https://user-images.githubusercontent.com/175116/60042447-54c49e80-96f0-11e9-936c-83fbad5e950d.png">
目前只能使用如下代码实现
``` latex
\documentclass[cn,11pt,cyan]{elegantbook}
\begin{document}
\begin{definition}{ }{}
测试
\end{definition}
\end{document}
```
修改 `elegantbook.cls` 中的 `\newenvironment{definition}[2]` 为
```
\newenvironment{definition}[2]
  {\ifstrempty{#1}{}{\edefinition[#1]}\ifstrempty{#2}{}{\label{def:#2}}}
  {\endedefinition}
```
仍需要使用 `\begin{definition}{}{}` 才能达到效果。期望能直接使用 `\begin{definition}` 达到期望的效果。

**Comment by EthanDeng** [comment]
由于定理类环境都用了 tcolorbox 宏包定理设置，所以写法是 `\begin{theorem}{}{}` 这样。

**Comment by views63** [comment]
> 
> 
> 由于定理类环境都用了 tcolorbox 宏包定理设置，所以写法是 `\begin{theorem}{}{}` 这样。

如果不修改 `\newenvironment{definition}[2]` 那段， 用`\begin{theorem}{}{}` 编译时会报错的，需要在第一对 `{}` 中间添加空格。

**Comment by muzimuzhi** [comment]
> 如果不修改 `\newenvironment{definition}[2]` 那段， 用`\begin{theorem}{}{}` 编译时会报错的，需要在第一对 `{}` 中间添加空格。

 * 具体会报什么错？
 * 如果确认会报错，能否新开一个 issue，然后提供能复现错误的最小例子？

使用 elegantbook v3.08 编译下面的例子，我没有得到报错
```latex
\documentclass[lang=cn]{elegantbook}
\begin{document}
\begin{definition}{}{}
content
\end{definition}
\end{document}
```

**Comment by views63** [comment]
> 
> 
> > 如果不修改 `\newenvironment{definition}[2]` 那段， 用`\begin{theorem}{}{}` 编译时会报错的，需要在第一对 `{}` 中间添加空格。
> 
>     * 具体会报什么错？
> 
>     * 如果确认会报错，能否新开一个 issue，然后提供能复现错误的最小例子？
> 
> 
> 使用 elegantbook v3.08 编译下面的例子，我没有得到报错
> 
> ```
> \documentclass[lang=cn]{elegantbook}
> \begin{document}
> \begin{definition}{}{}
> content
> \end{definition}
> \end{document}
> ```
我现在也没办法重现。记得当时是提示缺少参数。
```
\newenvironment{definition}[2]
  {\ifstrempty{#1}{\edefinition}{\edefinition[#1]}\ifstrempty{#2}{}{\label{def:#2}}}
  {\endedefinition}
```
\ifstrempty{#1} 进入了 \edefinition[#1]}\ifstrempty{#2}{}{\label{def:#2} 然后提示缺少参数了。
中间已经多次升级 texlive 不知道有没有关系。现在确实无法重现了
