### ISSUE TITLE
建议：单双页使用不同页边距

### ISSUE THREAD

**Issue by jin-li** [ElegantLaTeX/ElegantBook#37]
考虑到书籍在装订时方便，对于单双页来讲，左侧和右侧的页边距一般是不同的。简单来讲，单页装订侧在左，双页装订侧在右，因此单页左侧页边距=双页右侧页边距>单页右侧页边距=双页左侧页边距。为了方便装订，希望作者能将此问题列入考虑，单双页设置不同的页边距。

**Comment by EthanDeng** [comment]
你在 `\documentclass` 这里加上一个 `twoside` 选项试下。

**Comment by jin-li** [comment]
啊，看来已经有这个功能了，谢谢 ！ @

> 你在 `\documentclass` 这里加上一个 `twoside` 选项试下。
