### ISSUE TITLE
Elegantbook doesn't work on MikTex!?

### ISSUE THREAD

**Issue by zhz200408** [ElegantLaTeX/ElegantBook#39]
I've been using elegantbook for more than a month and finished nearly two chapters.  I recently reinstalled MikTex, installed elegantbook package and others , reinstalled TexMaker, refreshed file names, setting etc, and the Chinese fonts.  But nothing worked.  The elegantbook-cn.tex and all my previous files, which worked fine, failed to generate pdf.  Evey time it generated : fatal error occurred.  I've been trying all kinds possibilities for two days, and still have no clue.  My files in English works fine.  I tested a Chinese file using XeLatex, it worked fine as well.  (I was using TeXmaker, pdflatex.)
Could anyone point out other possible problems so that I can move on?  Thanks a great deal!

**Comment by muzimuzhi** [comment]
- Which operating system do you use?
 - What information do you get before error "fatel error occurred"?
 - Have you tried compiling from the terminal?
 - Can you provide a sample "Chinese file" which re-produces your problem?
