### ISSUE TITLE
ElegantBook不能显示siunitx宏包的\angstrom命令

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#41]
2019/7/29下载的最新模板
MWE如下
`\documentclass[lang=cn,11pt]{elegantbook}

\usepackage{siunitx}

\title{Title}

\subtitle{Subtitle is here}

\author{Your Name}

\institute{XXX University}

\date{\today}

\version{1.00}

\extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}

\logo{logo.png}

\cover{cover.jpg}

\begin{document}

\maketitle

\mainmatter

\hypersetup{pageanchor=true}

\chapter{Example Chapter Title}

\si{\angstrom}

\end{document}`
PDF正文部分一片空白，已尝试在ctexart标准文档类使用\angstrom命令，正常。

**Comment by muzimuzhi** [comment]
是字体问题，在 log 文件里可以看到引擎的报错
```
Missing character: There is no Å in font ntx-Regular-tlf-ot1!
```

1. `elegantbook` 默认加载 `math=newtxmath` 文档类选项，这会加载 `newtxmath` 宏包，修改公式字体
2. `siunitx` 默认会把 `\si` 接受的参数在数学环境下排版
3. `newtxmath` 宏包使用的数学字体，缺少 `Å` 这个符号
4. 相应的报错是引擎（xelatex）提供的，编辑器一般不会从 log 里把引擎报错过滤出来并突出显示

一个解决方案：为 `siunitx` 使用单独的、包含字符较全的字体，例如增加以下配置
```latex
\newfontfamily\latinModern{Latin Modern Roman}
\sisetup{mode=text, text-rm=\latinModern}
```

**Comment by sikouhjw** [comment]
> 你的 mwe 可以精简为
> 
> ```
> \documentclass[lang=cn]{elegantbook}
> \usepackage{siunitx}
> 
> \begin{document}
> |\si{\angstrom}|
> \end{document}
> ```
> 
> 输出结果中，两个 `|` 中间没有其他内容。
> 
> 以下内容基于此精简 mwe。
> 
> 问题是字体缺字，在 log 文件里可以看到引擎的报错
> 
> ```
> Missing character: There is no Å in font ntx-Regular-tlf-ot1!
> ```
> 
> 1. `elegantbook` 默认加载 `math=newtxmath` 文档类选项，这会加载 `newtxmath` 宏包，修改公式字体。具体，公式字体使用的字族是 `\OT1/ntxtlf/m/n/10`，实际调用的字体文件是 `ntx-Regular-tlf-ot1.tfm`，位于 http://mirrors.ctan.org/fonts/newtx/tfm/ntx-Regular-tlf-ot1.tfm
> 2. `siunitx` 默认将 `\si` 接受的参数在数学模式下输出
> 3. `newtxmath` 宏包使用的数学字体，也就是 `ntx-Regular-tlf-ot1.tfm`，缺少 `Å` 这个符号
> 4. 编译时，引擎（xelatex）向 log 记录相应信息，但编辑器没有把这条信息从 log 里把过滤出来并突出显示
> 
> 一个解决方案：为 `siunitx` 使用单独的、包含字符较全的字体，例如增加以下配置
> 
> ```
> \newfontfamily\latinModern{Latin Modern Roman}
> \sisetup{mode=text, text-rm=\latinModern}
> ```
> 
> 另一个思路是，让 `\angstrom` 使用拼合的符号 `\AA`。可能需要修改 `siunitx` 相关内容，暂时搁置。

谢谢，问题解决了

**Comment by muzimuzhi** [comment]
为了了解问题的实质，我试了一些更一般的情况，暂时的结论是，可能和字体编码有关。

现有的方案，先凑合用着吧。
