### ISSUE TITLE
不能调用yhmath宏包

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#42]
MWE如下
`\documentclass[lang=cn]{elegantbook}
\usepackage{yhmath}
\begin{document}
1
\end{document}`
在标准文档类下是可以编译的，报错显示Symbol font 'yhlargesymbols' is not defined.

**Comment by muzimuzhi** [comment]
多行代码请以 markdown 里的 `code block` 进行标记。参考 https://guides.github.com/features/mastering-markdown/#examples 里的 `Code` 部分。

**Comment by muzimuzhi** [comment]
0. 报错要从第一条看起，你提供的报错信息，不是编译 mwe 生成的第一条报错。

实际有两个问题，影响了 `yhmath` 宏包的使用。

1. 第一个问题，即编译 mwe 产生的第一条报错，<BR>`! LaTeX Error: Command \widering already defined. ... `

    * 如果想让 `yhmath` 重定义 `\widering`，可以这么用
    ```latex
    \let\widering\undefined
    \usepackage{yhmath}
    ```
    * 如果不想让 `yhmath` 重定义该命令，可以这么用（`yhmath` 宏包选项 `nowidering` 的实现有 bug，别用）
    ```latex
    \let\oldwidering\widering
    \let\widering\undefined
    \usepackage{yhmath}
    \let\widering\oldwidering
    ```

2. 第二个问题，即编译 mwe 产生的第二条报错，<BR>`! LaTeX Error: Too many symbol fonts declared.`

    latex 至多能同时使用 16 个 symbol font，而 `elegantbook`（及其依赖的宏包）已经定义了 16 个，导致 `yhmath` 无法定义新的。

    查源码，`elegantbook` 定义了不必要的三个 symbol font。
    https://github.com/ElegantLaTeX/ElegantBook/blob/72e63e3f0c7114243b6d1444f36edec663c0fd55/elegantbook.cls#L115-L134

    * 不必要之一，是这三个 symbol font 的内容，latex2e 格式已经提供，可以直接使用而无需重复定义。截图见 `texdoc source2e`, sec. 41.1.1
    ![image](https://user-images.githubusercontent.com/6376638/62169373-9af9c700-b35a-11e9-9be6-44925aa9edc9.png)
    * 不必要之二，是新定义的 `CMletters` 和 `CMsymbols` 在模板中从未使用，是废代码。

    解决第二个问题需要修改 `elegantbook.cls` 文件，见提交 https://github.com/muzimuzhi/ElegantBook/commit/4118a1e4e5efaff0fb86548056196585ab88106e 。

3. 编译 mwe 产生的其他报错，包括你问题里提到的报错，在解决以上两个问题后，会随之消失。

**Comment by sikouhjw** [comment]
> 一个建议：
> 
> * 多行代码请以 markdown 里的 `code block` 进行标记。参考 [Mastering Markdown - GitHub Guides](https://guides.github.com/features/mastering-markdown/#examples) 里的 `Code` 部分。

好的，下次提问会注意的

**Comment by sikouhjw** [comment]
> 1. 报错要从第一条看起，你提供的报错信息，不是编译 mwe 生成的第一条报错。
> 
> 实际有两个问题，影响了 `yhmath` 宏包的使用。
> 
> 1. 第一个问题，即编译 mwe 产生的第一条报错，`! LaTeX Error: Command \widering already defined. ... `
>    
>    * 如果想让 `yhmath` 重定义 `\widering`，可以这么用
>    
>    ```
>    \let\widering\undefined
>    \usepackage{yhmath}
>    ```
>    
>    
>    
>    * 如果不想让 `yhmath` 重定义该命令，可以这么用（`yhmath` 宏包选项 `nowidering` 的实现有 bug，已在 [TeX-Live/yhmath@1a873fb](https://github.com/TeX-Live/yhmath/commit/1a873fbef42519b7eda132bff452617f9a9846a4) 里修复，包含该修复的新版本尚未发布，所以暂时别用）
>    
>    ```
>    \let\oldwidering\widering
>    \let\widering\undefined
>    \usepackage{yhmath}
>    \let\widering\oldwidering
>    ```
> 2. 第二个问题，即编译 mwe 产生的第二条报错，`! LaTeX Error: Too many symbol fonts declared.`
>    latex 至多能同时使用 16 个 symbol font，而 `elegantbook`（及其依赖的宏包）已经定义了 16 个，导致 `yhmath` 无法定义新的。
>    查源码，`elegantbook` 定义了不必要的三个 symbol font。
>    https://github.com/ElegantLaTeX/ElegantBook/blob/72e63e3f0c7114243b6d1444f36edec663c0fd55/elegantbook.cls#L115-L134
>    
>    
>    * 不必要之一，是这三个 symbol font 的内容，latex2e 格式已经提供，可以直接使用而无需重复定义。截图见 `texdoc source2e`, sec. 41.1.1
>      ![image](https://user-images.githubusercontent.com/6376638/62169373-9af9c700-b35a-11e9-9be6-44925aa9edc9.png)
>    * 不必要之二，是新定义的 `CMletters` 和 `CMsymbols` 在模板中从未使用，是废代码。
>    
>    解决第二个问题需要修改 `elegantbook.cls` 文件，见提交 [muzimuzhi@4118a1e](https://github.com/muzimuzhi/ElegantBook/commit/4118a1e4e5efaff0fb86548056196585ab88106e) 。
> 3. 编译 mwe 产生的其他报错，包括你问题里提到的报错，在解决以上两个问题后，会随之消失。

谢谢！问题解决了

**Comment by EthanDeng** [comment]
已经将 pr 提交到最新版中。

**Comment by EthanDeng** [comment]
已将上述

**Comment by EthanDeng** [comment]
newtxmath 改了这个字体，如果把这个定义注释掉之后，积分符号和求和符号又会变成 newtxmath 里面的符号了。

**Comment by muzimuzhi** [comment]
可以只去掉以下（在模板中没有用到的）两个？
```latex
 \DeclareSymbolFont{CMletters}     {OML}{cmm} {m}{it}% 
 \DeclareSymbolFont{CMsymbols}     {OMS}{cmsy}{m}{n}% 
```
这样也能腾出两个 symbol font 的「名额」。

------

xetex 实际支持 256 个数学字体（`texdoc xetex`, sec. 2.3）。可能是出于向前兼容的考虑，latex2e 仅支持 256 math alphabat，还没有支持 256 math symbol font（自 texlive 2015）。
相关提交见 https://github.com/latex3/latex2e/commit/812d4c46b11b43fc089873a75453eaddb183b77f 。
> 2015-03-18  David Carlisle  <latex-bugs@latex-project.org>
>
>	* ltfssdcl.dtx: Allow math alphabets in full range 0-255
>	Restrict symbol fonts 0-15 (no change with classic tex)


TeX-SX 上的信息
> An extension to more than 16 symbol fonts needs more extensive changes replacing all uses of `\mathchardef` `\mathaccent` `\radical` etc by `\U...` versions.
> David Carlisle Mar 12 '15
https://tex.stackexchange.com/questions/232560/the-restriction-of-16-math-fonts-of-tex#comment551071_232620

**Comment by EthanDeng** [comment]
嗯 我仅保留了 CMlargesymbols 的定义。
