### ISSUE TITLE
关于重新分配 \int 等数学命令使用的符号

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#44]
1. 当前，模板提供两种数学字体配置，`math = newtx | mtpro2`，默认为前者。
1. 当 `math=newtx` 时，会加载 `newtxmath` 包
1. `newtxmath` 会把很多符号定义为较 computer modern 稍粗的版本，
    > for those who do not like the integral in `txfonts`, an emboldened version of the Computer Modern integral is made available, matching the weight of the `txfonts` symbols
    > ref: `texdoc newtx`, sec. 1

    为了撤销这个修改，模板重新分配了四个常用数学命令（`\int, \oint, \sum, \prod`）使用的字体

https://github.com/ElegantLaTeX/ElegantBook/blob/b3d038fc3e0c1b12f7b833bda4d2434e113abeec/elegantbook.cls#L98-L113

在上述第 3 步中，存在一些风险
1. 有更多命令可以重定义，例如 `\iint` 等
```tex
\makeatletter
\ams@renewcommand{\iint}{\DOTSI\protect\MultiIntegral{2}}
\ams@renewcommand{\iiint}{\DOTSI\protect\MultiIntegral{3}}
\ams@renewcommand{\iiiint}{\DOTSI\protect\MultiIntegral{4}}
\renewcommand{\idotsint}{\DOTSI\protect\MultiIntegral{0}}
\def\intkern@{\mkern-6mu\mathchoice{\mkern-8mu}{\mkern-4mu}{}{}}
\makeatother
```

2. 因为 `newtxmath` 使用的字体中，提供了一些 computer modern 没有提供的数学符号，所以仍然存在一些命令（如 `\oiint` 等），一定无法重定义为 computer modern 风格。

    如果用户需要同时使用重定义过的 `\int` 和无法重定义的 `\oiint`，那么总是会遇到符号风格不一致的问题。 

3. 可能的解决方案：
    - `esint` 宏包
    - `stix` 或 `xits` 字体对应的宏包

    以上是与 pdflatex 兼容的方案。如果仅考虑 xelatex，可以考虑 `unicode-math` 配合 `latin modern math`（仍然不包括四五个 `newtx` 包括的、不常用的积分符号）, `stix` 或 `xits`。

**Comment by EthanDeng** [comment]
积分符号用 `estint` 宏包，然后 `\sum` 和 `\prod` 还是维持原先 CMlargesymbols 定义吧。
