### ISSUE TITLE
让 bm 宏包少声明一些数学字体

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#45]
`bm` 宏包会额外声明 4 个数学字体，这容易让「最多 16 个数学字体」的限额变得紧张。

根据文档 `texdoc bm`, sec. 2，通过使用 
```tex
\newcommand\bmmax{0}
\RequirePackage{bm}
```
可以让 `bm` 宏包不额外声明数学字体，代价是
 * 稍慢的运行速度
 * 无法加粗定界符

**Comment by EthanDeng** [comment]
已经添加。
