### ISSUE TITLE
US letter paper size

### ISSUE THREAD

**Issue by ustcfdm** [ElegantLaTeX/ElegantBook#47]
Could you provide support for US letter paper size? This size is 216 x 279 mm, which is different from A4 (210 x 297 mm).

**Comment by muzimuzhi** [comment]
Currently, you can set paper size to letter by `geometry`. 
```latex
\documentclass{elegantbook}
\geometry{letterpaper}
\begin{document}
abc
\end{document}
```
Note, this does not change margins (i.e., the width and height of text body, margins of text body relative to paper, etc.). But you can always set them through `\geometry`.

**Comment by ustcfdm** [comment]
Awesome, it works!
