### ISSUE TITLE
在Ubuntu1804中编译出错

### ISSUE THREAD

**Issue by ShaoDP** [ElegantLaTeX/ElegantBook#5]
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(/home/shao/Documents/MyOneDrive/OneDrive - hrbeu.edu.cn/projects/doc_latex/ElegantBook-master/elegantbook-cn.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
(./elegantbook.cls
Document Class: elegantbook 2019/02/24 v3.06 ElegantBook document class
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty) (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty) (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty) (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty)))) (/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty) (/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk12.clo)) (/usr/share/texlive/texmf-dist/tex/latex/tools/indentfirst.sty) (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty) (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty) (/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty (/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty (/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex) (/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3xdvipdfmx.def))) (/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty (/usr/share/texlive/texmf-dist/tex/latex/base/tuenc.def)) (/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg))) (/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xeCJK.sty (/usr/share/texlive/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty) (/usr/share/texlive/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty) (/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xunicode-addon.sty (/usr/share/texlive/texmf-dist/tex/xelatex/xunicode/xunicode.sty (/usr/share/texmf/tex/latex/tipa/t3enc.def) (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty) (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/xetex.def))))) (/usr/share/texlive/texmf-dist/tex/xelatex/xunicode/xunicode.sty
*** Reloading Xunicode for encoding 'TU' ***
) (/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xunicode-extra.def) (/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))

! LaTeX Error: File `newtxmath.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
./elegantbook.cls:66: Emergency stop.
<read *> 
         
l.66 ^^I\setCJKfamilyfont
                         {zhsong}{SimSun}^^M
No pages of output.
Transcript written on elegantbook-cn.log.

查看了Tex Live的目录，里面有newtxmath.sty文件，请问如何修改？
另：注释掉\RequirePackage{newtxmath}后编译还是出错，提示“! LaTeX Error: File `firamono.sty' not found.”
再注释掉，会提示“! LaTeX Error: File `texnames.sty' not found.”
再注释掉就可以编译了。

**Comment by Liam0205** [comment]
你是不是系统里装了两套 TeX Live？其一是从源里装的，其二是你手动从 `.iso` 里装的？

**Comment by ShaoDP** [comment]
@Liam0205 还真有可能是，那怎么解决呢？需要卸载？还是指定路径？

**Comment by EthanDeng** [comment]
@Liam0205 名侦探 L

**Comment by Liam0205** [comment]
> @Liam0205 名侦探 L

莫要捧杀我……



> @Liam0205 如果是从源里安装的话，通过“sudo apt-get purge texlive*”应该能删除的吧？但是提示“no matches found: texlive*”，应该不是从源里安装的吧？
> 
> 如果如您所说的是，那怎么解决呢？需要卸载？还是指定路径？

我不知道呀……我好几年没用过 Ubuntu 了。

**Comment by ShaoDP** [comment]
@Liam0205 利用tlmgr重新安装了相关宏包并更新了映射，编译通过了
