### ISSUE TITLE
\displaystyle \int 没有任何效果

### ISSUE THREAD

**Issue by sierxue** [ElegantLaTeX/ElegantBook#50]
\displaystyle \int 可以使上下标分别在上下位置。但在这个模板中起不到这个效果，请问怎样才能达到这个效果？

**Comment by muzimuzhi** [comment]
1. 「使上下标分别在上下位置」具体指的是什么效果？能否通过效果截图详细说明？
2. 如果你想要的是「原来 `\int` 的上标是在斜上，如何变成正上」，应该使用 `\int\limits_a^b`。整个 latex 里都应该这么用，当前模板不是特例。

**Comment by sierxue** [comment]
谢谢！我要的就是这个效果。也许我记错了命令。
