### ISSUE TITLE
调整章节标题悬挂缩进的实现

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#51]
根据 https://github.com/ElegantLaTeX/ElegantBook/issues/49#issuecomment-524487903 和 https://github.com/ElegantLaTeX/ElegantBook/issues/49#issuecomment-524593413 ，目前章节标题悬挂缩进的距离是固定的 `2.45em`。
https://github.com/ElegantLaTeX/ElegantBook/blob/ae0d420e4954f2cc35cba577384496ab86573758/elegantbook.cls#L366-L373

在 section label 的宽度较大时，输出样式会不一致（见下图 “Before” 部分），建议修改。

假设仍燃使用悬挂风格，有多种方案，
1. 使用固定距离的悬挂缩进，缩进距离（例如为 `\sectionLabelWidth`）可设置。
2. 使用固定距离的悬挂缩进，缩进距离自动计算，为 max(某个固定距离, section label 的最大宽度 + 固定距离)。实现方式是比较并记录 section label 的最大宽度，记录在 aux 文件中，第二次编译时读取。
3. 使用可变距离的悬挂缩进，将整个 section label 悬挂出去并靠右对齐。

方案比较
 - 固定比可变更常见
 - 固定的两个方案中，1 实现简单但需要手动调整，2 实现稍复杂、需要二次编译但功能自动生效

以下例子展示了当前实现和第三种方案的效果，同时也简化了 `\titleformat` 的使用。

```latex
\documentclass{elegantbook}
\usepackage{lipsum}
\linespread{1}\selectfont

\newcommand\test[1]{
  \refstepcounter{chapter}
  \noindent{\LARGE\bfseries #1}
  \section{title}
  \setcounter{section}{10}
  \section{title}
  \setcounter{chapter}{10}
  \section{long long long long long long long long long long long long long long long long long title}
  \lipsum[23]
  \vspace{20pt}
}

\begin{document}
%% current setting
%\titleformat{\section}[hang]
%  {\bfseries}
%  {\hspace{-2.45em}\Large\bfseries{\color{structurecolor}\thesection}\enspace}
%  {1pt}
%  {\color{structurecolor}\Large\bfseries\filright}

\test{Before}

%% suggested setting
\titleformat{\section}[hang]
  {\Large\bfseries\color{structurecolor}}
  {\llap{\thesection\enspace}}
  {0pt}
  {}

\setcounter{chapter}{1}
\test{After}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/63652916-af35b600-c798-11e9-8937-1e202cfc5c62.png)

如果觉得需要该，并且能确定修改方案，我可以提供实现。

**Comment by EthanDeng** [comment]
取消吧，不太希望因为得到这个需要两次编译。

**Comment by ustcfdm** [comment]
建议实现一个可以方便取消悬挂缩进的实现，目前情况是想取消得分别在section, subsection, 和 subsubsection 里都改一变，虽然也不算很麻烦 (๑❛ᴗ❛๑)

**Comment by muzimuzhi** [comment]
> 取消吧，不太希望因为得到这个需要两次编译。

1. 模板里的其他功能，例如目录，本就需要两次编译。增加新的需要两次编译的功能，只是顺便而已。
2. 完全不考虑不需要两次编译的第一种方案吗？

**Comment by EthanDeng** [comment]
暂时不考虑了，这里还有一个考虑是在选择 `device=pad` 模式或者 `marginpar=margintrue` 时，边界会变得比较小，在章节数字比较大的时候，我不知道会不会出现其他问题。

**Comment by EthanDeng** [comment]
已经把 section/subsection 的负距离从模板文件删除了。

**Comment by muzimuzhi** [comment]
> 暂时不考虑了，这里还有一个考虑是在选择 `device=pad` 模式或者 `marginpar=margintrue` 时，边界会变得比较小，在章节数字比较大的时候，我不知道会不会出现其他问题。

有道理

另外，这属于向前不兼容的改动，建议记录进 changelog。
