### ISSUE TITLE
建议改预设的字体为推荐的，让用户自己选择字体

### ISSUE THREAD

**Issue by fyemath** [ElegantLaTeX/ElegantBook#52]
首先预设的数学字体确实符合网上流传的漂亮字体的建议。然而字体对于LaTeX 用户来说通常会造成麻烦。比如 mtpro2 和 esint。前者是付费字体，大多数用户没有，即使是mtpro2 lite的版本，可能很多用户也不熟悉。esint 由于宏包升级删去了 esint10.tfm，给使用最新版宏包的用户造成了很多麻烦。尤其是没有完全安装TeXLive 或者 MikTeX的用户。要想运行成功新的elegentbook 模板，要花很多功夫补这些字体。

所以从用户的角度，最好是给出一些推荐字体，说明这些字体的来源。让用户自己选择字体组合。
网上推荐的一些免费的字体组合，如 `\usepackage{charter}`  和 `\usepackage[charter]{mathdesign}` ,  以及 `\usepackage{libertine}` 和 `\usepackage[libertine]{newtxmath}` 都是不错的组合。并且这些字体都是免费的，且已经包含在 TeX 系统里面。

**Comment by muzimuzhi** [comment]
1. 模板默认不使用 mtpro2，即便通过文档类选项使用了，调用的依然是 mtpro2 的（可以从 CTAN 下载到的）免费子集。
2. esint 的问题，属于非常规的情况，且目前 texlive 和 miktex 都已修复 esint，更新后已经都能正常使用。
今天是 esint，明天还可能是其他的 latex 组件（在更新后）出现问题。texlive 2019 刚发布时，xelatex 使用的引擎 xdvipdfmx 就有更新导致的问题，不能因噎废食说干脆连 xelatex 也不用了。除非自己参与开发，否则用户必须接受一个有人维护的项目，在可接受的程度内出现一定问题。
3. 列出推荐的字体搭配是一个一般性的、带有审美倾向的任务，不一定是这个模板的目标。我同意模板在用户文档中列出宏包和字体依赖，但不同意模板完全不配置字体。

**Comment by EthanDeng** [comment]
`mtpro2` 和 `esint` 上面说的很清楚了，`esint` 是为了恢复原有的积分符号以及拓展其他常见的积分符号所用，目前的新版本问题只是它宏包的问题，并且已经修复。`mtpro2` 这个宏包（lite 是免费的），我记得我都没写在说明文档里，默认是 `newtx` 系列的字体，这个选项是模板用户群友的想法，并不适合所有人。

在之前修改过字体的版本文档里面说到了字体的设置细节（各个宏包控制的内容）：
+  `newtxtext`：英文 times 风格字体；
+ `newtxmath`：数学字体（大型操作符除外）；
+ `esint`：恢复大型操作符为 Computer Modern 字体；
+ `ctex`：中文字体，依赖于操作系统，具体见[官方文档](https://ctan.org/pkg/ctex) 。

关于字体美观的讨论，我并不想去过多讨论，目前这几个字体搭配是我在考虑版权，可用性，美观的基础上的最好选择（我认为的）。

**Comment by fyemath** [comment]
能在文档中列出依赖的宏包和字体，当然对用户的帮助会很大。另外也希望能减少对宏包的以来。如果两位所说，LaTeX的宏包，在更新后可能会导致一些奇怪的错误，对于大多数用户，要理解和修正这些错误是很不容易的事情。详细说明，当前可运行所需的宏包，字体及相应版本，并尽量少用宏包对于，elegant***.cls 的灵活实用性会有很大帮助。
谢谢你们为广大TeX 用户提供如此精美的宏包。

**Comment by EthanDeng** [comment]
后续有计划去整理、清理部分宏包（冗余、过时宏包），以及版本历史等信息供大家查询。模板运行所需要的版本为 TeX Live 2018 及以后，Overleaf 上的版本（内核 TeX Live 2017）可以直接运行。

**Comment by EthanDeng** [comment]
#6
