### ISSUE TITLE
修改\section换页后出现页眉错误

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#55]
```tex
\documentclass[cn,11pt,twoside]{elegantbook}
\usepackage{zhlipsum}
\titleclass{\section}{top}
\newcommand\sectionbreak{\clearpage}
\begin{document}
\chapter{Elegant\LaTeX{} 系列模板介绍}
\section{第一章}
\zhlipsum[1-10]
\section{第二章}
\zhlipsum[1]
\end{document}
```
具体表现为第五页的页眉显示为第二章而不是第一章

**Comment by muzimuzhi** [comment]
是模板的 bug，删除宏包 `titlesec` 的选项 `pagestyles` 即可
https://github.com/ElegantLaTeX/ElegantBook/blob/5fece145796fd2667e0e981f5fa22c946535c928/elegantbook.cls#L358

这个选项的作用是加载 `titleps` 宏包。猜测你遇到的问题是 `titleps` 和 `fancyhdr` 冲突了，这两个包都是用于定制页眉页脚的，而模板内部使用的是 `fancyhdr`。

**Comment by sikouhjw** [comment]
> 是模板的bug，删除宏包`titlesec`的选项`pagestyles`即可
> https://github.com/ElegantLaTeX/ElegantBook/blob/5fece145796fd2667e0e981f5fa22c946535c928/elegantbook.cls#L358
> 
> 选项对话这个作用英文的加载的英文`titleps`宏包。
> 
> 你猜测的遇到问题的英文`titleps`状语从句：`fancyhdr`冲突了，这两个包都是用于定制页眉页脚的，而模板内部使用的是`fancyhdr`，加载没有`titleps`的必要。

问题解决了，谢谢！
