### ISSUE TITLE
将例题作为练习的上级计数器

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#56]
将https://github.com/ElegantLaTeX/ElegantBook/blob/5fece145796fd2667e0e981f5fa22c946535c928/elegantbook.cls#L545-L555
移到https://github.com/ElegantLaTeX/ElegantBook/blob/5fece145796fd2667e0e981f5fa22c946535c928/elegantbook.cls#L533-L543
之前，将https://github.com/ElegantLaTeX/ElegantBook/blob/5fece145796fd2667e0e981f5fa22c946535c928/elegantbook.cls#L534-L536
改为
```tex
\newcounter{exer}[prob]
\setcounter{exer}{0}
\renewcommand{\theexer}{\theprob.\arabic{exer}}
```

**Comment by muzimuzhi** [comment]
发在这里，是为了以下的哪个目的？
1. 对特定需求提供一种解决方案
2. 希望模板修改默认行为

**Comment by sikouhjw** [comment]
> 发在这里，是为了以下的哪个目的？
> 
> 1. 对特定需求提供一种解决方案
> 2. 希望模板修改默认行为

对特定需求提供一种解决方案
