### ISSUE TITLE
比率符号的使用

### ISSUE THREAD

**Issue by stone-zeng** [ElegantLaTeX/ElegantBook#58]
有用户希望插入比率符号，如图所示：

![image](https://user-images.githubusercontent.com/18233088/66542055-04206680-eb64-11e9-8062-1f70bf2eecd8.png)

所谓「比号」是 U+2236 Ratio <code>&#x2236;</code>，注意与冒号 U+003A Colon <code>&#x3A;</code> 和全角冒号 U+FF1A Fullwidth colon <code>&#xFF1A;</code> 区分。

ElegantBook 模板所使用的西文字体并不包含这一符号，而中文字体一般是包含的。但 `xeCJK` 宏包默认把这一符号使用西文字体输出，因此需要做一些修改：

```tex
% 导言区
\xeCJKDeclareCharClass{FullRight}{"2236}
\newcommand\ratio[2]{#1^^^^2236#2}
```

第一行把 U+2236 这一符号设为 `FullRight` 字符类，使用中文字体输出，禁则处理类似冒号（右标点）；第二行定义一个命令用来方便输出，其中的 `^^^^2236` 相当于直接在代码中输入 <code>&#x2236;</code>。

使用时可采用 `\ratio{1}{5000}` 的语法。效果如下：

![image](https://user-images.githubusercontent.com/18233088/66542532-6d54a980-eb65-11e9-906e-0defae4b5ef3.png)

**Comment by EthanDeng** [comment]
备注：使用 XeLaTeX 进行编译。
