### ISSUE TITLE
在 #16 的评论不是为了争论，用不着专门对人

### ISSUE THREAD

**Issue by muzimuzhi** [ElegantLaTeX/ElegantBook#61]
如果我在 #16 下面、时隔半年的贸然回复引起了怒火，这不是我的本意。我不是为了和谁争吵而评论、而给这个项目提交的。

我会评论，恰是因为我正好在为 #46 写提交，遇到了「subtitle 为空时，纵向间距如何分配」的具体问题，想了解你对这个模板，从「设计者」角度的想法。

你说
> 包括之前拜托你去修改的封面，已经 3 个月了
> https://github.com/ElegantLaTeX/ElegantBook/issues/16#issuecomment-551698286

我没有感受到那是拜托的态度。我也需要时间调整对这个项目的态度，尝试把人和事分开。

我没有「强行要使用 latex3 的语法」，一开始提及时（https://github.com/ElegantLaTeX/ElegantBook/issues/16#issuecomment-488847805 ），我提供了资料介绍；后来你坚定了不使用 latex3 的意见，我也没有再使用过（例如 #60 ）。你更新了项目的 readme，不接受任何 pr，要求总是先在 issue 下讨论，我充分尊重并照做。在 #46 里的交流，我充分尊重你的意见，提供建议、描述功能，提供不同语法的比较，把决定权交在你的手上。

晚了很久才给 #46 写提交，中间也没有和你沟通过，我很抱歉。正如你说的，这个项目，你想做什么就做什么；我的双手也有完全行为能力。

你是不是坚持对我的意见，我无从影响；我对这个项目，会尽量保持无偏的态度。我每次在这个项目下进行活动，都会期待收到的是理性的回复。仅凭用户名、而非用户活动的内容，就做直接拒绝的决定，这不像是经过科研训练的人会做的事。对于一创建就遭关闭的 #60，我只感到遗憾。

不需要单独对我这个人、这个用户有特殊的判断；把用户信息隐去，只看用户活动提供的信息，你能看到什么、又会作出什么判断呢：提出了什么内容、反馈了哪些信息、修改了什么、修改满足或修复了什么…… 我会始终这样做，只要我收到的是理性的反馈信息。

**Comment by muzimuzhi** [comment]
大家都有脾气，只是我选择冷静的时候才参与、才提交。

**Comment by EthanDeng** [comment]
> 仅凭用户名、而非用户活动的内容，就做直接拒绝的决定，这不像是经过科研训练的人会做的事。

你还没明白我在说什么，我最后一次请你不要再做多余的事情了。
