### ISSUE TITLE
完善封面

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#62]
未来方向：
1. 弹性输出封面作者信息，避免缺少信息导致报错；
2. 封面改为自选，也即允许用户使用定制封面 PDF。

**Comment by Liam0205** [comment]
@EthanDeng GitHub 有个 milestone 的功能，适合做这个。你可以试试。

**Comment by EthanDeng** [comment]
#33 #53

**Comment by EthanDeng** [comment]
> @EthanDeng GitHub 有个 milestone 的功能，适合做这个。你可以试试。

嗯 我加上

**Comment by muzimuzhi** [comment]
模板里目前使用 token list（`\newtoken\subtitle`）来接受副标题的输入。
 - #19 和 #60 都提供了避免使用 token list，改用宏提供 `\subtitle`，然后通过判断宏是否为空来避免报错
 - 如果继续使用 token list 的机制，在 `\newtoken\subtitle` 后面加一句 `\subtitle{}` 将其初始化为空，也能避免报错。

------
本条评论，符合 readme 中「重要提示」部分的约束（由 https://github.com/ElegantLaTeX/ElegantBook/commit/a778683d146263e37ce5c38c3c1ea7c288ae2282 最后更新）。

**Comment by EthanDeng** [comment]
#68
