### ISSUE TITLE
定理类环境定义修改意见征询

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#64]
## 现有定理用法
今天在用户群，讨论到定理的问题，现有的定理形式是：
```tex
\begin{theorem}{theorem name}{label}
The content of theorem.
\end{theorem}
```
其中用到的是 `tcolorbox` 宏包的 `newtcbtheorem` 命令，对于这个定理的引用，使用 `\ref{thm:label}`。而为了兼容 `mode=simple` 和 `mode=fancy`，在 `simple` 模式下，实际调用的为 `amsthm`，即通过 `newtheorem` 命令定义。

在 ElegantBook 中，如果定理名没有或者不需要引用时，需要写成

```tex
\begin{theorem}{}{}
The content of theorem.
\end{theorem}
```

## `amsthm` 定理用法

一般通过 `amsthm` 定义的定理使用方法是 
```tex
\begin{theorem}[theorem name]\label{thm:label}
The content of theorem.
\end{theorem}
```

这种可选项作为定理名的方式有一个好处是，如果定理没有名字，也不需要引用，可以写成
```tex
\begin{theorem}
The content of theorem.
\end{theorem}
```
也就是在偷懒或者信息缺失的时候，这样写看着更加自然。

## 讨论

其实这个问题我原来也考虑过，不是考虑写起来麻烦还是不麻烦，而是兼容性问题，也就是把 ElegantBook 中的定理搬到其他模板/文类中不可以直接使用，需要修改之后才可以。我有计划改动，但由于这个定理的设置会影响到大部分人，而且是大幅度的，因此希望大家能够积极表达自己的观点。

### 改动方向：
放弃 `newtcbtheorem` 默认定理命令，改用一般环境定义命令 `tcolorboxenvironment`，结合 `amsthm` 定义定理类环境。

**注**：关于 `amsthm` 和 `ntheorem` 的讨论，请参考：[Theorem packages: which to use, which conflict?](https://tex.stackexchange.com/questions/5599/theorem-packages-which-to-use-which-conflict)

**Comment by andy123t** [comment]
我是数学专业的，用ElegantBook模板比较多，个人比较推荐amsthm定理用法

**Comment by Ky-Huang** [comment]
感觉上数学业界还是amsthm的那种写法比较多一点。。那种用起来也许更方便，因为很多定理没有名字，可以少写一个括号会比较方便，代码也更简洁；然后我个人写引用的方式是需要的时候再打上\label，也是出于偷懒和整洁的考虑吧。。。

**Comment by fyemath** [comment]
可不可以通过重新将定理名字，和label分别提取出来了，然后根据mode，来重新放回去?
