### ISSUE TITLE
文件中的*cn.tex不能通过编译，en.tex可以通过

### ISSUE THREAD

**Issue by denniscxc** [ElegantLaTeX/ElegantBook#65]
请教如何解决：

出现的error如下：
newtxmath.sty
786LaTeX Error: Command `\lvert' already defined.
See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
l.786 ...thopen}  {symbols}{106}{largesymbols}{12}

**Comment by stone-zeng** [comment]
Duplicated #59.

**Comment by EthanDeng** [comment]
新版已经调整 `amsmath` 和 `ctex` 的顺序，你用新版的吧。
