### ISSUE TITLE
请教如何改变字体

### ISSUE THREAD

**Issue by denniscxc** [ElegantLaTeX/ElegantBook#66]
如何更改字体,目前文档里面是mtpro2，却不懂如何更改，请指导

**Comment by EthanDeng** [comment]
不要加这个选项，去掉就好了。

**Comment by denniscxc** [comment]
谢谢指导，但去掉以后字体没有改变，我去掉了%\DeclareVoidOption{mtpro2}{\ekv{math=mtpro2}}
还有这个：
% fontsetting
%\ifdefstring{\ELEGANT@math}{mtpro2}{
%\let\Bbbk\relax
%\RequirePackage[lite]{mtpro2}
%}{\relax}
编译后，字体没有改变，还是和原来一样，指导一下，正确的更改是如何进行的，非常感谢

**Comment by EthanDeng** [comment]
你不需要改动 cls，只需要在使用的时候不要加上 mtpro2 选项即可，也即 
```tex
\documentclass[cn,11pt]{elegantbook}
```

**Comment by denniscxc** [comment]
\documentclass[cn,12pt]{elegantbook}
我用的是这个，没有加mtpro2选项

**Comment by EthanDeng** [comment]
那怎么是 mtpro2 字体呢？我连这个选项其实都没放在文档里，属于隐藏的。你直接传个代码上来吧，包括你的 cls 和 tex。

**Comment by denniscxc** [comment]
tex文件上传不了，是拷贝内容吗？

**Comment by EthanDeng** [comment]
你把你的文件压缩一下，通过下面这个地方传上来。

![QQ截图20191212104812](https://user-images.githubusercontent.com/8111364/70678737-e7242300-1ccd-11ea-87e8-c41c493f9d62.png)

**Comment by denniscxc** [comment]
[Template_Elegantbook309-ex1.zip](https://github.com/ElegantLaTeX/ElegantBook/files/3953605/Template_Elegantbook309-ex1.zip)

**Comment by denniscxc** [comment]
CLS文件没有改动

**Comment by denniscxc** [comment]
![dc1](https://user-images.githubusercontent.com/38495560/70678959-a37de900-1cce-11ea-954e-9b21e88878b0.jpg)
我希望用图片上的字体

**Comment by EthanDeng** [comment]
你问题描述错误了，现在字体是 newtx，不是 mtpro2。你要的是 computer modern math（也即 LaTeX 默认字体），你在导言不要加那些字体宏包啊，你自己知道想要什么，但是你都是随便加的，而且 newtxtext 和 newtxmath 都是 cls 有了的。

**Comment by denniscxc** [comment]
谢谢你指出的错误，我还未入门，请指导如何使用默认的，去掉usepackage{newtxtext}等就行了吗？

**Comment by EthanDeng** [comment]
你需要在 cls 中把下面这段全部注释掉：
```tex
\ifdefstring{\ELEGANT@math}{newtxmath}{
\RequirePackage{newtxmath}
\RequirePackage{esint}
%%% use yhmath pkg, uncomment following code
% \let\oldwidering\widering
% \let\widering\undefined
% \RequirePackage{yhmath}
% \let\widering\oldwidering

%%% use esvect pkg, uncomment following code
% \RequirePackage{esvect}

\DeclareSymbolFont{CMlargesymbols}{OMX}{cmex}{m}{n}
\let\sumop\relax\let\prodop\relax
\DeclareMathSymbol{\sumop}{\mathop}{CMlargesymbols}{"50}
\DeclareMathSymbol{\prodop}{\mathop}{CMlargesymbols}{"51}
}{\relax}
```

另外，你这个 cls 我替换为最新的了，已经把上面这段注释了。
[Template_Elegantbook309-fix.zip](https://github.com/ElegantLaTeX/ElegantBook/files/3953632/Template_Elegantbook309-fix.zip)

**Comment by denniscxc** [comment]
OK，太感谢您了！

**Comment by denniscxc** [comment]
请教一下高手：我如何制作选择项，我现在的代码如下：（但是编译通不过）

\usepackage{ifthen}
\newlength{\la}
\newlength{\lb}
\newlength{\lc}
\newlength{\ld}
\newlength{\lhalf}
\newlength{\lquarter}
\newlength{\lmax}
\newcommand{\xx}[4]{\\[.5pt]% 
 \settowidth{\la}{A.~#1~~~} 
 \settowidth{\lb}{B.~#2~~~}
  \settowidth{\lc}{C.~#3~~~}
  \settowidth{\ld}{D.~#4~~~}
  \ifthenelse{\lengthtest{\la > \lb}}  {\setlength{\lmax}{\la}}  {\setlength{\lmax}{\lb}}  
\ifthenelse{\lengthtest{\lmax < \lc}}  {\setlength{\lmax}{\lc}}  {}  
\ifthenelse{\lengthtest{\lmax < \ld}}  {\setlength{\lmax}{\ld}}  {}  
\setlength{\lhalf}{0.5\linewidth}  
\setlength{\lquarter}{0.25\linewidth} 
 \ifthenelse{\lengthtest{\lmax > \lhalf}}  
{\noindent{}A.~#1 \\ B.~#2 \\ C.~#3 \\ D.~#4 } 
 {  \ifthenelse{\lengthtest{\lmax > \lquarter}}  {\noindent\makebox[\lhalf][l]{A.~#1~~~}%    
\makebox[\lhalf][l]{B.~#2~~~}%   
 \makebox[\lhalf][l]{C.~#3~~~}%   
 \makebox[\lhalf][l]{D.~#4~~~}}%    
{\noindent\makebox[\lquarter][l]{A.~#1~~~}%      
\makebox[\lquarter][l]{B.~#2~~~}%     
 \makebox[\lquarter][l]{C.~#3~~~}%      
\makebox[\lquarter][l]{D.~#4~~~}}}}

**Comment by EthanDeng** [comment]
> OK，太感谢您了！

你下面的回复不属于这个问题，我把它删了。
