### ISSUE TITLE
宏包支持请求：用于缩略词表的 glossaries

### ISSUE THREAD

**Issue by sierxue** [ElegantLaTeX/ElegantBook#67]
书中需要缩略词表，能不能加入宏包 glossaries 的支持？谢谢！

**Comment by EthanDeng** [comment]
glossaries 并不是标准的 LaTeX 内容，你可以参考 [https://www.overleaf.com/learn/latex/Glossaries](https://www.overleaf.com/learn/latex/Glossaries)。

**Comment by sierxue** [comment]
好的，谢谢你的回复。我还不知道 glossaries 不是标准内容，学习了。
