### ISSUE TITLE
如何在左侧的目录标签里增加subsection的显示？

### ISSUE THREAD

**Issue by xyh-cosmo** [ElegantLaTeX/ElegantBook#69]
最近在写一个技术文档，想在左侧的目录标签里增加subsection的显示。目前elegantbook默认只能显示到section的层次，在快速定位到文档内容时不是很方便。请求增加一个控制目录显示层次的选项

**Comment by EthanDeng** [comment]
暂时解决方法：你在 `elegantbook.cls` 里面搜索 `\setcounter{tocdepth}{1}` ，将数字 1 改为 2 即可。选项的话下次增加吧。
