### ISSUE TITLE
目录超过一页时部分子目录会向下溢出

### ISSUE THREAD

**Issue by AGJackie** [ElegantLaTeX/ElegantBook#7]
Tex文档和目录溢出截图如下：
[MWEofelegantbook.zip](https://github.com/ElegantLaTeX/ElegantBook/files/3037891/MWEofelegantbook.zip)
![目录溢出截图](https://user-images.githubusercontent.com/49231906/55468469-01cdd480-5636-11e9-8233-fd26da59db4b.png)

**Comment by muzimuzhi** [comment]
模板在重定义 `\maketitle` 时，把 `\restoregeometry` 错误地放在 `titlepage` 环境中，导致目录部分的第一页，实际应用了封面的页面设置 `\gemetry{margin=0in}`，所以出现了
 * 目录溢出
 * log 中没有 `overfull \hbox` 警告

的问题。

已经提交 pr 修复。
