### ISSUE TITLE
lastpage宏包与\maketitle冲突

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#70]
发行版 TeX Live 2019，2019/11/28更新过一次宏包
MWE：
```tex
\documentclass[lang=cn,11pt]{elegantbook}
% title info
\title{Title}
\subtitle{Subtitle is here}
% bio info
\author{Your Name}
\institute{XXX University}
\date{\today}
% extra info
\version{1.00}
\extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}
\logo{logo.png}
\cover{cover.jpg}
\begin{document}
\maketitle
\end{document}
```
报错信息为：`Package lastpage: hyperref option pageanchor disabled.`

**Comment by EthanDeng** [comment]
```tex
\documentclass[lang=cn,11pt]{elegantbook}

% title info
\title{Title}
\subtitle{Subtitle is here}

% bio info
\author{Your Name}
\institute{XXX University}
\date{\today}

% extra info
\version{1.00}
\extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}
\logo{logo.png}
\cover{cover.jpg}

\begin{document}

\maketitle
\mainmatter
\hypersetup{pageanchor=true}

\end{document}
```

这个还是报错么？

**Comment by sikouhjw** [comment]
> 
> 
> ```
> \documentclass[lang=cn,11pt]{elegantbook}
> 
> % title info
> \title{Title}
> \subtitle{Subtitle is here}
> 
> % bio info
> \author{Your Name}
> \institute{XXX University}
> \date{\today}
> 
> % extra info
> \version{1.00}
> \extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}
> \logo{logo.png}
> \cover{cover.jpg}
> 
> \begin{document}
> 
> \maketitle
> \mainmatter
> \hypersetup{pageanchor=true}
> 
> \end{document}
> ```
> 
> 这个还是报错么？

没有报错了

**Comment by EthanDeng** [comment]
这个是原来就必须要有的一个东西，是 `lastpage` 宏包要求的。

**Comment by sikouhjw** [comment]
> 
> 
> 这个是原来就必须要有的一个东西，是 `lastpage` 宏包要求的。

是我的使用方式错了，没注意看最小示例
