### ISSUE TITLE
建议在模板中加入\frontmatter

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#71]
模板的最小示例为
https://github.com/ElegantLaTeX/ElegantBook/blob/bd16ebc36ebe609eb9d2151932dbd45a28dc8e1a/elegantbook-cn.tex#L788-L814
其中没有用到`\frontmatter`命令，这会导致一个问题，在https://github.com/ElegantLaTeX/ElegantBook/blob/master/elegantbook-cn.tex 编译出来的`pdf`文件中，`SumatraPDF`显示封面页码为`1`，第二页为`1.1`，第三页为`2`，第四页为`1.2`，第五页为`2.1`，这是不应该出现的。
有几个使用问题
- 添加序章太过繁琐
https://github.com/ElegantLaTeX/ElegantBook/blob/bd16ebc36ebe609eb9d2151932dbd45a28dc8e1a/elegantbook-cn.tex#L385-L393
- 前言一般页码为`i`、`ii`等，用数字不太好表示前言
解决方法是将
https://github.com/ElegantLaTeX/ElegantBook/blob/bd16ebc36ebe609eb9d2151932dbd45a28dc8e1a/elegantbook.cls#L728
改为`\hypersetup{pageanchor=true}`，然后这么写
```tex
\documentclass[lang=cn,11pt]{elegantbook}
\title{Title}
\subtitle{Subtitle is here}
\author{Your Name}
\institute{XXX University}
\date{\today}
\version{1.00}
\extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}
\logo{logo.png}
\cover{cover.jpg}

\begin{document}
\frontmatter
\maketitle
\chapter{content}
\tableofcontents
\mainmatter
\hypersetup{pageanchor=true}
\chapter{content}
\end{document}
```
只有第二页是`i.1`

**Comment by EthanDeng** [comment]
好

**Comment by EthanDeng** [comment]
`pageanchor` 的由是 `lastpage` 导致的，我参考了很多书籍，最终决定还是去掉吧，这样，加入 `\fontmatter` 之后，也不会有总页码不和谐的问题。

**Comment by EthanDeng** [comment]
总结：
1. 去掉 `lastpage`，也就同时不生成总页码数；
2. 去掉 `\hypersetup{pageanchor=true}`；
3. 加入 `\frontmatter`，页码将更新为 i\ii\iii 等等

**Comment by sikouhjw** [comment]
参考了 `lshort-zh-cn` 的处理方法，可以将
https://github.com/ElegantLaTeX/ElegantBook/blob/083ef244ac2d0797b7383dedacfd23e8d71b1662/elegantbook-cn.tex#L17-L19
改为
```latex
\begin{document}
\pagenumbering{Alph}
\maketitle
```
这样第一页就是 `A`，不会产生 `1.1`

**Comment by EthanDeng** [comment]
已经修改。
