### ISSUE TITLE
Error with Command already defined

### ISSUE THREAD

**Issue by nil-is-lin** [ElegantLaTeX/ElegantBook#72]
在使用過程中提示五個錯誤, 分別是
1. line 74: Command `\ulcorner' already defined. ...lcorner}{\mathopen} {AMSa}{"70}{AMSa}{"70}
2. line 75: Command `\urcorner' already defined. ...rcorner}{\mathclose}{AMSa}{"71}{AMSa}{"71}
3. line 76: Command `\llcorner' already defined. ...lcorner}{\mathopen} {AMSa}{"78}{AMSa}{"78}
4. line 77: Command `\lrcorner' already defined. ...rcorner}{\mathclose}{AMSa}{"79}{AMSa}{"79}
5. line 261: Command `\Bbbk' already defined. ...ol{\Bbbk} {\mathord}{AMSb}{"7C}

前四個定位於amsfonts.sty, 最後一個定位與 amssymb.sty.

我的環境是Ubuntu 18.04 LTS OS+TeXLive 2019, 所有的宏包已利用TeX Live Shell更新到最新。
記得以前是可以跑的，暫時未找到問題，希望對項目有所幫助。

**Comment by stone-zeng** [comment]
#59，#65

**Comment by nil-is-lin** [comment]
> #59，#65

OK，在elegantbook.cls中將
`\RequirePackage{amsmath,mathrsfs,amsfonts,amssymb}`
提到
`\RequirePackage[UTF8, scheme=plain]{ctex}`
之前，確實沒有類似錯誤出現。不過出現沒有_ntx-Bold-tlf-t1_的錯誤，應該是字體缺失，多謝！

**Comment by EthanDeng** [comment]
你用新版的 cls 还有这个问题吗？另外你这个错误可能是字体缓存的问题，你运行
```shell
sudo updmap-sys
```
试一下。

**Comment by nil-is-lin** [comment]
> 你用新版的 cls 还有这个问题吗？另外你这个错误可能是字体缓存的问题，你运行
> 
> ```shell
> sudo updmap-sys
> ```
> 
> 试一下。

感謝回覆。是新版cls，剛clone代碼沒 多久，我這裏還是需要修改ams類宏包的加載順序； 另刷新了字體緩存，試了`sudo updmap-sys`以及`sudo fc-cache -fv`都沒有改善，我用locate沒有在系統文件中找到該字體庫，再考慮是不是安裝的時候少了這部分？

**Comment by EthanDeng** [comment]
你提示的信息是 newtx 系列的字体出了问题，模板只用了两个宏包，一个 newtxtext和 newtxmath。

**Comment by nil-is-lin** [comment]
與[https://tex.stackexchange.com/questions/512797/missing-font-zplsups-regular-t1-after-catalina-update-on-macos?rq=1](Missing font 'zplsups-Regular-t1' after Catalina update on macOS)的情況類似，但具體原因還不太清楚。
