### ISSUE TITLE
建议给 `\cover` 和 `\logo` 设置缺省值

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#74]
在 `LaTeX技术交流 2 群：478023327` 遇到一个人提问，报错为缺少图片，他没有意识到 `\maketitle` 与图片之间的关系
在 https://github.com/ElegantLaTeX/ElegantBook/issues/62 完成之前，可以给 `\cover` 和 `\logo` 设置缺省值，例如 `MWE` 宏包中的图片，示意图如下：
![1](https://user-images.githubusercontent.com/49770925/72252368-1fef4900-363a-11ea-9267-ee716a1c2c58.png)
示意图实现如下：
```latex
\documentclass[lang=cn,11pt]{elegantbook}
\usepackage{mwe}
\title{Title}
\subtitle{Subtitle is here}
\author{Your Name}
\institute{XXX University}
\date{\today}
\version{1.00}
\extrainfo{Victory won\rq t come to us unless we go to it. --- M. Moore}
\logo{example-image-plain.pdf}
\cover{example-image-plain.pdf}

\begin{document}
\maketitle
\end{document}
```
具体实现如下：将https://github.com/ElegantLaTeX/ElegantBook/blob/b6e1a2e8e3d6d88d95dcc861f13fb557d474c134/elegantbook-cn.tex#L14-L15
删除，在 `cls` 中设置缺省值，这样就不会出现原因为“缺少图片”的报错，然后在说明手册中写明如果要更换封面需要加上这两个命令、在对应文件夹里加上对应的图片。
优点：
- 更加需要用户阅读手册，节省了使用成本、沟通成本

缺点：
- `MWE` 宏包的图片没有原来封面的图片优雅

可能的扩展：
- 将所有封面的命令都设置缺省值，那么最小示例 https://github.com/ElegantLaTeX/ElegantBook/blob/b6e1a2e8e3d6d88d95dcc861f13fb557d474c134/elegantbook-cn.tex#L787-L814 就不需要加参数也能正常编译了

**Comment by EthanDeng** [comment]
近日连同封面一起更新。
