### ISSUE TITLE
`problemset` 习题环境在目录中的超链接没有指定正确的链接位置

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#75]
将
https://github.com/ElegantLaTeX/ElegantBook/blob/c2a4b318ecfe513863700b091a412c4795192b0a/elegantbook.cls#L651
改为
```latex
\phantomsection\addcontentsline{toc}{section}{\texorpdfstring{\chaptername\medskip\problemsetname}{\problemsetname}}
```
解释：`\phantomsection` 命令自动产生一个超链接点，它通常用在下面的场合，为手工添加的目录项指定正确的链接位置
参考：《LaTeX 入门》，刘海洋，sec:3.2.3 电子文档与超链接

**Comment by EthanDeng** [comment]
已应用。
