### ISSUE TITLE
`solution` 环境首行与第二行垂直间距过大

### ISSUE THREAD

**Issue by sikouhjw** [ElegantLaTeX/ElegantBook#76]
https://github.com/ElegantLaTeX/ElegantBook/blob/c2a4b318ecfe513863700b091a412c4795192b0a/elegantbook.cls#L613
垂直间距是由 `\medskip` 带来的，猜测可能是想让 `custom` 与 `solution` 更加分明，将其改为
```latex
\newenvironment{solution}{\medskip\par\noindent\textbf{\color{main}\solutionname} \itshape}{\vskip2ex\par}
```

**Comment by EthanDeng** [comment]
嗯，已修改。
