### ISSUE TITLE
lstlisting环境中'$'符号导致错误

### ISSUE THREAD

**Issue by UUUVVVWWW** [ElegantLaTeX/ElegantBook#78]
```
\begin{lstlisting}[frame=none]
$ xxxxxx
\end{lstlisting}
```
编译出现 `missing $ inserted` 错误

**Comment by Liam0205** [comment]
目测是因为设置了 `mathescape = \$`。

**Comment by UUUVVVWWW** [comment]
哦，看到了。
`mathescape=<true|false>`
activates or deactivates special behaviour of the dollar sign. If activated a
dollar sign acts as TEX’s text math shift.
This key is useful if you want to typeset formulas in listings.
