### ISSUE TITLE
添加证明结束符

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#79]
如何在 proof 环境后增加证明结束符？

**Comment by EthanDeng** [comment]
在导言区加入 

```tex
\providecommand\qed{}
\renewcommand{\qed}{\hfill\ensuremath{\square}}
```

然后在 proof 环境中所需要的位置加入 `\qed`。

**Comment by EthanDeng** [comment]
实心的可以把 `\square` 换成 `\blacksquare`。

参考：
[\qed for theorems without proofs](https://tex.stackexchange.com/questions/34014/qed-for-theorems-without-proofs)

**Comment by fuzihaofzh** [comment]
请问QED符号不能自动生成吗？一般proof都是自动就有了的。
