### ISSUE TITLE
使用增加一个空白页的命令，不起作用？

### ISSUE THREAD

**Issue by daixiangdong** [ElegantLaTeX/ElegantBook#83]
使用增加一个空白页的命令，不起作用？
我使用 /newpage 或者 /clearpage 命令，编译之后都没有空白页出现？文件如下：

\documentclass[cn,a4paper,12pt]{elegantbook}
% 导言区
\input{preamble-use-part}
\begin{document}
	\frontmatter
	\maketitle	% 标题页
	\newpage
	\include{pages/preface}
	\tableofcontents
	\listoffigures
	\listoftables
	\listofmyexample
	\mainmatter
	\include{pages/part-01-new}
	\include{pages/chapter01}
	\clearpage
	\appendix
	\backmatter
	\printindex
\end{document}

**Comment by sikouhjw** [comment]
你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
```latex
\documentclass[cn,a4paper,12pt]{elegantbook}
\begin{document}
\maketitle
\mbox{}\newpage
\tableofcontents
\end{document}
```
问题来了，你为什么要手动换页？

**Comment by daixiangdong** [comment]
> 你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
> 
> ```
> \documentclass[cn,a4paper,12pt]{elegantbook}
> \begin{document}
> \maketitle
> \mbox{}\newpage
> \tableofcontents
> \end{document}
> ```
> 
> 问题来了，你为什么要手动换页？

收到，试了一下，OK了！

### **为什么要手动换页？**
1、看 BOOK 类的说明分奇数和偶数页，include 的文件会从新的一页开始，而且是从奇数页开始。如果遇到正好在偶数页的时候，前面会自动增加一个空白页。
2、但是用 elegantbook，没看到 上面的这个效果。
3、所以就想着自己手动增加一个空白页，能达到新章节都从奇数页开始。

**Comment by sikouhjw** [comment]
> 
> 
> > 你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
> > ```
> > \documentclass[cn,a4paper,12pt]{elegantbook}
> > \begin{document}
> > \maketitle
> > \mbox{}\newpage
> > \tableofcontents
> > \end{document}
> > ```
> > 
> > 
> > 问题来了，你为什么要手动换页？
> 
> 收到，试了一下，OK了！
> ### **为什么要手动换页？**
> 
> 1、看 BOOK 类的说明分奇数和偶数页，include 的文件会从新的一页开始，而且是从奇数页开始。如果遇到正好在偶数页的时候，前面会自动增加一个空白页。
> 2、但是用 elegantbook，没看到 上面的这个效果。
> 3、所以就想着自己手动增加一个空白页，能达到新章节都从奇数页开始。

这是选项 `openright/openany` 的事，参考 `texdoc lshort-zh` _sec1.4.1 文档类_

**Comment by daixiangdong** [comment]
> > > 你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
> > > ```
> > > \documentclass[cn,a4paper,12pt]{elegantbook}
> > > \begin{document}
> > > \maketitle
> > > \mbox{}\newpage
> > > \tableofcontents
> > > \end{document}
> > > ```
> > > 
> > > 
> > > 问题来了，你为什么要手动换页？
> > 
> > 
> > 收到，试了一下，OK了！
> > ### **为什么要手动换页？**
> > 1、看 BOOK 类的说明分奇数和偶数页，include 的文件会从新的一页开始，而且是从奇数页开始。如果遇到正好在偶数页的时候，前面会自动增加一个空白页。
> > 2、但是用 elegantbook，没看到 上面的这个效果。
> > 3、所以就想着自己手动增加一个空白页，能达到新章节都从奇数页开始。
> 
> 这是选项 `openright/openany` 的事，参考 `texdoc lshort-zh` _sec1.4.1 文档类_

你说的 lshort-zh，我都看过，如下：
---------------------------------------------
twoside, oneside 指定单面/双面排版。双面排版时，奇偶页的页眉页脚、页边距不同。article
和report 默认为oneside，**### book 默认为twoside。**
openright, openany 指定新的一章\chapter 是在奇数页（右侧）开始，还是直接紧跟着上
一页开始。report 默认为openany，**### book 默认为openright**。对article 无效。
----------------------------------------------

1、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为  \documentclass[a4paper,12pt]{ctexbook}，新章节自动 openright。

2、\documentclass[cn,a4paper,12pt]{elegantbook}，这样没效果，新章节不在 openright。

3、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为  \documentclass[cn, a4paper,12pt, openright]{elegantbook}，新章节还是没有在 openright，没有效果。



=======================================================
晕倒。。？ 居然 elegantbook 没有继承 book 的默认值 twoside  和 openright


**OK 了。**  ^_^

最终结果：把 \documentclass[cn,a4paper,12pt]{elegantbook}，
修改为  \documentclass[cn, a4paper,12pt,**### twoside,openright**]{elegantbook}，

新章节 就在 openright 了。

**Comment by sikouhjw** [comment]
> 
> 
> > > > 你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
> > > > ```
> > > > \documentclass[cn,a4paper,12pt]{elegantbook}
> > > > \begin{document}
> > > > \maketitle
> > > > \mbox{}\newpage
> > > > \tableofcontents
> > > > \end{document}
> > > > ```
> > > > 
> > > > 
> > > > 问题来了，你为什么要手动换页？
> > > 
> > > 
> > > 收到，试了一下，OK了！
> > > ### **为什么要手动换页？**
> > > 1、看 BOOK 类的说明分奇数和偶数页，include 的文件会从新的一页开始，而且是从奇数页开始。如果遇到正好在偶数页的时候，前面会自动增加一个空白页。
> > > 2、但是用 elegantbook，没看到 上面的这个效果。
> > > 3、所以就想着自己手动增加一个空白页，能达到新章节都从奇数页开始。
> > 
> > 
> > 这是选项 `openright/openany` 的事，参考 `texdoc lshort-zh` _sec1.4.1 文档类_
> 
> 你说的 lshort-zh，我都看过，如下：
> 
> twoside, oneside 指定单面/双面排版。双面排版时，奇偶页的页眉页脚、页边距不同。article
> 和report 默认为oneside，**book 默认为twoside**。
> openright, openany 指定新的一章\chapter 是在奇数页（右侧）开始，还是直接紧跟着上
> 一页开始。report 默认为openany，**book 默认为openright**。对article 无效。
> 
> 1、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为 \documentclass[a4paper,12pt]{ctexbook}，新章节自动 openright。
> 
> 2、\documentclass[cn,a4paper,12pt]{elegantbook}，这样没效果，新章节不在 openright。
> 
> 3、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为 \documentclass[cn, a4paper,12pt, openright]{elegantbook}，新章节还是没有在 openright，没有效果。
> 
> =======================================================
> 晕倒。。？ 居然 elegantbook 没有继承 book 的默认值 twoside 和 openright
> 
> **OK 了。** ^_^
> 
> 最终结果：把 \documentclass[cn,a4paper,12pt]{elegantbook}，
> **修改为 \documentclass[cn, a4paper,12pt,twoside,openright]{elegantbook}，**
> 
> 新章节 就在 openright 了。

看起来是 `oneside` 把 `openright` 无效化了
```latex
\documentclass[oneside,openright]{book}
\title{}
\author{}
\begin{document}
\maketitle
\chapter{1}
\end{document}
```

**Comment by daixiangdong** [comment]
> > > > > 你这个不是 MWE，问题在于不能凭空换页，至少需要空盒子
> > > > > ```
> > > > > \documentclass[cn,a4paper,12pt]{elegantbook}
> > > > > \begin{document}
> > > > > \maketitle
> > > > > \mbox{}\newpage
> > > > > \tableofcontents
> > > > > \end{document}
> > > > > ```
> > > > > 
> > > > > 
> > > > > 问题来了，你为什么要手动换页？
> > > > 
> > > > 
> > > > 收到，试了一下，OK了！
> > > > ### **为什么要手动换页？**
> > > > 1、看 BOOK 类的说明分奇数和偶数页，include 的文件会从新的一页开始，而且是从奇数页开始。如果遇到正好在偶数页的时候，前面会自动增加一个空白页。
> > > > 2、但是用 elegantbook，没看到 上面的这个效果。
> > > > 3、所以就想着自己手动增加一个空白页，能达到新章节都从奇数页开始。
> > > 
> > > 
> > > 这是选项 `openright/openany` 的事，参考 `texdoc lshort-zh` _sec1.4.1 文档类_
> > 
> > 
> > 你说的 lshort-zh，我都看过，如下：
> > twoside, oneside 指定单面/双面排版。双面排版时，奇偶页的页眉页脚、页边距不同。article
> > 和report 默认为oneside，**book 默认为twoside**。
> > openright, openany 指定新的一章\chapter 是在奇数页（右侧）开始，还是直接紧跟着上
> > 一页开始。report 默认为openany，**book 默认为openright**。对article 无效。
> > 1、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为 \documentclass[a4paper,12pt]{ctexbook}，新章节自动 openright。
> > 2、\documentclass[cn,a4paper,12pt]{elegantbook}，这样没效果，新章节不在 openright。
> > 3、把 \documentclass[cn,a4paper,12pt]{elegantbook}，修改为 \documentclass[cn, a4paper,12pt, openright]{elegantbook}，新章节还是没有在 openright，没有效果。
> > =======================================================
> > 晕倒。。？ 居然 elegantbook 没有继承 book 的默认值 twoside 和 openright
> > **OK 了。** ^_^
> > 最终结果：把 \documentclass[cn,a4paper,12pt]{elegantbook}，
> > **修改为 \documentclass[cn, a4paper,12pt,twoside,openright]{elegantbook}，**
> > 新章节 就在 openright 了。
> 
> 看起来是 `oneside` 把 `openright` 无效化了
> 
> ```
> \documentclass[oneside,openright]{book}
> \title{}
> \author{}
> \begin{document}
> \maketitle
> \chapter{1}
> \end{document}
> ```

要是不加 [oneside, openright] 的话，就继承了 book 的默认值！加上了，反而把默认值覆盖掉了！
