### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by VincentMVV** [ElegantLaTeX/ElegantBook#85]
Hi,
I need to known if some kind of localization for ElegantBook, if possible define "IT" instead of "EN" in

`\documentclass[lang=en]{elegantbook}`

I would like use your template for a juridical work in italian, because it seems perfect for my project.

May you help me?

Many thanks

**Comment by EthanDeng** [comment]
Did you try babel package under `lang=en`?

**Comment by EthanDeng** [comment]
If you want to localization of all the prefix/name of ElegantBook completely, you can refer this `\renewcommand` list/settings under **`lang=en`** language mode in your preamble. I don't know Italian, so I can't  translate for you.

```tex
\renewcommand\figref[1]{\textbf{Figure}~\ref{#1}}
\renewcommand\tabref[1]{\textbf{Table}~\ref{#1}}
\renewcommand{\chaptername}{Chapter \thechapter}
\renewcommand{\authorname}{\textbf{Author: }}
\renewcommand{\institutename}{\textbf{Institute: }}
\renewcommand{\datename}{\textbf{Date: }}
\renewcommand{\versionname}{\textbf{Version: }}
\renewcommand{\notename}{Note}
\renewcommand{\proofname}{Proof}
\renewcommand{\problemname}{Problem}
\renewcommand{\definitionname}{Definition}
\renewcommand{\theoremname}{Theorem}
\renewcommand{\axiomname}{Axiom}
\renewcommand{\postulatename}{Postulate}
\renewcommand{\lemmaname}{Lemma}
\renewcommand{\propositionname}{Proposition}
\renewcommand{\corollaryname}{Corollary}
\renewcommand{\examplename}{Example}
\renewcommand{\exercisename}{Exercise}
\renewcommand{\remarkname}{Remark}
\renewcommand{\assumptionname}{Assumption}
\renewcommand{\conclusionname}{Conclusion}
\renewcommand{\solutionname}{Solution}
\renewcommand{\propertyname}{Property}
\renewcommand{\introductionname}{Introduction}
\renewcommand{\problemsetname}{Exercise}
\renewcommand\bioinfo[2]{\gdef\@bioinfo{\textbf{#1}: #2}}
\renewcommand{\updatename}{Updates:}
\renewcommand{\historyname}{Version History}
```

**Comment by EthanDeng** [comment]
I like Aurora's painting of supporting each other, may you and your country will be fine.

![italian-china](https://user-images.githubusercontent.com/8111364/76928829-96037b00-691d-11ea-9ef9-6e4e7d418d98.jpg)

**Comment by VincentMVV** [comment]
> Did you try babel package under `lang=en`?

Thank you for answering my question.Yes, I did and it works!

**Comment by VincentMVV** [comment]
> I like Aurora's painting of supporting each other, may you and your country will be fine.
> 
> ![italian-china](https://user-images.githubusercontent.com/8111364/76928829-96037b00-691d-11ea-9ef9-6e4e7d418d98.jpg)

What a beautiful image, so rich in feeling. Thanks very much for the thought. The world is one!

**Comment by VincentMVV** [comment]
> If you want to localize of all the prefix/name of ElegantBook completely, you can refer this `\renewcommand` list/settings under **`lang=en`** language mode in your preamble. I don't know Italian, so I can't translate for you.
> 
> ```
> \renewcommand\figref[1]{\textbf{Figure}~\ref{#1}}
> \renewcommand\tabref[1]{\textbf{Table}~\ref{#1}}
> \renewcommand{\chaptername}{Chapter \thechapter}
> \renewcommand{\authorname}{\textbf{Author: }}
> \renewcommand{\institutename}{\textbf{Institute: }}
> \renewcommand{\datename}{\textbf{Date: }}
> \renewcommand{\versionname}{\textbf{Version: }}
> \renewcommand{\notename}{Note}
> \renewcommand{\proofname}{Proof}
> \renewcommand{\problemname}{Problem}
> \renewcommand{\definitionname}{Definition}
> \renewcommand{\theoremname}{Theorem}
> \renewcommand{\axiomname}{Axiom}
> \renewcommand{\postulatename}{Postulate}
> \renewcommand{\lemmaname}{Lemma}
> \renewcommand{\propositionname}{Proposition}
> \renewcommand{\corollaryname}{Corollary}
> \renewcommand{\examplename}{Example}
> \renewcommand{\exercisename}{Exercise}
> \renewcommand{\remarkname}{Remark}
> \renewcommand{\assumptionname}{Assumption}
> \renewcommand{\conclusionname}{Conclusion}
> \renewcommand{\solutionname}{Solution}
> \renewcommand{\propertyname}{Property}
> \renewcommand{\introductionname}{Introduction}
> \renewcommand{\problemsetname}{Exercise}
> \renewcommand{\updatename}{Updates:}
> \renewcommand{\historyname}{Version History}
> ```

Can I send you my translation?

**Comment by VincentMVV** [comment]
Here my translation (indent lines are the italian version)
`
%\renewcommand\figref[1]{\textbf{Figure}~\ref{#1}}
	\renewcommand\figref[1]{\textbf{Figura}~\ref{#1}}
%\renewcommand\tabref[1]{\textbf{Table}~\ref{#1}}
	\renewcommand\tabref[1]{\textbf{Tabella}~\ref{#1}}
%\renewcommand{\chaptername}{Chapter \thechapter}
	\renewcommand{\chaptername}{Capitolo \thechapter}
%\renewcommand{\authorname}{\textbf{Author: }}
	\renewcommand{\authorname}{\textbf{Autore: }}
%\renewcommand{\institutename}{\textbf{Institute: }}
	\renewcommand{\institutename}{\textbf{Istituto: }}
%\renewcommand{\datename}{\textbf{Date: }}
	\renewcommand{\datename}{\textbf{Data: }}
%\renewcommand{\versionname}{\textbf{Version: }}
	\renewcommand{\versionname}{\textbf{Versione: }}
%\renewcommand{\notename}{Note}
	\renewcommand{\notename}{Nota}
%\renewcommand{\proofname}{Proof}
	\renewcommand{\proofname}{Dimostrazione}
%\renewcommand{\problemname}{Problem}
	\renewcommand{\problemname}{Problema}
%\renewcommand{\definitionname}{Definition}
	\renewcommand{\definitionname}{Definizione}
%\renewcommand{\theoremname}{Theorem}
	\renewcommand{\theoremname}{Teorema}
%\renewcommand{\axiomname}{Axiom}
	\renewcommand{\axiomname}{Assioma}
%\renewcommand{\postulatename}{Postulate}
	\renewcommand{\postulatename}{Postulato}
%\renewcommand{\lemmaname}{Lemma}
	\renewcommand{\lemmaname}{Lemma}	%It's the same word
%\renewcommand{\propositionname}{Proposition}
	\renewcommand{\propositionname}{Proposizione}
%\renewcommand{\corollaryname}{Corollary}
	\renewcommand{\corollaryname}{Corollario}
%\renewcommand{\examplename}{Example}
	\renewcommand{\examplename}{Esempio}
%\renewcommand{\exercisename}{Exercise}
	\renewcommand{\exercisename}{Esercizio}
%\renewcommand{\remarkname}{Remark}
	\renewcommand{\remarkname}{Commento}	  %doubtful translation, because it is a 						 
                                                                                  %mathematical environment that I don't know
%\renewcommand{\assumptionname}{Assumption}
	\renewcommand{\assumptionname}{Assunto}
%\renewcommand{\conclusionname}{Conclusion}
	\renewcommand{\conclusionname}{Conclusione}
%\renewcommand{\solutionname}{Solution}
	\renewcommand{\solutionname}{Soluzione}
%\renewcommand{\propertyname}{Property}
	\renewcommand{\propertyname}{Proprietà}
%\renewcommand{\introductionname}{Introduction}
	\renewcommand{\introductionname}{Introduzione}
%\renewcommand{\problemsetname}{Exercise}
	\renewcommand{\problemsetname}{Esercizio}
%\renewcommand{\updatename}{Updates:}
	\renewcommand{\updatename}{Aggiornamenti:}
%\renewcommand{\historyname}{Version History}
	\renewcommand{\historyname}{Cronologia delle versioni}
`

**Comment by VincentMVV** [comment]
Here my translation (indent lines are the italian version)

%\renewcommand\figref[1]{\textbf{Figure}~\ref{#1}}
	\renewcommand\figref[1]{\textbf{Figura}~\ref{#1}}
%\renewcommand\tabref[1]{\textbf{Table}~\ref{#1}}
	\renewcommand\tabref[1]{\textbf{Tabella}~\ref{#1}}
%\renewcommand{\chaptername}{Chapter \thechapter}
	\renewcommand{\chaptername}{Capitolo \thechapter}
%\renewcommand{\authorname}{\textbf{Author: }}
	\renewcommand{\authorname}{\textbf{Autore: }}
%\renewcommand{\institutename}{\textbf{Institute: }}
	\renewcommand{\institutename}{\textbf{Istituto: }}
%\renewcommand{\datename}{\textbf{Date: }}
	\renewcommand{\datename}{\textbf{Data: }}
%\renewcommand{\versionname}{\textbf{Version: }}
	\renewcommand{\versionname}{\textbf{Versione: }}
%\renewcommand{\notename}{Note}
	\renewcommand{\notename}{Nota}
%\renewcommand{\proofname}{Proof}
	\renewcommand{\proofname}{Dimostrazione}
%\renewcommand{\problemname}{Problem}
	\renewcommand{\problemname}{Problema}
%\renewcommand{\definitionname}{Definition}
	\renewcommand{\definitionname}{Definizione}
%\renewcommand{\theoremname}{Theorem}
	\renewcommand{\theoremname}{Teorema}
%\renewcommand{\axiomname}{Axiom}
	\renewcommand{\axiomname}{Assioma}
%\renewcommand{\postulatename}{Postulate}
	\renewcommand{\postulatename}{Postulato}
%\renewcommand{\lemmaname}{Lemma}
	\renewcommand{\lemmaname}{Lemma}	%It's the same word
%\renewcommand{\propositionname}{Proposition}
	\renewcommand{\propositionname}{Proposizione}
%\renewcommand{\corollaryname}{Corollary}
	\renewcommand{\corollaryname}{Corollario}
%\renewcommand{\examplename}{Example}
	\renewcommand{\examplename}{Esempio}
%\renewcommand{\exercisename}{Exercise}
	\renewcommand{\exercisename}{Esercizio}
%\renewcommand{\remarkname}{Remark}
	\renewcommand{\remarkname}{Commento}	  %doubtful translation, because it is a 						 
                                                                                  %mathematical environment that I don't know
%\renewcommand{\assumptionname}{Assumption}
	\renewcommand{\assumptionname}{Assunto}
%\renewcommand{\conclusionname}{Conclusion}
	\renewcommand{\conclusionname}{Conclusione}
%\renewcommand{\solutionname}{Solution}
	\renewcommand{\solutionname}{Soluzione}
%\renewcommand{\propertyname}{Property}
	\renewcommand{\propertyname}{Proprietà}
%\renewcommand{\introductionname}{Introduction}
	\renewcommand{\introductionname}{Introduzione}
%\renewcommand{\problemsetname}{Exercise}
	\renewcommand{\problemsetname}{Esercizio}
%\renewcommand{\updatename}{Updates:}
	\renewcommand{\updatename}{Aggiornamenti:}
%\renewcommand{\historyname}{Version History}
	\renewcommand{\historyname}{Cronologia delle versioni}

**Comment by EthanDeng** [comment]
I add option of Italian with `lang=it` today, since next stable version will released after several weeks or months, you can download the latest version of `elegantbook.cls` and replace your local `elegantbook.cls` file.  I just add the translation which you provided, and add `babel` package with option `italian`, therefore, this option `lang=it` may have some other problems, **you or other Italian are welcome to provide modifications by creating issues or pull requests for this option**.

Here is some piece of code provided by [Overleaf](https://www.overleaf.com/learn/latex/Italian):

```tex
\documentclass[lang=it,math=newtx]{elegantbook}

\title{Best wishes}
\author{ddswhu}
\date{\today}

\begin{document}

\maketitle

\chapter{Test}
\section{Sezione introduttiva}
Questa è la prima sezione, possiamo aggiungere alcuni elementi aggiuntivi e tutto 
digitato correttamente. Inoltre, se una parola è troppo lunga e deve essere troncato 
babel cercherà per troncare correttamente a seconda della lingua.

\section{Teoremi Sezione}
Questa sezione è quello di vedere cosa succede con i comandi testo definendo

\[ \lim x =  \sin{\theta} + \max \{3.52, 4.22\} \]

\begin{property}
Questo è un breve riassunto dei contenuti del documento scritto in italiano.
\end{property}

\end{document}
```
The PDF looks like:
![QQ截图20200319132544](https://user-images.githubusercontent.com/8111364/77034666-78014d80-69e5-11ea-8fe1-7e7fbd5c8b26.png)

**Comment by abfek66** [comment]
This is the  french translation , but still confusing the two commands below
\renewcommand{\exercisename}{Exercice}
\renewcommand{\problemsetname}{Exercice}

[Elegant_booklang_fr.txt](https://github.com/ElegantLaTeX/ElegantBook/files/4623476/Elegant_booklang_fr.txt)

**Comment by abfek66** [comment]
\renewcommand\figref[1]{\textbf{Figure}~\ref{#1}}
\renewcommand\tabref[1]{\textbf{Tableau}~\ref{#1}}
\renewcommand{\chaptername}{Chapitre \thechapter}
\renewcommand{\authorname}{\textbf{Auteur: }}
\renewcommand{\institutename}{\textbf{Institut: }}
\renewcommand{\datename}{\textbf{Date: }}
\renewcommand{\versionname}{\textbf{Version: }}
\renewcommand{\notename}{Note}
\renewcommand{\proofname}{Démonstration}
\renewcommand{\problemname}{Problème}
\renewcommand{\definitionname}{Définition}
\renewcommand{\theoremname}{Théorème}
\renewcommand{\axiomname}{Axiôme}
\renewcommand{\postulatename}{Postulat}
\renewcommand{\lemmaname}{Lemme}
\renewcommand{\propositionname}{Proposition}
\renewcommand{\corollaryname}{Corollaire}
\renewcommand{\examplename}{Exemple}
\renewcommand{\exercisename}{Exercice}
\renewcommand{\remarkname}{Remarque}
\renewcommand{\assumptionname}{Supposition}
\renewcommand{\conclusionname}{Conclusion}
\renewcommand{\solutionname}{Solution}
\renewcommand{\propertyname}{Propriété}
\renewcommand{\introductionname}{Introduction}
\renewcommand{\problemsetname}{Exercice}
\renewcommand{\updatename}{Mises à jour:}
\renewcommand{\historyname}{Historique des versions}
