### ISSUE TITLE
chapter 编号问题

### ISSUE THREAD

**Issue by zoulixin93** [ElegantLaTeX/ElegantBook#91]
elegantbook 模板非常美观。使用时，每个Chapter 里面的section 编号都是0.1 没有按chapter 章数编号，需要怎么解决。
![WX20200405-174853](https://user-images.githubusercontent.com/31400800/78471696-c9d80080-7765-11ea-8e0f-fdfd250d9b8d.png)

**Comment by sikouhjw** [comment]
1. 如果不需要 `\chapter`，你为什么用 `book`？你需要的可能不是 `book`
2. 先打点基础再用模板，正文为什么放前言里？

**Comment by zoulixin93** [comment]
并没有把正文放到前言里面。
我的意思是，第一章里面 section的编号 和 第二章里面的section 编号 都是0.X 开头的。

**Comment by sikouhjw** [comment]
> 
> 
> 并没有把正文放到前言里面。
> 我的意思是，第一章里面 section的编号 和 第二章里面的section 编号 都是0.X 开头的。

就是因为你把内容放前言导致的
