### ISSUE TITLE
TeX Live/MacTeX 2020 问题反馈（Feedback）

### ISSUE THREAD

**Issue by EthanDeng** [ElegantLaTeX/ElegantBook#92]
大家把 TeX Live 2020 以及 MacTeX 2020 出现的问题统一发布在这里，如果要上传日志，可以通过文件或者折叠式代码贴到此处。折叠代码用法：

```md
<details>
  <summary>点击此处展开</summary>
  内容
</details>
```

<details>
  <summary>点击此处展开</summary>
  内容
</details>

**Comment by xiaohao890809** [comment]
`
/usr/local/texlive/2020/texmf-dist/tex/latex/gbt7714/gbt7714.sty:63: LaTeX Erro
r: Option clash for package natbib.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.63 \RequirePackage
                    {url}
? 
`

**Comment by EthanDeng** [comment]
```shell

! LaTeX Error: File `pgfornament.sty' not found.

```

**Comment by EthanDeng** [comment]
确认问题：gbt7714 宏包改动，使得对于 natbib 选项的传递出现问题。

综合考虑修改方案如下：

+ 4.x 版本，将不再使用 `gbt7714` 宏包以及 bibtex 支持方式，改为 biblatex。
+ next version, the three ElegantLaTeX templates **WILL NOT** use bibtex or `gbt7714`.

**Comment by WalkerSource** [comment]
Package gbt7714 Warning: The option "numbers" is obselete on input line 61.


! LaTeX Error: Option clash for package natbib.

**Comment by Liam0205** [comment]
> Package gbt7714 Warning: The option "numbers" is obselete on input line 61.
> 
> ! LaTeX Error: Option clash for package natbib.

This has been answered by https://github.com/ElegantLaTeX/ElegantBook/issues/92#issuecomment-612303854, and has been solved in: https://github.com/ElegantLaTeX/ElegantBook/commit/ae7a9ae8f6b6642ae296a4c639fff3181bc74bad#diff-e9396441dd19c88d694965e84585987fL357-R347

Please kindly have a check.

**Comment by WalkerSource** [comment]
Thank you. I got it.

**Comment by WalkerSource** [comment]
The new version still doesnot work. The latex is compiled with XeLatex +BibTex with Texstuio+ Miktex.  No PDF file is produced.

The logfile is attached. Hope it can be fixed. Thank you for the work.
[logfile.txt](https://github.com/ElegantLaTeX/ElegantBook/files/4515260/logfile.txt)

**Comment by EthanDeng** [comment]
根据 log 文件，无法辨别错误。

群里有人用 MikTeX （非 CTeX 中的 MikTeX），他们用最新版的包（没办法，这个没有版本管理）和模板没有问题。这里提供几个思路：

1. 用命令行测试一个非常简洁的代码，没问题说明你的编辑器配置可能存在问题，如果有问题看 2；
2. 更新 MikTeX 中的宏包至最新，特别是 ctex，更新之后重复 1，有问题继续看 3。
3. 加群提供更多、更及时的信息，和 MikTeX 用户交流，如果解决不了请看 4。
4. 删除 ElegantBook，并取关 ElegantLaTeX。

**Comment by WalkerSource** [comment]
I've updated the Miktex to the latest version. The new version still doesnot work. The latex is compiled with XeLatex +BibTex with Texstuio+ Miktex. No PDF file is produced.

This time, lines 151 and 23 are reported with errors. 

The logfile is attached. Hope it can be fixed. Thank you for the work.

[logfile.txt](https://github.com/ElegantLaTeX/ElegantBook/files/4519531/logfile.txt)

**Comment by EthanDeng** [comment]
`FZShuSong-Z01` 字体是选项 `chinesefont=founder` 所调用的字体，你如果没有这个字体，不要使用这个选项，见 ElegantBook 说明文档 3.3.1 部分。

![QQ截图20200423103942](https://user-images.githubusercontent.com/8111364/80053326-3b2df680-854f-11ea-9da9-718890be3ef8.png)

使用前请仔细阅读说明。

**Comment by WalkerSource** [comment]
我修改完毕，可以在TexStudio+Miktex上运行了。我自行到方正字体主页下载了字体，但是简体字体的名称后都有一个S字母。所以.cls文档中的字体名称都要修正，添加一个S。如下，
      \setCJKmainfont[BoldFont={FZHei-B01S},ItalicFont={FZKai-Z03S}]{FZShuSong-Z01S}
      \setCJKsansfont[BoldFont={FZHei-B01S},ItalicFont={FZHei-B01S}]{FZHei-B01S}
      \setCJKmonofont[BoldFont={FZHei-B01S},ItalicFont={FZHei-B01S}]{FZFangSong-Z02S}
      \setCJKfamilyfont{zhsong}{FZShuSong-Z01S}
      \setCJKfamilyfont{zhhei}{FZHei-B01S}
      \setCJKfamilyfont{zhkai}{FZKai-Z03S}
      \setCJKfamilyfont{zhfs}{FZFangSong-Z02S}
接着只要确保方正字体的名称（打开字体文档顶部可以看到），且是全部用户安装字体，那么再次重启电脑后，重新打开texstudio后，采用Xelatex+BibTex编辑，就可以获得正确运行了。谢谢你们给大家提供了这么漂亮的模板，也让我学习了新知识。谢谢。

**Comment by ziquanyang** [comment]
> ```
> /usr/local/texlive/2020/texmf-dist/tex/latex/gbt7714/gbt7714.sty:63: LaTeX Erro
> r: Option clash for package natbib.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.63 \RequirePackage
>                     {url}
> ? 
> ```

我也是这样，在TeXworks编译的时候停止输入return能继续编译，用TeXstudio编译则报错。

**Comment by sikouhjw** [comment]
> > ```
> > /usr/local/texlive/2020/texmf-dist/tex/latex/gbt7714/gbt7714.sty:63: LaTeX Erro
> > r: Option clash for package natbib.
> > 
> > See the LaTeX manual or LaTeX Companion for explanation.
> > Type  H <return>  for immediate help.
> >  ...                                              
> >                                                   
> > l.63 \RequirePackage
> >                     {url}
> > ? 
> > ```
> 
> 我也是这样，在TeXworks编译的时候停止输入return能继续编译，用TeXstudio编译则报错。

升级全部宏包

**Comment by ziquanyang** [comment]
> > > ```
> > > /usr/local/texlive/2020/texmf-dist/tex/latex/gbt7714/gbt7714.sty:63: LaTeX Erro
> > > r: Option clash for package natbib.
> > > 
> > > See the LaTeX manual or LaTeX Companion for explanation.
> > > Type  H <return>  for immediate help.
> > >  ...                                              
> > >                                                   
> > > l.63 \RequirePackage
> > >                     {url}
> > > ? 
> > > ```
> > 
> > 
> > 我也是这样，在TeXworks编译的时候停止输入return能继续编译，用TeXstudio编译则报错。
> 
> 升级全部宏包

我试试~~
