### ISSUE TITLE
lstlisting issue

### ISSUE THREAD

**Issue by jiserafini** [ElegantLaTeX/ElegantBook#94]
When I put 

\begin{lstlisting}
$sudo su
\end{lstlisting}

I receive an error saying that $ is missing.

**Comment by EthanDeng** [comment]
这是因为 listing 宏包 `mathescape` 导致的，两个方式：

1. 使用 `mathescape=true` 的情况下，定义一个数学环境中 $ 符号的命令，然后在 lstlisting 环境中使用 `\dollar` 命令：
```tex
\newcommand{\dollar}{\mbox{\textdollar}}

\begin{lstlisting}
  $\dollar$ sudo su
\end{lstlisting}
```
2. 在 `mathescape=false` 的情况下，可以直接使用 `$`
```tex
\begin{lstlisting}
  $sudo su
\end{lstlisting}
```
`mathescape` 的选项可以使用 `\lsset` 命令修改：
```tex
\lstset{mathescape=true}
```

参考资料：
1. [https://tex.stackexchange.com/questions/318572/use-dollar-sign-as-well-as-the-math-mode-in-lstlisting](https://tex.stackexchange.com/questions/318572/use-dollar-sign-as-well-as-the-math-mode-in-lstlisting)
2. [https://tex.stackexchange.com/questions/18452/use-in-lstlisting](https://tex.stackexchange.com/questions/18452/use-in-lstlisting)
