### ISSUE TITLE
书籍写作分章节问题

### ISSUE THREAD

**Issue by muyubaobao** [ElegantLaTeX/ElegantBook#95]
您好！作为一个书籍作者，其实是不希望自己所有的文字都放在一个文件里面的，我非常希望能有类似的功能，就是每一章有独立的tex文件，然后有一个总的tex文件对所有tex文件一起编译。这样对于写作非常有利，功能上面应该是不难实现的，不知道现有版本是否可以做到，谢谢！

**Comment by sikouhjw** [comment]
`texdoc lshort-zh-cn`, _sec 1.6 文件的组织方式_

你需要 `\include` or `\input`

**Comment by EthanDeng** [comment]
分章写作的话，其实用 input 或者 include 就行，当前版本用的是 bibtex，之后改为 biblatex 的时候会在文档部分说明这个的。

#93
