### ISSUE TITLE
有关bibstyle

### ISSUE THREAD

**Issue by muyubaobao** [ElegantLaTeX/ElegantBook#97]
我使用elegantbook cn的3.11版本标准包进行编译测试，发现在documentclass中改变bibstyle，例如变成bibstyle=ieeetr，或者bibstyle=abbrv, 均不能改变bibliography的格式。不知道是什么问题？我使用xelatex+bibtex编译，非常感谢大家的解答。

**Comment by EthanDeng** [comment]
1. 确保你完整运行了 xelatex bibtex xelatex xelatex
2. 如果还有问题，提供 MWE代码（把不必要的信息删去）

**Comment by sikouhjw** [comment]
明明就没问题
```tex
\documentclass[bibstyle=ieeetr]{elegantbook}
% \documentclass[bibstyle=abbrv]{elegantbook}
\begin{document}
\nocite{*}
\bibliography{xampl}
\end{document}
```

**Comment by muyubaobao** [comment]
下面是代码，我使用的中文模式，bib文件中一个是中文文献，一个是英文文献。
现在的问题是两个
1. 在我的电脑上无论如何修改bibstyle，文献的格式不会发生变化。
2. 中文文献显示有乱码

main.tex文件内容如下

\documentclass[cn,11pt,chinese,bibstyle=ieeetr]{elegantbook}
\begin{document}
刘宝红的书\cite{liubaohong_01} \\
Law的书\cite{law2000simulation}
\bibliography{reference}
\end{document}



bib文件内容如下
@book{liubaohong_01,
  title={采购与供应链管理: 一个实践者的角度},
  author={刘宝红},
  year={2019},
  publisher={机械工业出版社}
}

@book{law2000simulation,
  title={Simulation modeling and analysis},
  author={Law, Averill M and Kelton, W David and Kelton, W David},
  volume={3},
  year={2000},
  publisher={McGraw-Hill New York}
}

显示的情况如下

![显示](https://user-images.githubusercontent.com/66061323/83317212-a8732c80-a25d-11ea-9cbf-59b37e2e95fe.PNG)


感谢各位大神的帮助！

**Comment by sikouhjw** [comment]
@muyubaobao 请先编译我发的 MWE

**Comment by EthanDeng** [comment]
中文没有这些选项，原因是，这些 style 并不能处理好中文参考文献，因此中文文献用的国标，也就是 gbt7714。

**Comment by muyubaobao** [comment]
> 中文没有这些选项，原因是，这些 style 并不能处理好中文参考文献，因此中文文献用的国标，也就是 gbt7714。

好的了解了，我估计格式不变也是中文的问题。

不过，那个乱码的问题是怎么回事呢？您能帮忙看一下么？ 非常感谢！

**Comment by EthanDeng** [comment]
缺少信息导致的吧，还有 bib 文件是不是 utf8 编码格式的？

**Comment by muyubaobao** [comment]
> 缺少信息导致的吧，还有 bib 文件是不是 utf8 编码格式的？

确实是utf8编码的，我用txt打开bib文件另存为utf8。应该就可以了吧
另外，缺少信息的话，是少了哪个字段？
