### ISSUE TITLE
中文环境中的文件乱码问题

### ISSUE THREAD

**Issue by muyubaobao** [ElegantLaTeX/ElegantBook#99]
进一步测试发现，中文环境中的elegantbook文献显示有两个问题，

1. @article的作者超过3个的时候，从第四个开始作者名字是乱码。
2. 所有@book版本号及出版社字段有乱码。

bib文件的MWE code如下，bib文件的编码为utf-8

@book{test_02,
  title={美国刑法},
  author={储槐植 and 江溯},
  volume={86},
  year={1996},
  publisher={北京大学出版社}
}

@article{test_03,
  title={云计算技术发展分析及其应用探讨},
  author={王佳隽 and 吕智慧 and 吴杰 and 测试},
  journal={计算机工程与设计},
  volume={31},
  number={20},
  pages={4404--4409},
  year={2010}
}

**Comment by sikouhjw** [comment]
建议你提供最小工作示例+发行版信息+编译方式+`log` 文件，而不是单独的一段代码。

我这里测试没有任何问题
![1](https://user-images.githubusercontent.com/49770925/83319885-c13b0c80-a274-11ea-8b13-5d4c6b1cb62f.png)

**Comment by muyubaobao** [comment]
> 建议你提供最小工作示例+发行版信息+编译方式+`log` 文件，而不是单独的一段代码。
> 
> 我这里测试没有任何问题
> ![1](https://user-images.githubusercontent.com/49770925/83319885-c13b0c80-a274-11ea-8b13-5d4c6b1cb62f.png)

感谢帮忙测试。我使用的是elegantbook 3.11版本，编译方式XeLaTeX+BibTeX，我的MWE见下

main.tex内容如下

\documentclass[cn,11pt,chinese,bibstyle=ieeetr]{elegantbook}
% \documentclass[bibstyle=abbrv]{elegantbook}
\begin{document}
中文书 \cite{test_02} \\
中文文章 \cite{test_03}
\bibliography{reference}
\end{document}

bib的内容如下

@book{test_02,
  title={美国刑法},
  author={储槐植 and 江溯},
  volume={86},
  year={1996},
  publisher={北京大学出版社}
}

@article{test_03,
  title={云计算技术发展分析及其应用探讨},
  author={王佳隽 and 吕智慧 and 吴杰 and 测试},
  journal={计算机工程与设计},
  volume={31},
  number={20},
  pages={4404--4409},
  year={2010}
}

log文件见附件
[test.log](https://github.com/ElegantLaTeX/ElegantBook/files/4705122/test.log)

显示情况见图

![显示](https://user-images.githubusercontent.com/66061323/83320180-a322db80-a277-11ea-81d2-07e497abe0af.PNG)

**Comment by muyubaobao** [comment]
> 建议你提供最小工作示例+发行版信息+编译方式+`log` 文件，而不是单独的一段代码。
> 
> 我这里测试没有任何问题
> ![1](https://user-images.githubusercontent.com/49770925/83319885-c13b0c80-a274-11ea-8b13-5d4c6b1cb62f.png)

补充一下，很有意思的是，当我换成pdflatex+bibtex编译的时候，乱码都消失了。
我原来使用的是xelatex+bibtex的方式编译。

**Comment by Liam0205** [comment]
@muyubaobao 说明你用的 GBK 编码
